### ISSUE TITLE
Negative durability

### ISSUE THREAD

**Issue by SliderKP** [GC-spigot/AdvancedEnchantments#4288] opened 2024-05-14 15:29 UTC
### Describe the bug

when uses a itemsadder item with skin and enchants, durability goes negative

### How to reproduce

create a item with skin and enchant with trench or any AE and try to mine blocks.

### Screenshots / Videos

![image](https://github.com/GC-spigot/AdvancedEnchantments/assets/6493041/c2e4a799-66dc-4456-a513-141880a93ca8)
but the item in inventory looks with durability:
![image](https://github.com/GC-spigot/AdvancedEnchantments/assets/6493041/6f15d2a8-eeab-46c6-a8b0-f0c2208655f8)

### "/ae plinfo" link

https://paste.md-5.net/uhimoludum

### Server Log

https://mcpaste.io/aa9a71861b4d55df

**Comment by ThomasWega** [comment] 2024-05-14 19:07
duplicate of https://github.com/GC-spigot/AdvancedEnchantments/issues/4228

**Closed by ThomasWega** 2024-05-14 19:07 UTC
Labels: Bug: Unconfirmed
