### ISSUE TITLE
Cannot drop air on TRENCH

### ISSUE THREAD

**Issue by Omarlatif** [GC-spigot/AdvancedEnchantments#1937] opened 2021-05-05 13:59 UTC
**Describe the bug**
Cannot drop air on TRENCH / Failed to parse effect 'TRENCH' for enchant 'detonate'

**To Reproduce**
Unknown, I've received the message via Console

**Screenshots / Video**
https://gyazo.com/4410dd746030c8d657e3e035923fb501
https://pastebin.com/yV6WxXQp

## Server Information
- "/ae plinfo" link: https://paste.md-5.net/fobuhokebo
- Server log: <script src="https://gist.github.com/Omarlatif/f501cee9352b7bf4ab406921c8232ecd.js"></script>

**Comment by arceusxs2** [comment] 2021-05-07 16:49
Hello, im also getting this warn- only with air block.

**Comment by Insprill** [comment] 2021-05-07 18:22
*note here for myself* This is caused by a few blocks having different materials when placed compared to in item form. We need to check the [material is an item](https://hub.spigotmc.org/stash/projects/SPIGOT/repos/bukkit/browse/src/main/java/org/bukkit/Material.java#6858) and if it isn't try to turn it into one that is

**Comment by Insprill** [comment] 2021-05-10 23:49
Fixed in the next update

**Closed by Insprill** 2021-05-10 23:49 UTC
Labels: Bug: Confirmed, Priority: High, Resolution: Accepted
