### ISSUE TITLE
Detonate CE Bug

### ISSUE THREAD

**Issue by aki-dev23** [GC-spigot/AdvancedEnchantments#3829] opened 2023-11-27 15:54 UTC
### Describe the bug

Hello, one of my player reported that Deonate CE is duplicating these shulkers
whenever they mining it.

### How to reproduce

They're mining the shulker with 6x6 and after that the shulker duplicated

### "/ae plinfo" link

https://paste.md-5.net/bataqumaqa

### Server Log

https://mclo.gs/jun4b5M

**Comment by ThomasWega** [comment] 2023-11-28 12:57
duplicate of https://github.com/GC-spigot/AdvancedEnchantments/issues/3819

**Closed by ThomasWega** 2023-11-28 12:57 UTC
Labels: Bug: Unconfirmed
