### ISSUE TITLE
net.minecraft.server.level.PlayerInteractManager.breakBlock(PlayerInteractManager.java:370)

### ISSUE THREAD

**Issue by antibitcoin** [GC-spigot/AdvancedEnchantments#2216] opened 2021-07-31 03:05 UTC
**Describe the bug**
Error on console from time to time
[02:33:20] [Server thread/WARN]: 	at net.advancedplugins.ae.enchanthandler.ProcessEnchantment.run(ProcessEnchantment.java:304)
--
1616 | [02:33:20] [Server thread/WARN]: 	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80)
1617 | [02:33:20] [Server thread/WARN]: 	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
1618 | [02:33:20] [Server thread/WARN]: 	at net.minecraft.server.level.PlayerInteractManager.breakBlock(PlayerInteractManager.java:370)
1619 | [02:33:20] [Server thread/WARN]: 	at net.minecraft.server.level.PlayerInteractManager.a(PlayerInteractManager.java:330)
1620 | [02:33:20] [Server thread/WARN]: 	at net.minecraft.network.protocol.game.PacketPlayInBlockDig.a(PacketPlayInBlockDig.java:34)
1621 | [02:33:20] [Server thread/WARN]: 	at net.minecraft.network.protocol.game.PacketPlayInBlockDig.a(PacketPlayInBlockDig.java:8)
1622 | [02:33:20] [Server thread/INFO]: [AdvancedEnchantments] If you cannot indentify cause of this, contact developer providing this report.
1633 | [02:34:19] [Server thread/WARN]: 	at net.advancedplugins.ae.enchanthandler.ProcessEnchantment.run(ProcessEnchantment.java:304)
1634 | [02:34:19] [Server thread/WARN]: 	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80)
1635 | [02:34:19] [Server thread/WARN]: 	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
1636 | [02:34:19] [Server thread/WARN]: 	at net.minecraft.server.level.PlayerInteractManager.breakBlock(PlayerInteractManager.java:370)
1637 | [02:34:19] [Server thread/WARN]: 	at net.minecraft.server.level.PlayerInteractManager.a(PlayerInteractManager.java:330)
1638 | [02:34:19] [Server thread/WARN]: 	at net.minecraft.network.protocol.game.PacketPlayInBlockDig.a(PacketPlayInBlockDig.java:34)
1639 | [02:34:19] [Server thread/WARN]: 	at net.minecraft.network.protocol.game.PacketPlayInBlockDig.a(PacketPlayInBlockDig.java:8)
1640 | [02:34:19] [Server thread/INFO]: [AdvancedEnchantments] If you cannot indentify cause of this, contact developer providing this report.
1641 | [02:34:19] [Server thread/WARN]: 	at net.advancedplugins.ae.enchanthandler.ProcessEnchantment.run(ProcessEnchantment.java:304)
1642 | [02:34:19] [Server thread/WARN]: 	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80)
1643 | [02:34:19] [Server thread/WARN]: 	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
1644 | [02:34:19] [Server thread/WARN]: 	at net.minecraft.server.level.PlayerInteractManager.breakBlock(PlayerInteractManager.java:370)
1645 | [02:34:19] [Server thread/WARN]: 	at net.minecraft.server.level.PlayerInteractManager.a(PlayerInteractManager.java:330)
1646 | [02:34:19] [Server thread/WARN]: 	at net.minecraft.network.protocol.game.PacketPlayInBlockDig.a(PacketPlayInBlockDig.java:34)
1647 | [02:34:19] [Server thread/WARN]: 	at net.minecraft.network.protocol.game.PacketPlayInBlockDig.a(PacketPlayInBlockDig.java:8)
1648 | [02:34:19] [Server thread/INFO]: [AdvancedEnchantments] If you cannot indentify cause of this, contact developer providing this report.
1649 | [02:34:22] [Server thread/WARN]: 	at net.advancedplugins.ae.enchanthandler.ProcessEnchantment.run(ProcessEnchantment.java:304)
1650 | [02:34:22] [Server thread/WARN]: 	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80)
1651 | [02:34:22] [Server thread/WARN]: 	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
1652 | [02:34:22] [Server thread/WARN]: 	at net.minecraft.server.level.PlayerInteractManager.breakBlock(PlayerInteractManager.java:370)
1653 | [02:34:22] [Server thread/WARN]: 	at net.minecraft.server.level.PlayerInteractManager.a(PlayerInteractManager.java:330)
1654 | [02:34:22] [Server thread/WARN]: 	at net.minecraft.network.protocol.game.PacketPlayInBlockDig.a(PacketPlayInBlockDig.java:34)
1655 | [02:34:22] [Server thread/WARN]: 	at net.minecraft.network.protocol.game.PacketPlayInBlockDig.a(PacketPlayInBlockDig.java:8)
1656 | [02:34:22] [Server thread/INFO]: [AdvancedEnchantments] If you cannot indentify cause of this, contact developer providing this report.

**To Reproduce**
I guess when players using trench?

**Screenshots / Video**

## Server Information
"/ae plinfo" link: https://paste.md-5.net/vatozexapu
Server log: https://mcpaste.io/b0f5231e16958b08

**Comment by Insprill** [comment] 2021-07-31 06:04
Duplicate of #2200

**Closed by Insprill** 2021-07-31 06:04 UTC
Labels: Resolution: Duplicate
