### ISSUE TITLE
How Fix

### ISSUE THREAD

**Issue by dzakwaniqbal** [GC-spigot/AdvancedEnchantments#4418] opened 2024-07-03 14:05 UTC
### Describe the bug

I want to enchant my 2 bows, the one with enchantment power 4, which should be power 5, but it can't, after I deactivated the anvil in anvil.yml it worked again, but it's the turn of the custom enchant which can't be put together using anvil, do you can you help me so that my 2 bows can be enchanted + ce still joins the bow

### How to reproduce

Please help me

### Screenshots / Videos

https://prnt.sc/stRzkRUd08F2

### "/ae plinfo" link

https://paste.md-5.net/egagitidaw

**Comment by ThomasWega** [comment] 2024-07-06 08:14
possible duplicate of https://github.com/GC-spigot/AdvancedEnchantments/issues/4406

**Closed by ThomasWega** 2024-07-06 08:14 UTC
Labels: Bug: Unconfirmed
