### ISSUE TITLE
[Issue] Telepathy does not drop Chorus or Iron ore

### ISSUE THREAD

**Issue by PeterDorvay** [GC-spigot/AdvancedEnchantments#1487] opened 2020-10-02 23:48 UTC
**Describe the bug**
- Telepathy does not send `IRON_ORE` to the players inventory.
- Telepathy does not send `CHORUS_FLOWER` to the players inventory when broken with an axe.

**To Reproduce**
1.  Run /ae giveitem <name> diamond_pickaxe 1 telepathy:1 , then break iron ore. It won't send to inventory.
2. Run /ae giveitem <name> diamond_axe 1 telepathy:1 , then break the top block of the chorus plant. It is the chorus flower. It will be deleted instead of sending to players inventory.

**Screenshots / Video**

**Server Information (please complete the following information):**
Spigot 1.16.1 AE version 8.0.0pre8.7

**Comment by nivcoo** [comment] 2020-10-30 16:16
I've same issue with other seeds

**Comment by Insprill** [comment] 2021-03-15 22:50
The IRON issue I was not able to reproduce, nor the seed issue (not all seeds drop when you break them). the chorus flower issue will be fixed in the next update

**Closed by Insprill** 2021-03-15 22:50 UTC
Labels: issue
