### ISSUE TITLE
smelt was not works with fortune

### ISSUE THREAD

**Issue by Ecilpse** [GC-spigot/AdvancedEnchantments#2709] opened 2022-03-25 18:36 UTC
### Describe the bug

when player break 10 gold ore block with [25% smelt + fortune] pickaxe, 38 raw gold and 2gold ingot were dropped.
but with [100% smelt + fortune], only 10 gold ingot were dropped.
i think smelt is not worked with fortune.

### How to reproduce

화로: #추후 100퍼 개방
  display: "%group-color%화로"
  description: "확률적으로 광물을 채집시 가공합니다."
  applies-to: "Pickaxes"
  type: "MINING"
  group: "커먼"
  applies:
    - ALL_PICKAXE
    - ALL_SHOVEL
  levels:
    1:
      chance: 25
      effects:
        - "SMELT"
    2:
      chance: 50
      effects:
        - "SMELT"
    3:
      chance: 75
      effects:
        - "SMELT"
    4:
      chance: 100
      effects:
        - "SMELT"

### "/ae plinfo" link

https://paste.md-5.net/wiqapetiqu

**Comment by DuneSciFye** [comment] 2022-03-27 12:23
Duplicate of #2691

**Comment by Burchard36** [comment] 2022-03-29 22:02
Please check #2691 and read the latest comment I put there, if you have the same issue please re-open a new github issue, or open a ticket on our discord: https://discord.gg/pQkfYRU5ky

**Comment by Burchard36** [comment] 2022-03-30 11:01
Fix will be added to 8.9.9, please allow a few hours for this version to be uploaded, have a nice day!

**Comment by NCSV** [comment] 2022-03-30 16:14
> Fix will be added to 8.9.9, please allow a few hours for this version to be uploaded, have a nice day!

i updated 8.9.9, MORE_DROPS works with fortune, but SMELT still not works.
@Burchard36

**Comment by NCSV** [comment] 2022-03-30 16:16
![1](https://user-images.githubusercontent.com/25452835/160882366-54061474-0940-46e7-9ad8-12bf5afc621d.PNG)

**Comment by Burchard36** [comment] 2022-03-31 08:24
Hey there, looking into this issue now

**Comment by Burchard36** [comment] 2022-03-31 08:45
Hello, tested this on my local machine and I could not reproduce this error or this issue you are currently having.

Video: https://www.youtube.com/watch?v=g9r_VuJLzgw

Question, what blocks are you breaking to receive this error? Can you provide to me a video of you breaking these blocks, with the enchantments you have on your pickaxe to replicate this issue? If possible also send me your config.yml too!

**Comment by NCSV** [comment] 2022-03-31 10:35
> Hello, tested this on my local machine and I could not reproduce this error or this issue you are currently having.
> 
> Video: https://www.youtube.com/watch?v=g9r_VuJLzgw
> 
> Question, what blocks are you breaking to receive this error? Can you provide to me a video of you breaking these blocks, with the enchantments you have on your pickaxe to replicate this issue? If possible also send me your config.yml too!

i didn't find what blocks that i recived error but you can see the video only can get 1 ore items (even redstone drops 1)
[pickaxe has enchanted fortune 3 / 100% smelt]

https://www.youtube.com/watch?v=pDSrkUO_jtA

**Comment by Burchard36** [comment] 2022-03-31 11:28
Okay I see now, apologies for this inconvenience 

This bug will be fixed in 8.9.10, sorry!

Hope you have a nice day :)

**Comment by NCSV** [comment] 2022-03-31 13:20
> Okay I see now, apologies for this inconvenience
> 
> This bug will be fixed in 8.9.10, sorry!
> 
> Hope you have a nice day :)

more-drops only works with ore blocks?
after update, player noticed to me when break crops with MORE_DROPS,
was not applied properly.

**Comment by Burchard36** [comment] 2022-04-01 12:10
> after update, player noticed to me when break crops with MORE_DROPS was not applied properly.

Are you sure you setup this enchantment to work with Crops? Can you sent the enchantment you are currently using to multiple crops? (The default multiplication enchant only works for ORES so yes to answer the other question yes MORE_DROPS only works for ores unless you configure the conditions to word with blocks other than ones contianing ORE in the name, you need to create another one for crops)

In reguards to VEIN_MINE, ill look into the issue and see, I assume you mean vanilla fortune correct?

**Comment by Burchard36** [comment] 2022-04-26 20:41
Hey there, this should be fixed update to the latest version, open a new issue mentioning this one if its not :)

**Closed by Burchard36** 2022-04-26 20:41 UTC
Labels: Type: Enchant Conflict, Resolution: Accepted
