### ISSUE TITLE
Your license exceeded maximum number of unique IPs. Contact the developer for an enterprise license or connect using previously used IPs.

### ISSUE THREAD

**Issue by colinpapa** [GC-spigot/AdvancedEnchantments#3995] opened 2024-02-07 14:47 UTC
### Describe the bug

Your license exceeded maximum number of unique IPs. Contact the developer for an enterprise license or connect using previously used IPs.

### How to reproduce

Your license exceeded maximum number of unique IPs. Contact the developer for an enterprise license or connect using previously used IPs.

### "/ae plinfo" link

can't

**Comment by SirJben** [comment] 2024-02-07 14:55
Duplicate of #3994.

**Closed by SirJben** 2024-02-07 14:55 UTC
Labels: Resolution: Duplicate, Bug: Unconfirmed
