### ISSUE TITLE
[Issue] Events on Custom Weapons do not work

### ISSUE THREAD

**Issue by Leomelonseeds** [GC-spigot/AdvancedEnchantments#1780] opened 2021-03-14 08:32 UTC
Hey there,

I'd like to remind that #1582 is still present, and has been that way since custom weapons were released. I'm sorry to bring this up repeatedly but a long-standing, major issue like this should definitely take priority to be fixed. Please take consideration of this request.

Present on the latest 8.0-Pre21.1 version.

Thanks for your time.

**Comment by Insprill** [comment] 2021-03-30 02:02
Duplicate of #1582

**Closed by Insprill** 2021-03-30 02:02 UTC
Labels: Resolution: Duplicate
