### ISSUE TITLE
Issues with multiple enchants

### ISSUE THREAD

**Issue by rexmen123** [GC-spigot/AdvancedEnchantments#4664] opened 2024-10-03 02:23 UTC
### Describe the bug

Having issues with multiple enchants from advanced enchantments plugin
1. Telepathy Enchant
1.1 It uses durability on Unbreakable items as well.
1.2 When using hoes to break sugarcane with Telepathy, it consumes durability, which it shouldn't, since breaking sugarcane shouldn’t affect durability.

2. Trench Enchant
2.1 It causes significant lag.
2.2 Even with the "drops to inventory" option enabled in the config, it doesn’t work at all.
2.3 Trench also reduces the durability of tools that have Unbreakable.

3. Soulbound
3.1 It leads to duping issues.

### How to reproduce

I have no idea how can you produce exact setup as mine on your server.. without having same plugins as mine...

### Screenshots / Videos

Telepathy causing double durability loss than it should...  For blocks whcih doesn't even uses durablity when breaking with any tool are also reducing the durrablity.. Grass, sugarcane etc
https://jmp.sh/s/icOGJYppWU50APYYv89F 

Spark report for ticks only going above 300
https://spark.lucko.me/4gkVwkQcGk

### "/ae plinfo" link

https://paste.md-5.net/esahumezab

**Comment by rexmen123** [comment] 2024-10-03 02:29
For soulbound when player dies it dupes randomly, not everytime but most of the time

**Comment by rexmen123** [comment] 2024-10-03 03:09
New enchant issue
Multiplcation 
    '1':
      chance: 100
      conditions:
        - '%block type% contains ORE : %allow%'
      effects:
        - MORE_DROPS:1  
        
        this should give me double diamond ore when mining with silk touchh but it doesnt and withut silktouch also 1 diamond each time..

**Comment by Rexmen1** [comment] 2024-10-03 14:28
Can ignore multiplication enchant, its fixed by changing to more_drops:2

**Comment by Rexmen1** [comment] 2024-10-03 14:41
https://gyazo.com/eb8265fe5c93a73ee4fb52203c9f7bc3
New issue confirmed, With replanter its using 3 carrots instead of 1 when replacing, Look at the amount getting deducting when replanting is happening in hotbar...

**Comment by Rexmen1** [comment] 2024-10-05 16:10
trench lag issue is seprate plugin so can ignore it

**Comment by ThomasWega** [comment] 2024-10-05 21:01
The trench lag is most likely caused by a plugin conflict with ConditionalEvents. Outside of that the only issue I can see happening is 1.2, otherwise everything should work fine. I will need to test to make sure though. Please test on a fresh server with only latest AE installed. No other plugins

**Comment by Rexmen1** [comment] 2024-10-08 05:23
2.2 Even with the "drops to inventory" option enabled in the config, it doesn’t work at all.

**Comment by Rexmen1** [comment] 2024-10-08 05:24
that doesn't work either

**Comment by Rexmen1** [comment] 2024-10-08 05:24
Soulbound
3.1 It leads to duping issues.

**Comment by Rexmen1** [comment] 2024-10-08 05:25
there has to be a way to test whats causing the dupe? only happens when I add soulbound on tool, otherwise no how can that be other plugin's fault,

**Comment by Rexmen1** [comment] 2024-10-08 05:33
https://gyazo.com/6076b443d2720d31719a88fb3da65399
only 1 plugin Advanced enchantments 
paper server
in config on right check line number 585
still trench auto add into inv doesn't work

**Comment by Rexmen1** [comment] 2024-10-08 05:39
https://gyazo.com/eb8265fe5c93a73ee4fb52203c9f7bc3
New issue confirmed, With replanter its using 3 carrots instead of 1 when replacing, Look at the amount getting deducting when replanting is happening in hotbar...

**Comment by Rexmen1** [comment] 2024-10-08 05:39
Even after showing the gif proofs you are ignoring all these issues

**Comment by GC-spigot** [comment] 2024-10-08 09:20
Reply to your review:

1.1: https://gyazo.com/d291b8bdf18347deded470acf057174c no durability damage with telepathy and unbreaking items, we may need to test with your exact configuration. This is default configuration.
1.2 Solved in an update today (already fixed internally)

2.1 Solved in update scheduled today
2.2 Same, cannot recreate, may need your configuration

3.1 Again, maybe configuration or enchantment mix is the cause, cannot recreate https://gyazo.com/b2fdb127511860eabe64c621966bddfa

Share your configuration, cause clearly we with default configuration cannot recreate your problems. Stop spamming replies and actually include useful information instead of blaming us for not helping you.

**Comment by Rexmen1** [comment] 2024-10-08 10:54
So now im being toxic? when all just I'm trying to do is get my issues resolved, No one has time to go on and post all this again n again just to be denied every single time. If there is possible to debug and find exact cause let me know as debug system built in with this plugin isn't that helpful when finding the causes. N the issue with soulbound dupe is very random... I guess no more support is needed in case its not an issue. Just close the ticket, Im not gonna bother you guys anymore.

**Comment by Rexmen1** [comment] 2024-10-08 11:02
Clearly im having issues and clearly its with advanced enchantment plugin..
its all visible in gifs

https://ptero.co/titunujifa.yaml

**Comment by Rexmen1** [comment] 2024-10-08 11:04
1.1: https://gyazo.com/d291b8bdf18347deded470acf057174c no durability damage with telepathy and unbreaking items, we may need to test with your exact configuration. This is default configuration.

as I said telepathy is reducing durability on sugarcane etc blocks which doesn't reduce durability did u checked

**Comment by Rexmen1** [comment] 2024-10-08 11:05
https://gyazo.com/89b63b7953059a83045c186ef93880a6


this was tested with 1 plugin on the server nothing else
AE

**Comment by GC-spigot** [comment] 2024-10-08 11:05
> 1.1: https://gyazo.com/d291b8bdf18347deded470acf057174c no durability damage with telepathy and unbreaking items, we may need to test with your exact configuration. This is default configuration.
> 
> as I said telepathy is reducing durability on sugarcane etc blocks which doesn't reduce durability did u checked

Already mentioned this is fixed for an update which is scheduled today.


> https://gyazo.com/89b63b7953059a83045c186ef93880a6
> 
> this was tested with 1 plugin on the server nothing else AE

Default configuration?

**Comment by Rexmen1** [comment] 2024-10-08 11:07
only thing was changed was to make it go trenched blocks into inv, why does it matter if default or changed? but here is the config for enchantment

trench:
  display: '%group-color%Trench'
  description: Breaks in upto 3x3 area.
  applies-to: Pickaxes, Shovels
  type: MINING
  group: RARE
  enabled: true
  applies:
    - ALL_PICKAXE
    - ALL_SPADE
  levels:
    '1':
      effects:
        - BREAK_BLOCK @Trench{r=3}`

**Comment by GC-spigot** [comment] 2024-10-08 11:07
> only thing was changed was to make it go trenched blocks into inv, why does it matter if default or changed? but here is the config for enchantment
> 
> trench: display: '%group-color%Trench' description: Breaks in upto 3x3 area. applies-to: Pickaxes, Shovels type: MINING group: RARE enabled: true applies: - ALL_PICKAXE - ALL_SPADE levels: '1': effects: - BREAK_BLOCK @trench{r=3}`

Yes this is solved already for today's update, as mentioned in review and in my reply above.

**Comment by GC-spigot** [comment] 2024-10-08 11:07
Only remaining issues are with crops and unbreakable, crops it's working perfectly for me and my developer, so maybe you have more than 1 enchant on the hoe item? For unbreakable have you tested without other plugins?

**Comment by Rexmen1** [comment] 2024-10-08 11:08
and just tested telepathy using durablity on fresh server with just AE plugin
it causes durability loss there

**Comment by GC-spigot** [comment] 2024-10-08 11:08
> and just tested telepathy using durablity on fresh server with just AE plugin it causes durability loss there

Are you talking about `Unbreakable` items or with sugarcanes? With sugar canes it's fixed for today's update, which is not yet posted...

**Comment by GC-spigot** [comment] 2024-10-08 11:09
If you are talking about `Unbreakable` items, are you using default configuration? I feel like there is miscommunication here.

**Comment by Rexmen1** [comment] 2024-10-08 11:09
telepathy:
  display: '%group-color%Telepathy'
  description: |-
    Automatically places blocks broken
    by tools in your inventory.
  applies-to: Tools
  type: MINING
  group: LEGENDARY
  applies:
    - ALL_TOOLS
  levels:
    '1':   
      effects:
        - TP_DROPS @Block

**Comment by Rexmen1** [comment] 2024-10-08 11:10
im talking about in general, unbreakable or non unbreakable both loosing durability when used telepathy for the blocks which aren't supposed to loose durability

**Comment by GC-spigot** [comment] 2024-10-08 11:11
> im talking about in general, unbreakable or non unbreakable both loosing durability when used telepathy for the blocks which aren't supposed to loose durability

I said this is fixed already, with sugar canes, for today's update. Please read what I said in my reply to your review or the 5 other replies stating this previously. `Unbreakable` items are very different from sugarcane problem. If you do not reply to my questions I can't really help, cause I do not understand what the problem is now. 

Sugar canes are fixed for today, same with trench-autoadd setting from config.

**Comment by Rexmen1** [comment] 2024-10-08 11:13
its not just sugarcane, all possible blocks did u fixed all?

**Comment by GC-spigot** [comment] 2024-10-08 11:13
> its not just sugarcane, all possible blocks did u fixed all?

These are the blocks which ignore durability damage when broken with telepathy or trench:
![image](https://github.com/user-attachments/assets/6b8f5746-f0ba-4480-85b2-9815307857e9)

**Comment by Rexmen1** [comment] 2024-10-08 11:14
i think unbreakble durablity is related to telepathy and will auto fixed with it

**Comment by GC-spigot** [comment] 2024-10-08 11:14
Alright well then issues are now fixed, as we talked in discord. That is why I do not understand the re-posting of reviews, when I promised they will be fixed. That is why I am frustrated now.

**Comment by Rexmen1** [comment] 2024-10-08 11:15
and i was frustrated because your dev said only one issue is accepted rest are not...

"The trench lag is most likely caused by a plugin conflict with ConditionalEvents. Outside of that the only issue I can see happening is 1.2, otherwise everything should work fine. I will need to test to make sure though. Please test on a fresh server with only latest AE installed. No other plugins"

**Comment by Rexmen1** [comment] 2024-10-08 11:15
2.2 Even with the "drops to inventory" option enabled in the config, it doesn’t work at all.
this issue also fixed?

**Comment by Rexmen1** [comment] 2024-10-08 11:16
2.2 Same, cannot recreate, may need your configuration
nope u said can not recreate
like what there is to recreate, its just an option in config to toggle

**Comment by GC-spigot** [comment] 2024-10-08 11:17
> 2.2 Even with the "drops to inventory" option enabled in the config, it doesn’t work at all. this issue also fixed?

That's 2.1 not 2.2... 
![image](https://github.com/user-attachments/assets/03eb1452-8ad3-49c7-a8b3-499f2a0548dc)

![image](https://github.com/user-attachments/assets/62436543-34be-496d-8633-88f99f42fbdb)

Did you read my reply, man?



> and i was frustrated because your dev said only one issue is accepted rest are not...
> 
> "The trench lag is most likely caused by a plugin conflict with ConditionalEvents. Outside of that the only issue I can see happening is 1.2, otherwise everything should work fine. I will need to test to make sure though. Please test on a fresh server with only latest AE installed. No other plugins"

"I will need to test to make sure though".



> 2.2 Same, cannot recreate, may need your configuration nope u said can not recreate like what there is to recreate, its just an option in config to toggle

Oh my god man, 2.1 is fixed, 2.2 is the durability, not trench-autoadd. That is fixed with sugarcanes now.

**Comment by Rexmen1** [comment] 2024-10-08 11:19
english is not my first language sorry if its confusing

**Comment by Rexmen1** [comment] 2024-10-08 11:19
we both want 1 thing, get our issues resolved and move on...

**Comment by Rexmen1** [comment] 2024-10-08 11:20
i guess then everything is fixed, im gonna test after the update

**Comment by GC-spigot** [comment] 2024-10-08 11:21
> ![image](https://private-user-images.githubusercontent.com/35670389/374533743-39adbe19-cf6a-4a74-9773-d42f3e1e8f50.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjgzODY2MjcsIm5iZiI6MTcyODM4NjMyNywicGF0aCI6Ii8zNTY3MDM4OS8zNzQ1MzM3NDMtMzlhZGJlMTktY2Y2YS00YTc0LTk3NzMtZDQyZjNlMWU4ZjUwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDA4VDExMTg0N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk5MzQ0YjZjZTM4NTYzMzQ1NjUxZTQ2ZDI5ZGNmZDM5ZjZjYmViNmNkYmIzNzExMGNmMTM1YTgxZjNjNWZlNmYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.jsPjAoNxUI68JtEWx7goph7HrrH8M_tNcA1Z31Dx4oc) ![image](https://private-user-images.githubusercontent.com/35670389/374533855-bb1ad6df-a424-482b-a369-87e07966533a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjgzODY2MjcsIm5iZiI6MTcyODM4NjMyNywicGF0aCI6Ii8zNTY3MDM4OS8zNzQ1MzM4NTUtYmIxYWQ2ZGYtYTQyNC00ODJiLWEzNjktODdlMDc5NjY1MzNhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDA4VDExMTg0N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE5NzA5Yjk3M2U5YmQyZWM1NjI2MTgxNzc3NmYwMWIxMGNlYjY3OGQxOWVmOWZlOTFjZTA1MjNiNzA0M2ZjZWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.CHfQw0YQKUpOwDKywGDPgIPCnTnXsijJvk9_aqJiRAk)

Why are Spigot review's naming scheme and here on git different? This makes it impossible to discuss. English is not my first language either, language is not the problem, it's the spam of replies. 

2.2. from github is fixed, as I said in my reply, which I have now stated 6 times that `trench-autoadd` setting is fixed.

**Comment by GC-spigot** [comment] 2024-10-08 11:21
> i guess then everything is fixed, im gonna test after the update

Which is what we discussed on Discord, that your problems will be fixed in 1-2 updates...

**Comment by Rexmen1** [comment] 2024-10-08 11:21
ok ty

**Comment by Rexmen1** [comment] 2024-10-08 11:21
> > i guess then everything is fixed, im gonna test after the update
> 
> Which is what we discussed on Discord, that your problems will be fixed in 1-2 updates...

you said diff thing, your dev said diff, that's why I thought those issues are not even considered

**Comment by GC-spigot** [comment] 2024-10-08 11:23
> > > i guess then everything is fixed, im gonna test after the update
> > 
> > 
> > Which is what we discussed on Discord, that your problems will be fixed in 1-2 updates...
> 
> you said diff thing, your dev said diff, that's why I thought those issues are not even considered

He said they should work but he has not tested them, never said they will not be fixed or tested. We'll work on our replies but this github ticket was never dismissed.

**Comment by Rexmen1** [comment] 2024-10-08 11:25
Sorry for my part then bcz of confusion

**Comment by GC-spigot** [comment] 2024-10-08 11:26
> Sorry for my part then bcz of confusion

As you've said, we all want issues to be solved. Update will be out in ~8h, still testing it etc. Let us know if your issues are solved, if you still have any problems you let us know here and they will be solved update after. From my testing it's looking good now.

**Closed** 2024-10-16 09:51 UTC
Labels: Status: Lacking Critical Information, Bug: Unconfirmed, Status: Awaiting Response
