### ISSUE TITLE
Infinite wood + major server lag when using treefeller enchant effect

### ISSUE THREAD

**Issue by HalfloveJAR** [GC-spigot/AdvancedEnchantments#3875] opened 2023-12-23 23:51 UTC
### Describe the bug

When you use the treefeller enchant on an axe the same time someone uses an mcmmo treefeller ability the server lags badly and the player receives infinite logs as shown in the video attached.

I'm aware this is a compatibility issue more than a bug, but it's a really nasty one that can probably be fixed. I figured you may be willing to fix it since McMMO is such a popular plugin and others will surely experience this too. Thank you!

### How to reproduce

1. Install Mcmmo
2. Right click an axe with a treefeller enchant to enable the mcmmo ability
3. Chop any tree

### Screenshots / Videos

https://github.com/GC-spigot/AdvancedEnchantments/assets/29326375/677a71f7-1c9c-41de-8ccc-e00e96dcfe18

### "/ae plinfo" link

https://paste.md-5.net/nisirugoxu

**Comment by ThomasWega** [comment] 2023-12-24 08:26
duplicate of https://github.com/GC-spigot/AdvancedEnchantments/issues/3423

**Closed by ThomasWega** 2023-12-24 08:26 UTC
Labels: Bug: Unconfirmed
