### ISSUE TITLE
EFFECT_STATIC were not working sometimes.

### ISSUE THREAD

**Issue by Ecilpse** [GC-spigot/AdvancedEnchantments#2698] opened 2022-03-19 15:46 UTC
### Describe the bug

somtimes EFFECT_STATIC with effect was not work properly,
when player re-equpped armor, and then works.
but this problems was happend quite often so players were annoyed.

### How to reproduce

경공: #3레벨(스피드2) 추후개방
  display: "%group-color%경공"
  description: "장착시 이동속도가 증가합니다."
  applies-to: "부츠"
  type: "EFFECT_STATIC"
  group: "언커먼" #레전더리
  applies:
    - ALL_BOOTS
  levels:
    1:
      effects:
        - "POTION:SPEED:0"
    2:
      effects:
        - "POTION:SPEED:1"

make EFFECT_STATIC enchantment like this and test.

### "/ae plinfo" link

https://paste.md-5.net/oxurikuwan

**Comment by Burchard36** [comment] 2022-04-17 06:25
https://user-images.githubusercontent.com/48583030/163703126-9f764fee-aa3a-491e-941f-ceff6d4ef710.mp4

Hello, so this bug was replicable on my end, but it was VERY hard to replicate (I'm talking about every 50 equips is happened)

I did some further research, implemented a possible fix but this bug still happens VERY rarely (every few hundred armors equips) I fiddled with this and came to a conclusion:

This bug is more or less caused by Lag on the Server & Client side, where for 1 tick the server cant detect the armor equipped, I managed to mitigate a lot of this lag but unfortunately, I can't take this to where it is perfect 100% of the time, I will continue to look into this further (I spent over and a half on this bug already) but it just seems the bug replication is not reliable enough to where we can implement a proper fix, as its hard to simulator TPS drops as well as Player lag in perfect harmony to replicate this bug

Apologies that this isn't fixable 100%, but the latest fix should help mitigate the bug by ten-fold

If you manage to get this replicable in a video, please do send a video like that is a lot more helpful for us (You can see in the video I sent, I spent over 3 minutes equipping and un-equipping the armor and at the end, the bug happens. the original video was over 8 minutes long but I shortened it so you can witness me attempting to replicate this bug

The fix I implemented will be available in 8.9.14

**Comment by Burchard36** [comment] 2022-04-26 20:42
Closing due to a partial fix being added, if this bug still persist consistently please open another issue :)

**Closed by Burchard36** 2022-04-26 20:42 UTC
Labels: Bug: Confirmed, Type: Performance
