### ISSUE TITLE
Permanent effect using hoppers

### ISSUE THREAD

**Issue by LuluxClient** [GC-spigot/AdvancedEnchantments#1861] opened 2021-04-10 15:45 UTC
## Details

**Describe the bug**

You get a permanent effect for example GEARS II (gives you speed 2) and it will be permanent
**To Reproduce**

Right click a hopper to open it with the item that has the custom enchant on and you have the effect without having to put the armor on. 
**Screenshots / Video**

https://gyazo.com/b5203d609c171df4422593aa0bb93709

## Server Information
- "/ae plinfo" link: 
- Server log: 
server : 1.8.8 paper latest
Plugin : 8.0.0-Pre22.6

**Comment by Insprill** [comment] 2021-04-13 07:05
Duplicate of #1859

**Closed by Insprill** 2021-04-13 07:05 UTC
Labels: Resolution: Duplicate
