### ISSUE TITLE
EnchantItemEvent to AdvancedEnchantments v8.5.2 Error Spams console

### ISSUE THREAD

**Issue by EchocallingEarth** [GC-spigot/AdvancedEnchantments#2180] opened 2021-07-21 19:43 UTC
## Details

**Describe the bug**
[12:31:00] [Server thread/ERROR]: Could not pass event EnchantItemEvent to AdvancedEnchantments v8.5.2
java.lang.ArrayIndexOutOfBoundsException: Index -1 out of bounds for length 3
	at net.advancedplugins.ae.enchantmentTable.ETableHandler.getCount(ETableHandler.java:116) ~[?:?]
	at net.advancedplugins.ae.enchantmentTable.EnchantmentTableClick.onEnchant(EnchantmentTableClick.java:55) ~[?:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor773.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.17.1.jar:git-Purpur-1287]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.17.1.jar:git-Purpur-1287]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.17.1.jar:git-Purpur-1287]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:624) ~[patched_1.17.1.jar:git-Purpur-1287]
	at net.minecraft.world.inventory.EnchantmentMenu.lambda$clickMenuButton$1(EnchantmentMenu.java:262) ~[?:?]
	at net.minecraft.world.inventory.ContainerLevelAccess.lambda$execute$0(ContainerLevelAccess.java:61) ~[?:?]
	at net.minecraft.world.inventory.ContainerLevelAccess$2.evaluate(ContainerLevelAccess.java:48) ~[?:?]
	at net.minecraft.world.inventory.ContainerLevelAccess.execute(ContainerLevelAccess.java:60) ~[?:?]
	at net.minecraft.world.inventory.EnchantmentMenu.clickMenuButton(EnchantmentMenu.java:246) ~[?:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.handleContainerButtonClick(ServerGamePacketListenerImpl.java:2973) ~[?:?]
	at net.minecraft.network.protocol.game.ServerboundContainerButtonClickPacket.handle(ServerboundContainerButtonClickPacket.java:17) ~[?:?]
	at net.minecraft.network.protocol.game.ServerboundContainerButtonClickPacket.handle(ServerboundContainerButtonClickPacket.java:6) ~[?:?]
	at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$1(PacketUtils.java:56) ~[?:?]
	at net.minecraft.server.TickTask.run(TickTask.java:18) ~[patched_1.17.1.jar:git-Purpur-1287]
	at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:149) ~[?:?]
	at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:23) ~[?:?]
	at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1422) ~[patched_1.17.1.jar:git-Purpur-1287]
	at net.minecraft.server.MinecraftServer.shouldRun(MinecraftServer.java:190) ~[patched_1.17.1.jar:git-Purpur-1287]
	at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:122) ~[?:?]
	at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1400) ~[patched_1.17.1.jar:git-Purpur-1287]
	at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1393) ~[patched_1.17.1.jar:git-Purpur-1287]
	at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:132) ~[?:?]
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1471) ~[patched_1.17.1.jar:git-Purpur-1287]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1270) ~[patched_1.17.1.jar:git-Purpur-1287]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319) ~[patched_1.17.1.jar:git-Purpur-1287]
	at java.lang.Thread.run(Thread.java:831) [?:?]
[12:31:00] [Server thread/INFO]: SteveWeathers has made the advancement [Enchanter]

**To Reproduce**
Unknown how to reproduce

**Screenshots / Video**
NA

## Server Information
https://paste.md-5.net/ogoqowihir

https://pastebin.com/EfZE0Xw1

Additional info upon request

**Comment by Insprill** [comment] 2021-07-21 21:15
Duplicate of #2132

**Closed by Insprill** 2021-07-21 21:15 UTC
Labels: Resolution: Duplicate
