### ISSUE TITLE
[Issue] Dupe Glitch

### ISSUE THREAD

**Issue by Pudiaz** [GC-spigot/AdvancedEnchantments#1733] opened 2021-03-02 22:35 UTC
**Describe the bug**
Dupe glitch for blocks that have 2 blocks hit 

**To Reproduce**
Telepathy puts item back into inventory, when you break a block that has 2 hitboxes, and break the correct one it will dupe that block.

**Screenshots / Video**
https://youtu.be/YhplL7K5WQ8

**Server Information (please complete the following information):**
- version git-paper-"06900aef5" MC:1.16.5 api version 1.16.5-R0.1-snapshot
- AdvancedEnchantments 8.0.0-Pre17.1

**Comment by Insprill** [comment] 2021-03-03 03:56
please update to the latest version of AE and report back as to if it still happens

**Comment by Insprill** [comment] 2021-03-05 04:17
Closing as it's been 2 days, and I'm not able to reproduce this issue on the latest version.

**Closed by Insprill** 2021-03-05 04:17 UTC
Labels: issue
