### ISSUE TITLE
Error when enchanting

### ISSUE THREAD

**Issue by LuluxClient** [GC-spigot/AdvancedEnchantments#2132] opened 2021-07-08 15:56 UTC
## Details

**Describe the bug**

If you enchant an item you get this error : https://pastebin.com/Lt4L9i1S
**To Reproduce**

If you enchant an item you get this error : https://pastebin.com/Lt4L9i1S
**Screenshots / Video**

https://pastebin.com/Lt4L9i1S

## Server Information
ae: 8.4.5
Server : 1.8.8

**Comment by EchocallingEarth** [comment] 2021-07-22 13:44
My Apologies Insprill for not seeing the issue existed and opening 2180. I did not realize it was caused by a player enchanting an item. Additionally I didn't look this far back, I usually search for issues within a few days as 99% of bugs are addressed and fixed within that time frame.  Sadly this seems to be a bug now going on 2 weeks unresolved. :( 

If I can provide any further info to help resolve this including testing etc please let me know here or via a ping on Discord EchocallingEarth#0001

Thanks

**Comment by Insprill** [comment] 2021-08-01 18:32
Fixed in the next update

**Closed by Insprill** 2021-08-01 18:32 UTC
Labels: Bug: Confirmed, Resolution: Accepted
