### ISSUE TITLE
Jobs reborn hook with TP_DROPS

### ISSUE THREAD

**Issue by LuluxClient** [GC-spigot/AdvancedEnchantments#2213] opened 2021-07-30 07:53 UTC
## Details

**Describe the bug**

Latest jobs reborn doesn't work with both Experimental block breaking on & off and the new option called use-experimental-damage (on and off)
**To Reproduce**

Grab an axe with telepathy and join a farmer job that gives you money for breaking crops such as a pumpkin or watermelon. Break it and you won't get paid for it but if you break it by hand it will work

**Screenshots / Video**

Don't need

## Server Information
- "/ae plinfo" link: 
- Server log: 
ae: 8.5.7
Server: 1.8.8 tacospigot

**Comment by Insprill** [comment] 2021-07-31 22:40
Possible fix in the next update. Please respond once it comes out and you are able to test it.

**Comment by LuluxClient** [comment] 2021-08-03 12:39
> Possible fix in the next update. Please respond once it comes out and you are able to test it.

hey it is now working but now the drops are dupe, it tps them in my inv + it drops them on the ground.

**Comment by LuluxClient** [comment] 2021-08-03 12:40
https://gyazo.com/a4b2ba539ef5e772a683a7c5ad4fbfc6 

and if the experimental thing is off the dupe isn't happening but the hook is no longer working.

**Comment by nivcoo** [comment] 2021-08-03 23:26
I can confirm the first issue and use-experimental-block-breaking. So i have to disable this feature and lost the jobs hook

**Comment by LuluxClient** [comment] 2021-08-04 19:58
latest update broke jobs reborn hook again.

**Comment by nivcoo** [comment] 2021-08-04 20:01
Do you have reactivate experimental block ?

**Comment by nivcoo** [comment] 2021-08-05 00:13
I've tried and i can confirm, jobs not works with and without experimental

**Comment by nivcoo** [comment] 2021-08-05 00:13
With auto_smelt/telepathy

**Comment by LuluxClient** [comment] 2021-08-05 22:30
Still bugged on the latest version.

**Comment by Insprill** [comment] 2021-08-06 00:31
Alright, I know what the issue is now. It's gonna take some time to figure out due to technical limitations of legacy versions. On legacy versions, the only way to prevent a block from dropping the default drops is to set it to AIR, however, a lot of plugins, including Jobs, ignore BlockBreakEvents when the block broken is AIR. I have an idea that *might* work to get around this but don't have an ETA for when I can implement it.

**Comment by nivcoo** [comment] 2021-08-16 15:45
Why from one version to another does the support for jobs and other plugins no longer work? You didn't add the express fire-event option to call the event qaudn on breaks with autosmelt / telepathy?

**Comment by nivcoo** [comment] 2021-08-16 15:45
I don't really understand why the fix lasts 1 week to be broken again like before

**Comment by Insprill** [comment] 2021-08-16 16:08
I explained it in my last comment

**Comment by LuluxClient** [comment] 2021-08-22 01:14
Can't wait for the fix :)

**Comment by nivcoo** [comment] 2021-08-22 12:36
You can fix it fast, it breaks all the gameplay!

**Comment by Insprill** [comment] 2021-08-25 03:39
The idea I had before did in fact work! The next update will have the 1.13+ version of experimental-block-breaking backported to legacy versions. Going to leave this open for now until it's confirmed to fix the compatibility.

**Comment by Insprill** [comment] 2021-08-29 14:12
Now that 8.6.8 is out, can y'all confirm that it's fixed?

**Comment by nivcoo** [comment] 2021-08-29 14:13
I have tried and it works but i will wait tomorrow to be sure

**Comment by LuluxClient** [comment] 2021-08-30 07:27
> Now that 8.6.8 is out, can y'all confirm that it's fixed?

Tried it too and it’s working for me !

**Comment by Insprill** [comment] 2021-08-30 07:30
Epic! Marking this as resolved.

**Closed** 2021-08-30 07:30 UTC
Labels: Bug: Confirmed, Resolution: Accepted
