### ISSUE TITLE
Hotbar Item Dupe

### ISSUE THREAD

**Issue by ryankayz7** [GC-spigot/AdvancedEnchantments#2706] opened 2022-03-25 00:26 UTC
### Describe the bug

When using enchantments that increase item durability on block break and you change item slots upon the block break it seems to duplicate the item in the item to the slot you change to as well as the original slot. This occurred with two enchants as listed below.

### How to reproduce

To reproduce the issue you add a speed modifier to your pickaxe such as a very high level of haste or efficiency. The higher the mining speed the easier it is to reproduce I believe due to having more times that you are breaking the block making it easier to get the right timing. On top of this you add the enchant (I suggest unbreakable due to 100% chance) and then you have to time your block break at the same time as you switch your hotbar item. This then causes the duplication. You can see this occur in the video below. (note the user in the video is on bedrock but this does work on java edition too)

### Screenshots / Videos

https://gyazo.com/ae7757f5370ed87ca846b80d4b148814
https://gyazo.com/5c49d863f2f370346cdc915b82d4eb5a

### "/ae plinfo" link

https://paste.md-5.net/hovohuravo

**Comment by ryankayz7** [comment] 2022-03-25 00:28
Forgot to add the enchants so here are the ones it is reproducible with:
unbreakable:
  display: "%group-color%Unbreakable"
  description: 'Prevent your pickaxe from breaking in mines!'
  applies-to: 'Tools'
  group: 'COPPER'
  type: 'MINING'
  applies:
  - 'ALL_PICKAXE'
  levels:
    '1':
      chance: 100
      condition:
      - '%player world% = world_mines : %allow%'
      effects:
        - 'ADD_DURABILITY_CURRENT_ITEM:-1'

AND 
        
trench:
  display: "%group-color%Trench"
  description: "Chance to break in 3x3 area."
  applies-to: "Pickaxes, Shovels"
  type: "MINING"
  group: "GOLD"
  applies:
    - ALL_PICKAXE
    - ALL_SPADE
  levels:
    1:
      chance: 4
      effects:
        - "TRENCH:3"
        - "TP_DROPS" 
        - 'ADD_DURABILITY_CURRENT_ITEM:-15'              
    2:
      chance: 8
      effects:
        - "TRENCH:3"
        - "TP_DROPS"      
        - 'ADD_DURABILITY_CURRENT_ITEM:-15'              
    3:
      chance: 12
      effects:
        - "TRENCH:3"
        - "TP_DROPS"                
        - 'ADD_DURABILITY_CURRENT_ITEM:-15'              
    4:
      chance: 16
      effects:
        - "TRENCH:3"
        - "TP_DROPS"                
        - 'ADD_DURABILITY_CURRENT_ITEM:-15'              
    5:
      chance: 20
      effects:
        - "TRENCH:3"
        - "TP_DROPS"        
        - 'ADD_DURABILITY_CURRENT_ITEM:-15'

**Comment by DuneSciFye** [comment] 2022-03-27 12:15
This happens with the ADD_DURABILITY effects, I can confirm this. I tried doing REMOVE_ENCHANT and ADD_DURABILITY, but it removed the enchant, and the second it added the durability it re-added the enchant. If I moved my main hand to another hot bar slot, it would duplicate the item. The only way I found this to work was to add a WAIT effect between the ADD_DURABILITY and REMOVE_ENCHANT, but between that time you could change hotbar slots and keep the enchant

**Comment by Burchard36** [comment] 2022-03-31 11:57
Hello there! I will look into this issue right now and hopefully have a fix for you

I'm unable to produce this myself but I wont deny any video evidence, plus I can see a few lines of code where this can possibly cause this bug

**Comment by ryankayz7** [comment] 2022-03-31 12:37
Thank you! If it helps with testing I know someone who can reliably reproduce this. They are on bedrock as in the video above though

**Comment by Burchard36** [comment] 2022-03-31 12:51
Hello there, I was able to reproduce the issue perfectly fine in Java edition, I didn't notice you meant your own unbreakable enchantment instead of the default built in one.

This bug has been fixed locally on my and and should be fixed when 8.9.10 gets released (Hopefully, should be released in a few hours, just waiting for GC to be able to update this to spigot)

I normally send videos with my fixes, wont do it on here since well its just gonna be a video of me switching my item selection over and over for 20 minutes, haha

**Comment by Burchard36** [comment] 2022-03-31 22:23
Hello 8.9.10 is released, please update your AE and this dupe bug is fixed

Have a nice day!

**Closed by Burchard36** 2022-03-31 22:23 UTC
Labels: Priority: Critical, Bug: Confirmed, Resolution: Accepted
