### ISSUE TITLE
Guardian Effect

### ISSUE THREAD

**Issue by Jok3rTV** [GC-spigot/AdvancedEnchantments#374] opened 2019-03-11 20:18 UTC
Please add some more mob types for the GUARDIAN effect like baby zombie or baby zombie ride on a chicken on even custom mobs that we can create like skeleton with pumpking on his head If you don't want to add the custom mobs then just add the normal Minecraft mobs like the baby zombie. And if you adding Custom mobs so to add ability to set on zombie armor + skull on his head to make it like a zombie with full iron set on and a guardian skull to make it look like a guardian

**Comment by GC-spigot** [comment] 2019-03-20 19:16
Duplicate of your new ticket.

**Closed by GC-spigot** 2019-03-20 19:16 UTC
