### ISSUE TITLE
Jobs reborn hook not working (well it's bugged

### ISSUE THREAD

**Issue by LuluxClient** [GC-spigot/AdvancedEnchantments#2063] opened 2021-06-18 13:12 UTC
## Details

**Describe the bug**

Sometimes custom enchants such as telepathy isn't giving jobs exp money etc if you mine crops. and yes I tried with both experimental block breaking on true and false
**To Reproduce**

It's random and I need to /ae reload to fix it each time
**Screenshots / Video**

don't need it just doesn't work

## Server Information
- "/ae plinfo" link: 
- Server log: 
ae: 8.2.8
Server ver : 1.8.8 tacospigot

**Comment by Insprill** [comment] 2021-06-18 19:14
Duplicate of #1361

**Closed by Insprill** 2021-06-18 19:14 UTC
Labels: Resolution: Duplicate
