### ISSUE TITLE
crash server 

### ISSUE THREAD

**Issue by hkkongou** [GC-spigot/AdvancedEnchantments#2266] opened 2021-08-13 03:32 UTC
## Details

**Describe the bug**
update from version 8.5.7 to 8.6.4 crashed all 3 of my servers , with same error log

**To Reproduce** 
replace jar from 8.5.7 to 8.6.4
wait for players to use AE

**Screenshots / Video**

log
https://paste.gg/p/anonymous/ff74dbd465114a5d97bdaaee20ff04c4

![image](https://user-images.githubusercontent.com/61608872/129300775-c64a0789-02c5-4919-a6ff-13139ae04d98.png)
the only thing in the server i updated is AE, thats it, so i am sure is AE problem and i switched back to 8.5.7 and is stable now.

## Server Information
- "/ae plinfo" link: https://paste.md-5.net/arukuyodoc
- Server log: https://mclo.gs/dtzOQCx

**Comment by Insprill** [comment] 2021-08-13 04:22
Duplicate of #2254

**Closed by Insprill** 2021-08-13 04:22 UTC
Labels: Resolution: Duplicate
