### ISSUE TITLE
Duplication Bug

### ISSUE THREAD

**Issue by Etanarvazac** [GC-spigot/AdvancedEnchantments#4102] opened 2024-03-20 23:52 UTC
### Describe the bug

Testing with my server's owner, MasonX3 on the XCraft Survival Server, we are still finding a duplication bug active. At first, we thought it was due to the Magnet, Vitrify, and Auto-Smelt enchantments. Then with mcMMO. However, after much troubleshooting, we think we've found the root cause of this issue. It is indeed with the AutoSmelt, Magnet, and Vitrify enchantments paired with mcMMO's Double Drops (which is activated at Mining level 100 and above). We have tested if this is due to mcMMO and have found this bug to exist without mcMMO. After disabling these few enchantments, the bug was gone. I have made a clip of this issue and linked it below. I have also provided a list of each custom enchantment on my pickaxe does in a section below.

I will note that the mod you see in the clip (Xaero's Minimap) and OptiFine (OptiFabric) are the only two mods installed. I am a moderator on XCraft Survival and our anti-cheat would be going mad if my client had client-side mods that broke the server's rules. If you want a clip from the vanilla MC client, I will do so. I will also note that this is different from issue #4097 as I have tested this with a l pickaxe with only the Fortune, Unbreaking, Mending, Efficiency V, **Experience**, **Quickening**, and **Resilience V** enchantments (bold are AE enchants) and this duplication did **not** happen.

This bug is similar to issue #4070. This issue greatly describes this issue and how to reproduce it effectively.

### Custom Enchantments broken down:
- **Experience:** Gives XP upon breaking blocks
- **Resilience:** Increases the durability of tools
- **Quickening:** Gives player the Speed potion effect
- **Haste:** Gives player the Haste beacon effect
- **Magnet:** Puts broken block directly in player's inventory, kills dropped item from breaking
- **Auto-Smelt:** Automatically smelts blocks and ores (e.g.: Cobblestone smelts to Stone when mined)
- **Vein Miner:** Mines out the entire vein of an ore.
NOTE: Items marked **(disabled)** in the above list were already disabled when the video was made.

### Affected enchantments:
- Auto-Smelt
- Magnet
- Vitrify

### How to reproduce

**Method 1:**
1. Place shulkers down in your server. Putting items in the shulkers is **optional** as it **does not** have an effect on this bug.
2. Create a pickaxe matching the one provided in the screenshot below (name not required)
3. Ensure you have at least 100 levels in mcMMO's Mining skill for at least 10% double drop rate.
4. Restart your server
5. Using the pickaxe made in step 2, break the shulker boxes. You should see 2 shulker boxes appear.

**Method 2:**
1. Place a dispenser and fill with shulkers. Putting items in shulkers is **optional** as it **does not** have an effect on this bug.
2. Create a pickaxe matching the one provided in the screenshot below (name not required).
3. Ensure you have at least 100 levels in mcMMO's Mining skill for at least 10% double drop rate.
4. Have the dispenser place the shulker. You can either use a button, or a timer (timer would be easier).
5. Using the pickaxe made in step 2, break the shulker boxes. You should see 2 shulker boxes appear.

### Screenshots / Videos

The affected tool:
![image](https://github.com/GC-spigot/AdvancedEnchantments/assets/55290878/05025652-c481-4c2f-923f-dc3d24ccc2ee)

Video (Unlisted to public, anyone with link can view):
https://youtu.be/roPvzlBh8z8

### "/ae plinfo" link

https://paste.md-5.net/iruwaxuyac

### Edits:
1. Multiple changes (3/24/24):
  a. Added reproduction "Method 2" which was recently discovered by our team.
  b. Listed all enchantments that are effected by this bug
  c. Fixed various GitHub formatting issues
  d. Included notation of mcMMO
  e. Rewritten the description of this bug to further note all troubleshooting recently done.
  f. Included notation to another issue in which relates to this one.

**Comment by MasonX3** [comment] 2024-03-20 23:58
I'll add to this with the `enchantments.yml` file. 

https://paste.md-5.net/pakuhisihe.shell

**Comment by MasonX3** [comment] 2024-03-22 02:09
Can confirm this bug is still present on the latest version.

**Comment by Etanarvazac** [comment] 2024-03-24 18:46
Mason removed Vulcan & GriefDefender. This bug still prevailed.

**Comment by Etanarvazac** [comment] 2024-03-24 19:41
After some additional troubleshooting, we found that Magnet, AutoSmelt, and Vitrify with mcMMO's Double Drops create this issue.

**Comment by ThomasWega** [comment] 2024-03-24 21:28
Most probably a duplicate of https://github.com/GC-spigot/AdvancedEnchantments/issues/4070. Should be fixed in the next update

**Closed by ThomasWega** 2024-03-24 21:28 UTC
Labels: Bug: Unconfirmed
