### ISSUE TITLE
Bug with more than 20 health

### ISSUE THREAD

**Issue by ElMoha943** [GC-spigot/AdvancedEnchantments#2199] opened 2021-07-25 19:33 UTC
## Details

**Describe the bug**

An error appears in console if a player has more than 20 health.

**To Reproduce**

Have a player with more than 20health, this could be achieved with custom equipment or other plugins.

**Screenshots / Video**

![image](https://user-images.githubusercontent.com/25410859/126911095-1b406645-b5ec-4ea4-aeac-00e0d59eccc7.png)

## Server Information
- "/ae plinfo" link:  https://paste.md-5.net/givemalage
- Server log:  
[latest.log](https://github.com/GC-spigot/AdvancedEnchantments/files/6874448/latest.log)

**Comment by Insprill** [comment] 2021-07-25 19:34
duplicate of #2190

**Comment by ElMoha943** [comment] 2021-07-25 19:34
fix tho?

**Closed by Insprill** 2021-07-25 19:34 UTC
Labels: Resolution: Duplicate
