### ISSUE TITLE
Issue with auto smelt enchant

### ISSUE THREAD

**Issue by JHarris12345** [GC-spigot/AdvancedEnchantments#2043] opened 2021-06-06 16:47 UTC
## Details

**Describe the bug**

If you mine lapis ores with the auto smelt enchant, it drops lapis blocks instead of lapis.
**To Reproduce**

Mine lapis ore with auto smelt enchant.
**Screenshots / Video**

Not need, very simple

## Server Information
- "/ae plinfo" link: 
- https://paste.md-5.net/zekovajasu
- Server log: 
Log contains peoples IPs so wont be uploading this. If you definitely need it, tag me and Ill send over discord. I dont think its needed for this issue

**Comment by Insprill** [comment] 2021-06-07 00:47
Duplicate of #2040

**Closed by Insprill** 2021-06-07 00:47 UTC
Labels: Bug: Confirmed, Resolution: Duplicate
