### ISSUE TITLE
Vanilla enchant exclusion does not work

### ISSUE THREAD

**Issue by t-34-2** [GC-spigot/AdvancedEnchantments#1843] opened 2021-04-06 17:53 UTC
## Details

**Describe the bug**
Adding vanilla enchants to the not-applyable-with portion of an enchant config does not stop items from receiving both the CE and excluded vanilla enchant.

I was told to post it as a bug for the time being.

**To Reproduce**
Enchant a bow with, say Flame, and in the CE enchantments.yml for a bow CE, add ARROW_FIRE as an excluded (not-applyable-with) vanilla enchant. Then get a book of the mentioned bow CE, and drag it onto the bow with Flame . It should have blocked the CE from being applied on there. 
Dev gave this instruction: 
> Try using these names https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/enchantments/Enchantment.html

**Screenshots / Video**

## Server Information
- "/ae plinfo" link:  https://paste.md-5.net/tixuzaxezi 
- Server log:  https://gist.github.com/t-34-2/9e7fb64c5b978172e6437f30a158536c

**Comment by Insprill** [comment] 2021-06-03 04:18
Is this still an issue on the latest version? I couldn't reproduce it

**Comment by rmalca** [comment] 2021-09-10 23:11
Same problem here.

"/ae plinfo" link: https://paste.md-5.net/gefiheconi

Enchantment:
```
smelting:
  display: '%group-color%Fundición'
  type: 'MINING'
  settings:
    not-applyable-with:
      - mending
      - silk_touch
  levels:
    1:
      effects:
        - 'SMELT'
```

**Screenshots / Video**
Result in enchanting table:
![image](https://user-images.githubusercontent.com/3759745/132926572-6c7be78e-9da8-4bbf-a46a-3d7da7e68adc.png)

**Comment by Insprill** [comment] 2021-09-28 06:38
Fixed in the next update

**Closed by Insprill** 2021-09-28 06:38 UTC
Labels: Bug: Confirmed, Resolution: Accepted
