### ISSUE TITLE
Right click enchantment info crash

### ISSUE THREAD

**Issue by juancruzdal** [GC-spigot/AdvancedEnchantments#2260] opened 2021-08-12 12:51 UTC
## Details

**Describe the bug**
Server crash when you display too many times the info of enchantments in /e menu

**To Reproduce**
Right click a enchant group in /e menu too many times (right click -> back -> right click -> back)

## Server Information
- https://paste.md-5.net/itamawizeh
- https://mcpaste.io/d81e62ddfa2b48f3

**Comment by Insprill** [comment] 2021-08-12 15:05
Duplicate of #2254

**Closed** 2021-08-12 15:05 UTC
Labels: Resolution: Duplicate
