### ISSUE TITLE
A couple of bugs that need to be fixed.

### ISSUE THREAD

**Issue by DimaSergeew** [GC-spigot/AdvancedEnchantments#3064] opened 2022-10-14 13:04 UTC
### Describe the bug

1. mistake is simple, you can wear leather instead of armor -_-

2. This mistake is more serious. The "flying" enchantment is constantly bugged by players. They take off their shoes in 1 world and put them on in another, as a result they get an endless flight without shoes (

### How to reproduce

1) Wear boots with the "flying" enchantment.
2) Fly.
3) Teleport to another world, take off your shoes.
4) Teleport anywhere again.
5) congratulations you can fly without shoes

### Screenshots / Videos

https://user-images.githubusercontent.com/75163645/195853868-7787ec91-b5d2-4cfe-815d-69ab0e539116.mp4

### "/ae plinfo" link

https://paste.md-5.net/ceyuvoneri

### Server Log

-

**Comment by reussy** [comment] 2022-10-14 14:56
Hello @DimaSergeew 

Remove "LEATHER" from "armor-items" in config.yml and it should be fixed!

**Comment by reussy** [comment] 2022-10-27 13:12
I can't reproduce it the second issue, you could try this in the latest version. I'm sure this is being caused by another plugin.

**Comment by reussy** [comment] 2022-10-29 04:33
The second one is duplicated (#3053). We'll keep it in this report, the other one will be closed...

**Comment by DimaSergeew** [comment] 2022-10-29 06:14
> The second one is duplicated (#3053). We'll keep it in this report, the other one will be closed... @DimaSergeew

I poured the plugin on a clean build and could reproduce the bug

**Comment by DimaSergeew** [comment] 2022-10-30 07:55
l

**Comment by reussy** [comment] 2022-10-30 16:20
> > The second one is duplicated (#3053). We'll keep it in this report, the other one will be closed... @DimaSergeew
> 
> I poured the plugin on a clean build and could reproduce the bug

Hi, have you tested this only with AdvancedEnchantments installed on your server?

**Comment by reussy** [comment] 2022-11-08 02:17
@DimaSergeew

**Closed** 2022-11-08 09:27 UTC
Labels: Bug: Unconfirmed
