### ISSUE TITLE
Health Bug

### ISSUE THREAD

**Issue by xXDarkCvBxX** [GC-spigot/AdvancedEnchantments#2239] opened 2021-08-05 18:41 UTC
I have this message in console:

[20:11:53] [Server thread/WARN]: [AdvancedEnchantments] Task #1077834 for AdvancedEnchantments v8.5.7 generated an exception
java.lang.IllegalArgumentException: Health must be between 0 and 22.0, but was 24.0. (attribute base value: 20.0, player: Andaros)
	at org.bukkit.craftbukkit.v1_16_R3.entity.CraftLivingEntity.setHealth(CraftLivingEntity.java:127) ~[patched_1.16.5.jar:git-Paper-783]
	at net.advancedplugins.ae.enchanthandler.enchanttypes.EFFECT_STATIC.lambda$null$0(EFFECT_STATIC.java:47) ~[?:?]
	at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:100) ~[patched_1.16.5.jar:git-Paper-783]
	at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:468) ~[patched_1.16.5.jar:git-Paper-783]
	at net.minecraft.server.v1_16_R3.MinecraftServer.b(MinecraftServer.java:1427) ~[patched_1.16.5.jar:git-Paper-783]
	at net.minecraft.server.v1_16_R3.DedicatedServer.b(DedicatedServer.java:436) ~[patched_1.16.5.jar:git-Paper-783]
	at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1342) ~[patched_1.16.5.jar:git-Paper-783]
	at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1130) ~[patched_1.16.5.jar:git-Paper-783]
	at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:291) ~[patched_1.16.5.jar:git-Paper-783]
	at java.lang.Thread.run(Thread.java:834) [?:?]

It does not seem to generate any conflict, but it can be harmful and I do not know if it can do something for this I report it

**Comment by Insprill** [comment] 2021-08-05 19:13
Duplicate of #2190

**Closed by Insprill** 2021-08-05 19:13 UTC
Labels: Resolution: Duplicate
