### ISSUE TITLE
EFFECT_STATIC health error

### ISSUE THREAD

**Issue by EchocallingEarth** [GC-spigot/AdvancedEnchantments#2190] opened 2021-07-24 01:09 UTC
## Details

**Describe the bug**
[17:09:03 WARN]: [AdvancedEnchantments] Task #6549 for AdvancedEnchantments v8.5.4 generated an exception
java.lang.IllegalArgumentException: Health must be between 0 and 20.0, but was 21.0. (attribute base value: 20.0, player: EchocallingEarth)
        at org.bukkit.craftbukkit.v1_17_R1.entity.CraftLivingEntity.setHealth(CraftLivingEntity.java:110) ~[patched_1.17.1.jar:git-Purpur-1287]
        at net.advancedplugins.ae.enchanthandler.enchanttypes.EFFECT_STATIC.lambda$null$0(EFFECT_STATIC.java:47) ~[?:?]
        at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[patched_1.17.1.jar:git-Purpur-1287]
        at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483) ~[patched_1.17.1.jar:git-Purpur-1287]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1565) ~[patched_1.17.1.jar:git-Purpur-1287]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:492) ~[patched_1.17.1.jar:git-Purpur-1287]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1480) ~[patched_1.17.1.jar:git-Purpur-1287]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1270) ~[patched_1.17.1.jar:git-Purpur-1287]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319) ~[patched_1.17.1.jar:git-Purpur-1287]
        at java.lang.Thread.run(Thread.java:831) [?:?]

**To Reproduce**
OP/Owner creative mode
Used /warp to travel between worlds and the above warning spams the console. When reported last time Insprill stated it was a enchanted related error and closed the issue merging with another issue. Which at the time seemed correct, however this time I was able to precisely replicate the warning. And can confirm that it is not related to enchanting. 

Further tested using /mvtp to same world.
World is a nonplayer world for admins only using a flat seed.

NOTE the main worlds and connected player world are not effected by this bug. Which may require further testing of however I am unsure what testing would be best to do for this. I have tested with a clean inventory and a loaded inventory - both results are the same. No enchantments or special items etc are used during these test. only commands as stated above.
Additional testing was also done in survival and spectator.

**Screenshots / Video**
Nothing was shown in game

## Server Information
https://paste.md-5.net/ejotudepij
https://pastebin.com/9kUh1yiN

Additional information which may be of help: 
Download of AE came from the official site not from Spigot
Additional info if needed video upon request.
If it is needed to log on to the server and test further please request the IP and OP'ing if needed. (OP'ing only applies to those approved to fix the bug or research it by Insprill or GC)

**Comment by Insprill** [comment] 2021-07-27 21:49
Thank you for the well-written report. Can you try and remove Multiverse to see if that fixes it? With just AE, EssentialsX, LuckPerms, PAPI, ProtocolLib, and Vault I couldn't get the error when warping between worlds wearing all Overload 3 armor.

**Comment by ElMoha943** [comment] 2021-07-28 01:01
> Thank you for the well-written report. Can you try and remove Multiverse to see if that fixes it? With just AE, EssentialsX, LuckPerms, PAPI, ProtocolLib, and Vault I couldn't get the error when warping between worlds wearing all Overload 3 armor.

Hi, im having same error with any enchanted item involving people with more health, as said in the ticket you closed because it was duplicated: it happens if the player has more than 20 health (this can be achieved with external plugins or custom armor/item values of maxhealth). I believe It has nothing to do with Overload 3 armor.

**Comment by EchocallingEarth** [comment] 2021-07-28 06:01
> Thank you for the well-written report. Can you try and remove Multiverse to see if that fixes it? With just AE, EssentialsX, LuckPerms, PAPI, ProtocolLib, and Vault I couldn't get the error when warping between worlds wearing all Overload 3 armor.

As this is on a production server at this time, No I am unable to remove MV. Also, we use CMI verse EssentialsX. And I understand this makes replicating harder if at all possible. 

However, with this in mind, I will see if there is another way to further test. And update over the next few days (as I am off from duty for my 3-day rotation). During this time I will test using the following multi-world plugins in addition to MV. Myworlds (if updated) as well as Hyperverse (if Updated). I will also investigate options for reduced health when warping/using built-in world commands (similar to mvtp) and other methods. I will during testing log all details and provide the same here. Hopefully, with this information, a resolution can be found.

**Comment by EchocallingEarth** [comment] 2021-08-02 13:55
I have run several tests and the results are showing the same. However, I have not been able to finish my testing as of yet. As I am still working on Hyperverse testing. I just wanted to ensure you that I have been attempting to resolve this issue and have not allowed it to fall to the weigh side. 

The issue only appears to be with this single world, which has lead me to consider checking preworldinventory and a few other across-world plugins. I will be doing heavy testing on this aspect as well today and tomorrow.  beginning today with a clean install of AE including folder contents to see if I can resolve the issue that way as well. It is frustrating I know and that is part of why I am pushing hard to resolve it.

_Important note I will also post fresh install check the issue related to Enchanter which spams the console to see if I can provide further input on that matter as well._

**Comment by EchocallingEarth** [comment] 2021-08-02 17:15
Well, the most recent update broke the plugin apparently so now testing is on hold till a fix is made.

[07:45:11] [Craft Scheduler Thread - 728 - AdvancedEnchantments/WARN]: java.net.ConnectException: Connection timed out
[07:45:11] [Craft Scheduler Thread - 728 - AdvancedEnchantments/WARN]: 	at java.base/sun.nio.ch.Net.connect0(Native Method)
[07:45:11] [Craft Scheduler Thread - 728 - AdvancedEnchantments/WARN]: 	at java.base/sun.nio.ch.Net.connect(Net.java:576)
[07:45:11] [Craft Scheduler Thread - 728 - AdvancedEnchantments/WARN]: 	at java.base/sun.nio.ch.Net.connect(Net.java:565)
[07:45:11] [Craft Scheduler Thread - 728 - AdvancedEnchantments/WARN]: 	at java.base/sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:588)
[07:45:11] [Craft Scheduler Thread - 728 - AdvancedEnchantments/WARN]: 	at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:333)
[07:45:11] [Craft Scheduler Thread - 728 - AdvancedEnchantments/WARN]: 	at java.base/java.net.Socket.connect(Socket.java:645)
[07:45:11] [Craft Scheduler Thread - 728 - AdvancedEnchantments/WARN]: 	at java.base/sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:290)
[07:45:11] [Craft Scheduler Thread - 728 - AdvancedEnchantments/WARN]: 	at java.base/sun.security.ssl.BaseSSLSocketImpl.connect(BaseSSLSocketImpl.java:174)
[07:45:11] [Craft Scheduler Thread - 728 - AdvancedEnchantments/WARN]: 	at java.base/sun.net.NetworkClient.doConnect(NetworkClient.java:182)
[07:45:11] [Craft Scheduler Thread - 728 - AdvancedEnchantments/WARN]: 	at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:497)
[07:45:11] [Craft Scheduler Thread - 728 - AdvancedEnchantments/WARN]: 	at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:600)
[07:45:11] [Craft Scheduler Thread - 728 - AdvancedEnchantments/WARN]: 	at java.base/sun.net.www.protocol.https.HttpsClient.<init>(HttpsClient.java:265)
[07:45:11] [Craft Scheduler Thread - 728 - AdvancedEnchantments/WARN]: 	at java.base/sun.net.www.protocol.https.HttpsClient.New(HttpsClient.java:379)
[07:45:11] [Craft Scheduler Thread - 728 - AdvancedEnchantments/WARN]: 	at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(AbstractDelegateHttpsURLConnection.java:189)
[07:45:11] [Craft Scheduler Thread - 728 - AdvancedEnchantments/WARN]: 	at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1232)
[07:45:11] [Craft Scheduler Thread - 728 - AdvancedEnchantments/WARN]: 	at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1120)
[07:45:11] [Craft Scheduler Thread - 728 - AdvancedEnchantments/WARN]: 	at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:175)
[07:45:11] [Craft Scheduler Thread - 728 - AdvancedEnchantments/WARN]: 	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1653)
[07:45:11] [Craft Scheduler Thread - 728 - AdvancedEnchantments/WARN]: 	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1577)
[07:45:11] [Craft Scheduler Thread - 728 - AdvancedEnchantments/WARN]: 	at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:224)
[07:45:11] [Craft Scheduler Thread - 728 - AdvancedEnchantments/WARN]: 	at net.advancedplugins.ae.Core$2.run(Core.java:566)
[07:45:11] [Craft Scheduler Thread - 728 - AdvancedEnchantments/WARN]: 	at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftTask.run(CraftTask.java:101)
[07:45:11] [Craft Scheduler Thread - 728 - AdvancedEnchantments/WARN]: 	at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57)
[07:45:11] [Craft Scheduler Thread - 728 - AdvancedEnchantments/WARN]: 	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[07:45:11] [Craft Scheduler Thread - 728 - AdvancedEnchantments/WARN]: 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
[07:45:11] [Craft Scheduler Thread - 728 - AdvancedEnchantments/WARN]: 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
[07:45:11] [Craft Scheduler Thread - 728 - AdvancedEnchantments/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:831)
[07:45:11] [Craft Scheduler Thread - 728 - AdvancedEnchantments/INFO]: [AdvancedEnchantments] Disabling AdvancedEnchantments v8.5.9

All other plugins etc are running fine.
Full log:
https://pastebin.com/4JWiR5fB

Plugins:
AdvancedChests, AdvancedClaimGuardian, AntiCurse, ArmoredElytra, AureliumSkills, Bank, BigDoors, BlockParticles, ChestSort, Chunky, Citizens, CleanroomGenerator, CMI, CMIEInjector*, CMILib, ConsoleSpamFix, Core, CoreProtect, CustomCrafting, CustomEnderChest, CustomShop, Denizen, DisplayShops, dtlTradersPlus, EpicBackpacks, EpicFarming, EpicFurnaces, EpicHoppers, ExoticGarden, ExtraGear, ExtraTools, FastAsyncWorldEdit (WorldEdit), HeadDatabase, HolographicDisplays, HorseOverhaul, ImageOnMap, InfoBook, Item-Chest-Sorter, ItemsAdder, Jobs, LibsDisguises, LightAPI, LimitPillagers, LoneLibs, Lootin, LuckPerms, LWC, Multiverse-Core, NBTAPI, NetheriteShield, NoPlugins, PerWorldInventory, PlaceholderAPI, ProtocolLib, PublicCrafters, Sentinel, Slimefun, spark, SuperLuckyBlock, SurvivalInvisiframes, Terra, UltimateCatcher, UltimateFishing, UltimateRepairing, UltimateStacker, UltimateTimber, VanillaTweaks, Vault, WolfyUtilities

Disabled Plugin sees Log and error in this message.
AdvancedEnchantments(disabled)

Will open a new issue if needed - pending response here.

Further info upon request.

**Comment by EchocallingEarth** [comment] 2021-08-03 14:15
I opened a new issue for the above as till it is fixed I can not do any further testing. Once the issue is fixed and actually fixed properly I will continue to work on testing and do all I can to help.

**Comment by EchocallingEarth** [comment] 2021-08-07 17:26
Thorough testing is complete. Logs will be provided upon request. However, my findings are the same for Hyperverse,  as well as MyWorlds.  I will run a final test today of PreWorldInventories on all cross-world platforms and update accordingly. 

Additional testing may still be required, however, it is my belief that this is clearly an issue created by AdvancedEnchants as it started after one of the updates. And since we run the latest updates for me to resolve the cause would take much longer than would be reasonable. Basically requiring me to download and test each previous release(update) until I find what update caused the issue initially. This may be why the issue is unfixed - it was not recognized at first and failed to be picked up and fixed at that time. Now it is like many Mojang issues are buried in the code.

Still, I'll provide one final test and update later today.

**Comment by Insprill** [comment] 2021-08-08 05:29
I know when the error started. It was when EFFECT_STATIC started updating other armor pieces when changed. Its just figuring out *why* its happening which is hard. When we set the health we clamp it at their max health which shouldn't let it go over but somehow it is. I haven't been able to start looking into it because I can't reproduce it so any info on how to reproduce it would be greatly appreciated. Thank you for really looking into this, helps alot.

**Comment by EchocallingEarth** [comment] 2021-08-12 12:03
I have discovered this bug also occurs when placing a head on player when not in one of the 3 main or primary worlds used by Mojang. The bug remains no matter what multi-world plugin is used. Any additional testing you wish for me to do I am willing to do.

**Comment by Insprill** [comment] 2021-08-24 04:13
Finally managed to reproduce it! Using this helmet 
```
/minecraft:give @p netherite_helmet{AttributeModifiers:[{AttributeName:"generic.max_health",Name:"generic.max_health",Amount:10,Operation:0,UUID:[I;-1655194134,-846771602,-1103918793,1338046781]}]} 1
```
and swapping it with another helmet that doesn't give the health boost creates the error. Looking into a fix now.

**Comment by Insprill** [comment] 2021-08-24 04:26
Fixed in the next update!

**Closed by Insprill** 2021-08-24 04:26 UTC
Labels: Priority: Critical, Bug: Confirmed, Resolution: Accepted
