### ISSUE TITLE
[Issue] Telepathy flower dupe

### ISSUE THREAD

**Issue by naikyy** [GC-spigot/AdvancedEnchantments#1796] opened 2021-03-18 22:35 UTC
Hello, you can dupe flowers by Telepathy, you can see all on this video.

**Video**
https://www.youtube.com/watch?v=0vClb-ig7wQ

**Server Information:**
- Server Version: newest build Purpur
- Plugin Version: 8.0.0-Pre21.3.jar

**Comment by Insprill** [comment] 2021-03-21 00:24
I was not able to reproduce this issue on Paper-562 1.16.5. Can you test the latest version and see if it only happens on Purpur?

**Comment by Insprill** [comment] 2021-03-27 21:47
Will be closing in a few days if we don't get a response

**Comment by Insprill** [comment] 2021-03-30 00:46
Fixed for pre21.8.

**Closed by Insprill** 2021-03-30 00:46 UTC
Labels: Bug: Confirmed
