### ISSUE TITLE
bug with the blocktrack lore

### ISSUE THREAD

**Issue by NightLife-SG** [GC-spigot/AdvancedEnchantments#2127] opened 2021-07-07 18:08 UTC
## Details

**Describe the bug**
 Blocktarck Bug,when blocktrack added to a pickaxe every block it mine it add the lore to the pickaxe with new line 

**To Reproduce**
add blocktrack to pickaxe,and mine block
![image_2021-07-08_020502](https://user-images.githubusercontent.com/84533050/124807933-e8443180-df90-11eb-8e51-3fd8978c079f.png)

**Screenshots / Video**
If possible, add screenshots or videos to help explain/ show your problem. These are greatly appreciated. 

## Server Information
- "/ae plinfo" link: <https://paste.md-5.net/aceziceqab -->
- Server log:

**Comment by Insprill** [comment] 2021-07-08 02:08
Duplicate of #2064

**Closed by Insprill** 2021-07-08 02:08 UTC
Labels: Resolution: Duplicate
