### ISSUE TITLE
[Issue] Health Boost Problem (Overload)

### ISSUE THREAD

**Issue by Starkenz** [GC-spigot/AdvancedEnchantments#2111] opened 2021-07-02 10:49 UTC
## Details

**Describe the bug**
When i wore overload enchantment it just inverts my health instead of adding health. 

**To Reproduce**
Just wore overload or godly overload armor.

**Screenshots / Video**
https://youtu.be/G1lEo5RHVAg

## Server Information
- Server Version: [PaperSpigot 1.12.2]
- Plugin Version: 8.3.9. It also works on 8.4.0

**Comment by Starkenz** [comment] 2021-07-02 13:10
The issue related to #2102 #2054

**Comment by Insprill** [comment] 2021-07-02 13:37
Duplicate of #2102

**Closed by Insprill** 2021-07-02 13:37 UTC
Labels: Resolution: Duplicate

**Comment by Starkenz** [comment] 2021-07-02 13:44
Hello, why is this issue closed? Is it completely server problem?

**Comment by Insprill** [comment] 2021-07-02 13:54
It was closed since it's a duplicate of another issue. We only allow one issue per bug/ feature request to keep organized and find things easier
