### ISSUE TITLE
Items with custom textures break very quickly.

### ISSUE THREAD

**Issue by andersonrocklive** [GC-spigot/AdvancedEnchantments#4234] opened 2024-05-01 01:36 UTC
### Describe the bug

tools, armor and weapons with textures break very quickly, it does not take into account the durability of the item

### How to reproduce

I have the items adders plugin if I take an armor or weapon tool and apply the enchantments to it this item breaks very quickly which does not happen in vanilla items

### Screenshots / Videos

![bug](https://github.com/GC-spigot/AdvancedEnchantments/assets/24902474/fa893a56-531c-49f7-8af7-cc13e4fe36f9)

### "/ae plinfo" link

https://paste.md-5.net/ezibewuzez

**Comment by SliderKP** [comment] 2024-05-01 19:45
same bug, you test it in latest version ?

**Comment by ThomasWega** [comment] 2024-05-02 10:26
dupe of https://github.com/GC-spigot/AdvancedEnchantments/issues/4228

**Closed by ThomasWega** 2024-05-02 10:26 UTC
Labels: Bug: Unconfirmed
