### ISSUE TITLE
Slotincreaser items not only have the original function, but also right-click to have the function of renametag items...

### ISSUE THREAD

**Issue by NEIKI19914** [GC-spigot/AdvancedEnchantments#3963] opened 2024-01-24 08:17 UTC
### Describe the bug

When I hold a slotincreaser item of any quality, right clicking on it gives me the ability to renametag it, and it also has its own feature for dragging and dropping items...

### How to reproduce

That's it after using the command to get the item... I don't know if it's the issue caused by 1.20.4..

### "/ae plinfo" link

https://paste.md-5.net/yateyumupa

**Comment by ThomasWega** [comment] 2024-01-24 08:18
Possible duplicate of https://github.com/GC-spigot/AdvancedEnchantments/issues/3947

**Closed by ThomasWega** 2024-01-24 08:18 UTC
Labels: Bug: Unconfirmed
