### ISSUE TITLE
I found a way to dupe anything in the plugin

### ISSUE THREAD

**Issue by DimaSergeew** [GC-spigot/AdvancedEnchantments#3310] opened 2023-04-28 10:25 UTC
### Describe the bug

I have found a way to duplicate any items using the crafting table and enchantment table with the help of this plugin.

### How to reproduce

Take any items and open an enchanting table or a crafting table.
Put any item in the crafting slot of the crafting table or in the enchantment slot of the enchanting table.
Keep the items you want to duplicate in your inventory.
Make sure to obtain something from the crafting table, for example, by putting items in the crafting slots.
Keep the items you want to duplicate in your inventory while someone kills you.
After respawning, all the items you had in your inventory before should have duplicated except for the item that was in the crafting slot of the crafting table.

### Screenshots / Videos

(https://drive.google.com/file/d/1iGwHQuYFKsP69iD_AjBWE3kWAXb0o0yO/view?usp=sharing)
+ https://youtu.be/46LwAb6GhWI

### "/ae plinfo" link

(https://paste.md-5.net/otogabibom)

### Server Log

-

**Comment by reussy** [comment] 2023-04-29 02:04
Hey,

You have tried to replicate this without AdvancedEnchantments installed, maybe it has nothing to do with the...

**Comment by DimaSergeew** [comment] 2023-04-29 09:36
> Hey,
> 
> You have tried to replicate this without AdvancedEnchantments installed, maybe it has nothing to do with the...

Are you kidding me? I even checked with only 1 of this plugin and dupe works

**Comment by CrystallizedAtrophy** [comment] 2023-04-29 22:14
I tried this on the server I staff on and it didn't do it. Version 9.0.8.

**Comment by DimaSergeew** [comment] 2023-05-01 03:52
> I tried this on the server I staff on and it didn't do it. Version 9.0.8.

Now I will redo the video with only this plugin

**Comment by DimaSergeew** [comment] 2023-05-01 04:50
> I tried this on the server I staff on and it didn't do it. Version 9.0.8.

https://youtu.be/46LwAb6GhWI

**Comment by Agaloth** [comment] 2023-05-04 15:25
I can confirm that this works.

**Comment by DimaSergeew** [comment] 2023-05-04 17:47
> Эй,
> 
> Вы пытались воспроизвести это без установленных AdvancedEnchantments, возможно, это не имеет никакого отношения к...

yes

**Comment by Truongvv10** [comment] 2023-05-04 23:36
I can also confirm, it worked. Duped my armor, followed the same exact video

**Comment by CrystallizedAtrophy** [comment] 2023-05-04 23:48
Found out why it didn't work for me. Keep inventory is on. Works in world/dimensions with keep inventory turned OFF. Please fix asap.

**Comment by AlFr3on111** [comment] 2023-05-05 06:46
ye the dupe is working in last update i hope they fix it asap

**Comment by GC-spigot** [comment] 2023-05-05 06:59
This will be fixed today in a couple of hours

**Comment by GC-spigot** [comment] 2023-05-05 11:20
Resolved now finally, update will be out in ~20 minutes.

**Closed by GC-spigot** 2023-05-05 11:20 UTC
Labels: Bug: Unconfirmed, Resolution: Unrelated, Status: Awaiting Response
