### ISSUE TITLE
Trench in update 9.8.3 is now breaking all pickaxes (was on 9.6.11 previously and it did not break them)

### ISSUE THREAD

**Issue by mastachef** [GC-spigot/AdvancedEnchantments#4264] opened 2024-05-08 17:35 UTC
### Describe the bug

Since updating to the recent version trench started to break pickaxes that its enchanted with nearly instantly, my enchantments that have trench 5 and higher break the pickaxe in one hit now, previously trench was not causing durability reduction so why was this changed ?
I was on version 9.6.11 previously and this never happened 

It seems to be affecting items with custom textures more-so than normal items not sure why that would be
this never happened on the prior version I stated above.

### How to reproduce

have a pickaxe enchanted with trench and mine

### "/ae plinfo" link

https://paste.md-5.net/icazoxixog

**Comment by ThomasWega** [comment] 2024-05-13 08:57
![image](https://github.com/GC-spigot/AdvancedEnchantments/assets/82312488/94459fa5-fa71-4331-9b75-38631ba09458)
This is how we handle the drops. You can see we basically use the same item while checking if it's in the inventory of the entity. Maybe other plugins modify the drops on a different event priority or the don't modify the event drops at all. We'd need to get the insights from these plugins to know what the issue is

**Comment by ThomasWega** [comment] 2024-05-13 08:59
duplicate of https://github.com/GC-spigot/AdvancedEnchantments/issues/4228

**Closed by ThomasWega** 2024-05-13 08:59 UTC
Labels: Bug: Unconfirmed

**Comment by mastachef** [comment] 2024-06-09 16:55
Still waiting for a fix
