### ISSUE TITLE
EXTINGUISH error

### ISSUE THREAD

**Issue by bdagenais2** [GC-spigot/AdvancedEnchantments#2733] opened 2022-04-07 17:21 UTC
### Describe the bug

error found in log: https://pastebin.com/JyT9rY1M

### How to reproduce

unknown, just sharing log.

### "/ae plinfo" link

https://paste.md-5.net/pirugufedo

### Server Log

https://pastebin.com/JyT9rY1M

**Comment by Burchard36** [comment] 2022-04-08 23:12
This is likely a duplicate of #2719 refer to my answer there please, also not sure why your error log looks so weird, seems like its cut off at the end

Reply to this if your error is not the same or similar error as that item

**Closed by Burchard36** 2022-04-08 23:12 UTC
Labels: Bug: Unconfirmed
