### ISSUE TITLE
Armor set listener issue

### ISSUE THREAD

**Issue by Thedysons** [GC-spigot/AdvancedEnchantments#3629] opened 2023-09-03 12:36 UTC
### Describe the bug

The armor set bonus only activates when equipping a piece that has an **Advanced Enchantment** on it which is an issue for armor that only utilizes vanilla enchants and uses armor sets for bonus effects. When equipping the full set, **the plugin doesn't even acknowledge that the set has been equipped or unequipped**.

[Ancient.txt](https://github.com/GC-spigot/AdvancedEnchantments/files/12506024/Ancient.txt)

### How to reproduce

1. Equip the set of armor linked above.
2. The set bonus shouldn't activate nor should the message appear.
3. Remove one piece and add any enchantment using the `/ae enchant` cmd.
4. Re-equip the armor piece.
5. The set bonus should trigger.

### "/ae plinfo" link

https://paste.md-5.net/udodivocex

**Comment by GC-spigot** [comment] 2023-09-03 20:18
A duplicate of #3616

**Closed by GC-spigot** 2023-09-03 20:18 UTC
Labels: Bug: Unconfirmed
