### ISSUE TITLE
MMOITEMS custom durability disappears 

### ISSUE THREAD

**Issue by n0tlz** [GC-spigot/AdvancedEnchantments#4229] opened 2024-04-27 12:39 UTC
### Describe the bug

MMOITEMS custom durability disappears when applying a CE onto the item.

### How to reproduce

Generate an item from MMOitems that has a custom durability
add an enchant to it using advanced enchantments

### Screenshots / Videos

https://streamable.com/kvltej

Cant upload the video so i uploaded it somewhere else and here you go.
[latest (1).log](https://github.com/GC-spigot/AdvancedEnchantments/files/15138195/latest.1.log)

Also heres the log file I cant upload it on mcpaste 

### "/ae plinfo" link

https://paste.md-5.net/ipebacocut

**Comment by ThomasWega** [comment] 2024-05-02 07:27
duplicate of https://github.com/GC-spigot/AdvancedEnchantments/issues/4229

**Closed by ThomasWega** 2024-05-02 07:27 UTC
Labels: Bug: Unconfirmed
