### ISSUE TITLE
MORE_DROPS dupe items with mobs 

### ISSUE THREAD

**Issue by hkkongou** [GC-spigot/AdvancedEnchantments#3902] opened 2024-01-06 19:11 UTC
### Describe the bug

When player kill a mob that hold an item and kill the mob with a sword with more drop enchantment. The item on the mob's hand will be duped.
(Shulker box is solved, but other items does not)

### How to reproduce

1. summon a mob
2. mob hold the dupe target item
3. kill the mob with more drop enchantment

### Screenshots / Videos

[https://www.youtube.com/watch?v=MW9wvoPqUd0](https://www.youtube.com/watch?v=MW9wvoPqUd0)

### "/ae plinfo" link

https://paste.md-5.net/unodicaduk

**Comment by ThomasWega** [comment] 2024-01-06 22:37
This is currently an intended behaviour, but we will think about changing this. Or would providing a list of items that cannot be duped (like shulker box currently is) work for you?

**Comment by ThomasWega** [comment] 2024-01-06 23:04
Will be fixed in the next version

**Closed by ThomasWega** 2024-01-06 23:04 UTC
Labels: Bug: Confirmed, Status: In development
