### ISSUE TITLE
TP_DROPS causes server crashes with mcMMO's Treefeller on large trees

### ISSUE THREAD

**Issue by Dakotaa** [GC-spigot/AdvancedEnchantments#3423] opened 2023-06-10 03:44 UTC
### Describe the bug

When using mcMMO's Treefeller ability on large trees with a TP_DROPS tool, there seems to be some kind of infinite recursion or otherwise basically endless loop that causes a server crash.

https://pastebin.com/LFwT8MrB

Probably related, players have reported getting far more mcMMO EXP and tool durability loss when using treefeller with a TP_DROPS tool compared to other tools.

### How to reproduce

Enchant a tool with a TP_DROPS enchantment
Use mcMMO treefeller on a large tree with this tool

### "/ae plinfo" link

https://paste.md-5.net/umefuqurus

**Comment by Dakotaa** [comment] 2023-08-16 18:03
This is still an issue and still causing server crashes.

**Comment by Dakotaa** [comment] 2023-10-22 17:02
Still an issue.

**Comment by ThomasWega** [comment] 2023-10-31 17:37
could you send your spark report please?

**Comment by HalfloveJAR** [comment] 2023-12-24 16:46
I'm having this issue too, Thomas closed my issue since it's a duplicate of this one. But I figured I'd post my details here as well so y'all can see this is a legit problem and multiple people are affected by it still.

https://github.com/GC-spigot/AdvancedEnchantments/assets/29326375/42f2fa50-846e-426c-b40c-2a833f5ae553

**Comment by ThomasWega** [comment] 2023-12-26 17:51
> I'm having this issue too, Thomas closed my issue since it's a duplicate of this one, but I figured I'd post my details here as well so y'all can see this is still a problem that is affecting multiple people.
> bug.mp4

If you could send your spark report, that'd be great

**Comment by ThomasWega** [comment] 2024-01-07 19:07
Will be fixed in the next update!

**Closed by ThomasWega** 2024-01-07 19:07 UTC
Labels: Type: Plugin Conflict, Bug: Confirmed, Type: Performance
