### ISSUE TITLE
Crashing idk why

### ISSUE THREAD

**Issue by LowScarlet** [GC-spigot/AdvancedEnchantments#2258] opened 2021-08-12 08:18 UTC
## Details

**Describe the bug**
Just Crashing

**To Reproduce** 
I don't know how to reproduce, just crashing but I don't know what I'm doing

**Screenshots / Video**
![image](https://user-images.githubusercontent.com/64282946/129162840-011d1a6b-ac87-4ed8-bd73-5c2e2f8c4264.png)

## Server Information
- "/ae plinfo" link: https://paste.md-5.net/oruyopitod
- Server log: https://mcpaste.io/9d7a7a36016fa06d

**Comment by Insprill** [comment] 2021-08-12 15:05
Duplicate of #2254

**Closed by Insprill** 2021-08-12 15:05 UTC
Labels: Resolution: Duplicate
