### ISSUE TITLE
Mining Lapis Ore With Smelting + Silk Touch Drops Ink Sac (use-experimental-block-breaking: true)

### ISSUE THREAD

**Issue by WhatsTheBadNews** [GC-spigot/AdvancedEnchantments#2018] opened 2021-05-29 09:15 UTC
## Details

**Describe the bug**
Mining Lapis Ore with Smelting + Silk Touch drops Ink Sacs.

 I've only tested with `use-experimental-block-breaking: true`, though I am not sure if that makes a difference

**To Reproduce**
1.) Hold a pickaxe with Silk Touch and do /ae enchant Smelting 3
2.) Use the pickaxe to mine a Lapis Ore

## Server Information
- "/ae plinfo" link: https://paste.md-5.net/yefonotavu
- Server log: https://gist.github.com/WhatsTheBadNews/0996a6819b5c3aebdae5e8b6553378a4

**Comment by Insprill** [comment] 2021-05-29 09:18
Duplicate of #1992

**Closed by Insprill** 2021-05-29 09:19 UTC
Labels: Resolution: Duplicate
