### ISSUE TITLE
Enchantments working on Offhand

### ISSUE THREAD

**Issue by KrlozZo** [GC-spigot/AdvancedEnchantments#3597] opened 2023-08-22 20:38 UTC
### Describe the bug

The enchantments type ATTACK and MINING are working on off hand while having another item on main hand, just watch the video

### How to reproduce

- enchant a item with enchantment type attack
- change the item to offhand
- attack with another item in your main hand and the enchantment will work

### Screenshots / Videos

https://github.com/GC-spigot/AdvancedEnchantments/assets/118636389/9158683c-33bf-40dc-990c-c2362a05af35

https://github.com/GC-spigot/AdvancedEnchantments/assets/118636389/e2359bab-a519-4ad3-850e-0211a31c3e2b

### "/ae plinfo" link

no need

**Comment by ThomasWega** [comment] 2023-08-28 15:01
Duplicate of https://github.com/GC-spigot/AdvancedEnchantments/issues/3511. Will hopefully get to it soon :)

**Closed by ThomasWega** 2023-08-28 15:01 UTC
Labels: Bug: Unconfirmed
