### ISSUE TITLE
Firework not launching when enchant book is opened 1.20.4

### ISSUE THREAD

**Issue by moonies44** [GC-spigot/AdvancedEnchantments#4716] opened 2024-11-09 12:37 UTC
### Describe the bug

In 1.20.4, the when opening an enchant book from the enchanter it does not launch a firework in the air

### How to reproduce

open an enchant book in 1.20.4

### "/ae plinfo" link

https://paste.md-5.net/okariduhed

### Server Log

https://mclo.gs/cmIcNrk

### Filled out form correct and using latest version

i confirm

**Comment by ThomasWega** [comment] 2024-11-13 17:20
Are you sure `firework-on-open` is true in config.yml?

**Comment by ThomasWega** [comment] 2024-11-13 17:26
Nevermind, the issue is there

**Comment by ThomasWega** [comment] 2024-11-13 17:45
Fixed in the next update

**Closed by ThomasWega** 2024-11-13 17:45 UTC
Labels: Bug: Confirmed
