### ISSUE TITLE
Chest Duplication and Chestplate Removal

### ISSUE THREAD

**Issue by MasonX3** [GC-spigot/AdvancedEnchantments#2363] opened 2021-09-20 15:38 UTC
### Describe the bug

When attempting to place a chest, or more accurately multiple chests, whatever item is in your chestplate armor slot is deleted and the chest item itself will place and duplicate. 

I've tried every plugin on the server standalone, and this bug only appeared when AdvancedEnchantments was installed.

### How to reproduce

Have a chestplate in your armor slot and hold a chest, if you right-click the chest, it will replace the chestplate with the chest items and place a chest, adding one more chest to the number of chests you had before and deleting whatever was in your chestplate armor slot.

### Screenshots / Videos

Chest Item replacing Chestplate (WITHOUT PLACING THE CHEST): https://gyazo.com/4c8ba650fc802c69741c98cb6a998367

Chest Item replacing Chestplate (With placing the chest) Duplication: https://gyazo.com/ecca50c99f1887b3ff5a0ff86dd14af2

### "/ae plinfo" link

https://paste.md-5.net/xugedisixo

### Server Log

https://mcpaste.io/9173afd0f6ea40ec

**Comment by Insprill** [comment] 2021-09-20 20:29
Duplicate of #2353 (fixed in the next update)

**Closed by Insprill** 2021-09-20 20:29 UTC
Labels: Resolution: Duplicate
