### ISSUE TITLE
Carved Pumpkins Delete Helmets and Duplicate

### ISSUE THREAD

**Issue by BrandonT80** [GC-spigot/AdvancedEnchantments#2766] opened 2022-04-22 03:20 UTC
### Describe the bug

Hello, found a bug that deletes items. I uninstalled all plugins one by one until the issue stopped. Went on a test server and only had this plugin and was able to reproduce this issue 100% of the time.

Video:
https://youtu.be/E9BnvymePMA
  
  

### How to reproduce

1. Wear any type of helmet.
2. Place a Carved Pumpkin.

This will duplicate the carved pumpkin, place one on the ground, one on the players head, and deletes their armor. It flashes in the inventory and disappears. This happens 100% of the time. I was able to turn this feature off with this:

`# Armor Switching (Right click while holding a piece of armor you're already wearing and they will be switched)
armor-switching:
  enabled: false
  sound: LEVEL_UP
  # Is switching between armor skulls enabled
  armorSkullsSwitching: false`
  
  Video:
  https://youtu.be/E9BnvymePMA

### Screenshots / Videos

https://youtu.be/E9BnvymePMA

### "/ae plinfo" link

https://paste.md-5.net/tejeruweqi

**Comment by austv** [comment] 2022-04-22 13:56
You are running AE 8.9.12
This issue was fixed in version 8.9.16, try to update your jar.

**Comment by Burchard36** [comment] 2022-04-23 04:17
This was indeed fixed un 8.9.16, but it had the plaerdatabase bug as well, the issue is now fixed for both on 8.9.18

**Closed** 2022-04-23 04:17 UTC
Labels: Bug: Confirmed, Resolution: Accepted
