### ISSUE TITLE
Trench detonate dupes the Tool it self

### ISSUE THREAD

**Issue by antibitcoin** [GC-spigot/AdvancedEnchantments#2220] opened 2021-07-31 17:31 UTC
## Details

**Describe the bug**
People figure out to dupe the tool it self when they break with it.
Please note downgrading to AdvancedEnchantments-8.5.6.jar solves this issue.

**To Reproduce**
as the player says:
Major dupe
Pickaxes r very broken
Every time you mine a block with detonate it dupes

**Screenshots / Video**

## Server Information
- "/ae plinfo" link: https://paste.md-5.net/vatozexapu
- Server log: https://mcpaste.io/b0f5231e16958b08

**Comment by Insprill** [comment] 2021-07-31 17:43
Duplicate of #2215 (fixed in the next update)

**Closed** 2021-07-31 17:44 UTC
Labels: Resolution: Duplicate
