### ISSUE TITLE
Feature Request - Disable Enchantments on Offhand

### ISSUE THREAD

**Issue by JericNisperos** [GC-spigot/AdvancedEnchantments#3610] opened 2023-08-26 03:16 UTC
### Describe the bug

Players can bypass Enchantment limit since they can put Sword on their Offhand with Enchantments in it and still works. So hoping to have an option to disable Enchantments when on offhand unless specified in the Enchantment.

For easiest way, hoping to have an option from config.yml as a boolean if AE should be disabled from Offhand and has an list in it to exclude any Enchantment name in this option. Or maybe any other way that can make this option possible.

### How to reproduce

Add Enchants to a sword and put it on your offhand slot

### "/ae plinfo" link

N.A

**Comment by ThomasWega** [comment] 2023-08-28 15:04
duplicate of https://github.com/GC-spigot/AdvancedEnchantments/issues/3511. We know about this issue and will address it soon :)

**Closed by ThomasWega** 2023-08-28 15:04 UTC
Labels: Bug: Unconfirmed
