### ISSUE TITLE
Server Freeze

### ISSUE THREAD

**Issue by NightLife-SG** [GC-spigot/AdvancedEnchantments#2265] opened 2021-08-12 17:41 UTC
## Details

**Describe the bug**
 Server freeze until a tps of 5

**To Reproduce** 
 Not sure how this happen

Error -> https://pastebin.com/2xVZRHzC

**Comment by Insprill** [comment] 2021-08-12 19:35
Duplicate of #2254

**Closed by Insprill** 2021-08-12 19:35 UTC
Labels: Resolution: Duplicate
