### ISSUE TITLE
Enchant Message Spam 

### ISSUE THREAD

**Issue by TheLeby9** [GC-spigot/AdvancedEnchantments#2282] opened 2021-08-16 00:09 UTC
## Details

**Describe the bug**

the thing is all operators on the server keep getting this type of message below in the screenshot spammed . and it happens for multiple enchantments too not this specific one only.

**To Reproduce** 

i dont know it just send me those messages

**Screenshots / Video**

![2021-08-16_02 50 41](https://user-images.githubusercontent.com/88544635/129496395-c68f7674-9a18-4bb8-b571-4a496fa94ff8.png)

[23:47:13 INFO]: [AdvancedEnchantments ERROR] Could not pass ArrayIndexOutOfBoundsException: Index 1 out of bounds for length 1
[23:47:13 INFO]: [AdvancedEnchantments]    Class: net.advancedplugins.ae.enchanthandler.effectsreader.RunnableEffect.run(RunnableEffect.java:751)
[23:47:13 INFO]: [AdvancedEnchantments]    Extra info: effect[GUARD:ZOMBIE]; enchant [undeadruse]; mc[117]; ae[8.6.4]
[23:47:13 INFO]: [AdvancedEnchantments] If you cannot indentify cause of this, contact developer providing this report. 

## Server Information
- "/ae plinfo" link: https://paste.md-5.net/ukuyudojom
- Server log: 
[latest.log](https://github.com/GC-spigot/AdvancedEnchantments/files/6989087/latest.log)

**Comment by Insprill** [comment] 2021-08-16 07:53
Duplicate of #2273

**Closed** 2021-08-16 15:18 UTC
Labels: Resolution: Duplicate
