### ISSUE TITLE
Wall torch with trench ench outputs error/warning in console

### ISSUE THREAD

**Issue by SlyyJacob** [GC-spigot/AdvancedEnchantments#2275] opened 2021-08-14 18:02 UTC
When a player breaks wall torch with a trench ench. it outputs this in console:
```
[19:59:35 WARN]: [AdvancedEnchantments] Tried to drop item "WALL_TORCH" but it isn't an obtainable item! Please report this to us on Discord.
[19:59:36 WARN]: [AdvancedEnchantments] Tried to drop item "WALL_TORCH" but it isn't an obtainable item! Please report this to us on Discord.
[19:59:37 WARN]: [AdvancedEnchantments] Tried to drop item "WALL_TORCH" but it isn't an obtainable item! Please report this to us on Discord.
```

plinfo
https://paste.md-5.net/osuruwenin

**Comment by Insprill** [comment] 2021-08-15 16:54
Look like this might be the cause of #2264

**Comment by Insprill** [comment] 2021-08-16 07:49
Is in fact a duplicate of #2264

**Comment by SlyyJacob** [comment] 2021-08-16 08:37
I managed to replicate it with a trench pickaxe with silk touch on this setup
![2021-08-16 10_37_07](https://user-images.githubusercontent.com/36818957/129535640-bfd1ad04-5eb1-4f5c-969c-050470d6e240.jpg)

`[10:37:01 WARN]: [AdvancedEnchantments] Tried to drop item "WALL_TORCH" but it isn't an obtainable item! Please report this to us on Discord.`

**Closed** 2021-08-18 00:13 UTC
Labels: Resolution: Duplicate
