### ISSUE TITLE
MORE_DROPS On mining Types not working at all.

### ISSUE THREAD

**Issue by RustyDagger** [GC-spigot/AdvancedEnchantments#2313] opened 2021-08-21 03:27 UTC
## Details

**Describe the bug**
The MORE_DROPS is not dropping more of the ore's from iron/gold/redstone etc
by default it was set to MORE_DROPS:1 and 1x any thing is still default so the default config is idiotic....
However setting it to MORE_DROPS:2 did not result in more items either. Iv added a sound for testing purposes so you can hear when it activates.

**To Reproduce** 
https://paste.md-5.net/edabinazoq.pl
Install this enchantment on any pickaxe and break several iron_ore or any ore type block. then use an unenchanted pickaxe and observe that the item drop amounts are the same.

## Server Information
- "/ae plinfo" link: https://paste.md-5.net/aziroxapoj.m
- Server log: https://paste.md-5.net/ucijufoyoz.md

**Comment by Insprill** [comment] 2021-08-23 18:57
Your chance is only 45%, does setting it to 100 make it work? It works fine for me. It also duplicates the drops by count + 1 so setting it to 1 will result in 2 drops, 2 will be 3x, etc.

**Comment by RustyDagger** [comment] 2021-08-23 23:02
> 
> 
> Your chance is only 45%, does setting it to 100 make it work? It works fine for me. It also duplicates the drops by count + 1 so setting it to 1 will result in 2 drops, 2 will be 3x, etc.

please read it again I said "break a few blocks" this was to allow for it to activate......... I added the sound I know its activating and not changing the drops.
if you changed the enchantment before testing maybe that made it work. I do not wish for every block to drop more tho to the chance is needed.

**Comment by Insprill** [comment] 2021-08-24 01:05
Didn't mean to insult you, was just asking you to test it with a 100% chance to eliminate bad luck with only a 45% chance. I will also update the wiki to reflect how it's actually handled. This is the enchantment I've used to test it, give it a go and see if it works. If it doesn't, try enabling/disabling experimental-block-breaking in the configs and see if that changes anything. 
```yaml
multiplication:
  display: "%group-color%Multiplication"
  description: "Chance to multiply ore drops.\nCosts 5 souls / activation."
  applies-to: "Pickaxe"
  type: "MINING;KILL_MOB"
  group: "FABLED"
  applies:
    - ALL_PICKAXE
  levels:
    1:
      effects:
        - "MORE_DROPS:1"

**Comment by RustyDagger** [comment] 2021-08-24 01:17
I added your enchantment to a Pickaxe and no extra drops, I then enabled the experimental block breaking and did a full server reboot,
It seems to now be behaving as intended and dropping the extra items.

**Comment by Insprill** [comment] 2021-08-24 03:51
Alright, since I can't reproduce this and experimental-block-breaking fixed it for you I'm gonna mark this as not a bug and close it. Just leave experimental-block-breaking enabled, it actually tends to be more stable than normal block breaking.

**Closed by Insprill** 2021-08-24 03:51 UTC
Labels: Resolution: Not a Bug
