### ISSUE TITLE
REPEATING Trigger work for held items

### ISSUE THREAD

**Issue by gamerdorks** [GC-spigot/AdvancedEnchantments#4050] opened 2024-02-27 23:07 UTC
### Describe the bug

The REPEATING trigger doesn't work on mainhand / offhand items, only on armor.

### How to reproduce

Create a REPEATING trigger on a mainhand item such as a sword, with a simple MESSAGE effect for debug purposes.

### Screenshots / Videos

https://prnt.sc/0-w38clXo6tS

### "/ae plinfo" link

https://paste.md-5.net/lucowenuji

**Comment by ThomasWega** [comment] 2024-02-28 07:45
REPEATING trigger currently only work for Armor. I will leave this as feature request

**Comment by gamerdorks** [comment] 2024-03-18 13:56
> REPEATING trigger currently only work for Armor. I will leave this as feature request

The wiki said that it worked for held items, that's why I called this a bug and not a suggestion.  Fix the wiki, or fix the feature.

**Comment by ThomasWega** [comment] 2024-03-18 15:59
> > REPEATING trigger currently only work for Armor. I will leave this as feature request
> 
> The wiki said that it worked for held items, that's why I called this a bug and not a suggestion. Fix the wiki, or fix the feature.

Where do you see this?

**Comment by ThomasWega** [comment] 2024-03-22 22:35
duplicate of https://github.com/GC-spigot/AdvancedEnchantments/issues/4050

**Closed by ThomasWega** 2024-03-22 22:35 UTC
Labels: Type: Feature Request
