### ISSUE TITLE
Multiplication enchantment not working

### ISSUE THREAD

**Issue by RMF-AndyPlayz** [GC-spigot/AdvancedEnchantments#3076] opened 2022-10-21 23:03 UTC
### Describe the bug

Title; The multiplication enchantment isn't working.

### How to reproduce

I tried this on diamond ore

1. Place down a few diamond ores
2. Get a pickaxe with multiplication 5
3. Mine diamond ore with mult. 5 pickaxe
4. You will notice that no matter how hard you try or even if you set the chance to 100%, the drops won't multiply.

### Screenshots / Videos

My server multiplication enchant config:
`multiplication:
  display: "%group-color%Multiplication"
  description: "Chance to multiply ore drops.\nCosts 5 souls / activation."
  applies-to: "Pickaxe"
  type: "MINING"
  group: "FABLED"
  applies:
    - ALL_PICKAXE
  levels:
    1:
      chance: 15
      cooldown: 5
      condition: "%block type% contains ORE : %allow%"
      souls: 5
      effects:
        - "MORE_DROPS:1"
    2:
      chance: 20
      cooldown: 5
      condition: "%block type% contains ORE : %allow%"
      souls: 5
      effects:
        - "MORE_DROPS:1"
    3:
      chance: 25
      cooldown: 6
      condition: "%block type% contains ORE : %allow%"
      souls: 5
      effects:
        - "MORE_DROPS:1"
    4:
      chance: 28
      cooldown: 7
      condition: "%block type% contains ORE : %allow%"
      souls: 5
      effects:
        - "MORE_DROPS:1"
    5:
      chance: 30
      cooldown: 8
      condition: "%block type% contains ORE : %allow%"
      souls: 5
      effects:
        - "MORE_DROPS:1"`
The debug message that pops up when mining diamond ore with multiplication V
![image](https://user-images.githubusercontent.com/58617083/197303131-8ebcbba6-5c98-4da7-ab8c-a6bb3f714ff7.png)

### "/ae plinfo" link

https://paste.md-5.net/sazuliyawa

**Comment by DuneSciFye** [comment] 2022-10-21 23:23
I tested this and confirmed

**Comment by reussy** [comment] 2022-10-29 03:50
Hello @RMF-AndyPlayz @DuneSciFye 👋

Quoting what you say **`"Place down a few diamond ores"`**, this won't never work with ores that are placed by a player. This is to avoid duplication bugs, if you try this with naturally generated minerals it will work correctly.

**Comment by DuneSciFye** [comment] 2022-10-29 22:42
Ah alright. I'll keep this in mind in the future. I did indeed place them down. Thank you.

**Comment by Awpmeister2170** [comment] 2022-11-08 01:06
Closing due to being clarified

**Closed by Awpmeister2170** 2022-11-08 01:06 UTC
Labels: Bug: Unconfirmed
