### ISSUE TITLE
Server Crash Issue Related to Haste Enchantment

### ISSUE THREAD

**Issue by Kaludii** [GC-spigot/AdvancedEnchantments#3856] opened 2023-12-12 18:29 UTC
### Describe the bug

Hello, I am experiencing a recurring server crash issue related to the Haste custom enchantment in the AdvancedEnchantments plugin. This problem occurs specifically when using tools with the Haste enchantment. The server crashes when even a single block is dug/broken. For example, breaking blocks like gravel or dirt leads to an unexpected shutdown of the server. The issue seems to be linked to the Haste enchantment, as removing it from the tool prevents the crashes. I have attached the shovel that made our server crash each time it was used, along with all the enchants it included.

### How to reproduce

Equip a tool (like a shovel) with the Haste enchantment.
Use the tool to break blocks (e.g., gravel, dirt).
Observe the server's response (crash occurs shortly after performing these actions).

### Screenshots / Videos

https://media.discordapp.net/attachments/1182160640253624380/1183711954964066374/image.png?ex=658954aa&is=6576dfaa&hm=a5b948368cce708b33aa5d09409d3080b75580f5d501269dd6b7bad2502123cd&=&format=webp&quality=lossless

### "/ae plinfo" link

https://paste.md-5.net/nigatujije

### Server Log

(Onl https://mcpaste.io/6fa72cbebc6818e1

**Comment by Kaludii** [comment] 2023-12-12 18:30
This is the full data for the shovel when it had the Haste enchant if it helps:
`[17:22:37 INFO]: Kaludii has the following entity data: {Slot: 0b, id: "minecraft:netherite_shovel", tag: {"ae_enchantment;detonate": 5, "ae_enchantment;haste": 3, Enchantments: [{id: "minecraft:efficiency", lvl: 5s}, {id: "minecraft:fortune", lvl: 3s}, {id: "minecraft:mending", lvl: 1s}, {id: "minecraft:unbreaking", lvl: 3s}], Damage: 0, PublicBukkitValues: {"toolstats:hash": "1b4b42fdf580451649831cfeb3bf72ee6ef0bc13dc68b01cd0cee157d86b56a7", "toolstats:origin": 6, "toolstats:generic-mined": 108894, "toolstats:time-created": 1702197957822L, "toolstats:owner": [B; -33B, 19B, 25B, -75B, 94B, -114B, 67B, -5B, -72B, 4B, 14B, -26B, 84B, 44B, 96B, -128B]}, transmogged: "true", "ae_enchantment;reforged": 4, "ae_enchantment;abiding": 1, slots: 6, "ae_enchantment;restore": 4, display: {Name: '{"extra":[{"bold":true,"italic":true,"underlined":false,"strikethrough":false,"obfuscated":false,"color":"dark_red","text":"Legendary "},{"bold":false,"italic":false,"color":"dark_red","text":"["},{"italic":false,"color":"gray","text":"Netherite Shovel"},{"italic":false,"color":"dark_red","text":"] "},{"italic":false,"color":"light_purple","text":"["},{"italic":false,"underlined":true,"color":"aqua","text":"6"},{"italic":false,"underlined":false,"color":"light_purple","text":"]"}],"text":""}', Lore: ['{"extra":[{"bold":false,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false,"color":"gray","text":"Haste III"}],"text":""}', '{"extra":[{"bold":false,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false,"color":"green","text":"Experience V"}],"text":""}', '{"extra":[{"bold":false,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false,"color":"aqua","text":"Reforged IV"}],"text":""}', '{"extra":[{"bold":false,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false,"color":"yellow","text":"Detonate V"}],"text":""}', '{"extra":[{"bold":false,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false,"color":"yellow","text":"Restore IV"}],"text":""}', '{"extra":[{"bold":false,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false,"color":"gold","text":"Abiding I"}],"text":""}', '{"extra":[{"bold":false,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false,"color":"dark_gray","text":""}],"text":""}', '{"extra":[{"bold":false,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false,"color":"dark_gray","text":"► "},{"italic":false,"color":"gray","text":"This item can only be obtained"}],"text":""}', '{"extra":[{"bold":false,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false,"color":"dark_gray","text":"► "},{"italic":false,"color":"gray","text":"from "},{"italic":false,"color":"dark_red","text":"⧉ "},{"bold":true,"italic":true,"color":"dark_red","text":"Legendary Crate "},{"bold":false,"italic":false,"color":"dark_red","text":"⧉"}],"text":""}', '{"extra":[{"bold":false,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false,"color":"dark_gray","text":""}],"text":""}', '{"extra":[{"bold":false,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false,"color":"gray","text":"Spawned on: "},{"italic":false,"color":"dark_gray","text":"12/10/2023"}],"text":""}', '{"extra":[{"bold":false,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false,"color":"gray","text":"Spawned in by: "},{"italic":false,"color":"dark_gray","text":"Kaludii"}],"text":""}', '{"extra":[{"bold":false,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false,"color":"gray","text":"Blocks mined: "},{"italic":false,"color":"dark_gray","text":"108,894"}],"text":""}']}, "ae_enchantment;experience": 5}, Count: 1b}`

**Comment by SirJben** [comment] 2023-12-13 06:40
Hello, does disabling VeinMiner plugin helps?

**Comment by Kaludii** [comment] 2023-12-15 03:46
> Hello, does disabling VeinMiner plugin helps?

Hello, disabling veinminer seems to fix it. So it is an issue with the VeinMiner plugin. We are using the latest version for that plugin `2.1.1`.

**Comment by SirJben** [comment] 2023-12-16 14:19
Contact the other plugin for this issue.

**Comment by 2008Choco** [comment] 2023-12-31 01:36
Author of VeinMiner, jumping in on this issue.

I don't think there's much I can do to resolve this issue. I'm unsure why AdvancedEnchantments is attempting to break a block if the alleged culprit is a simple enchantment that does nothing more than add a haste potion effect to the player, so maybe this is something worth looking into on your end. VeinMiner will break blocks that are within the vein (as it should), but will ignore `BlockBreakEvent` calls from blocks that have the `veinminer:to_be_veinmined` metadata key to avoid recursive vein mines.

If you'd like a quick band-aid patch in your plugin, you can ignore `BlockBreakEvent` calls from blocks with the aforementioned metadata key, but that will probably break _integration_ that we would otherwise like to retain (say double drops from a block that was broken as a result of vein miner). I think the real issue is AE calling a BBE for an effect that shouldn't break blocks.

**Comment by ThomasWega** [comment] 2024-01-03 08:35
We don't run any BlockBreakEvent unless the effect is supposted to break blocks. I've tested the haste enchantment and it does NOT run a BlockBreakEvent. However, I will test more and we will figure out a solution to this.

**Comment by Kaludii** [comment] 2024-01-04 02:00
> We don't run any BlockBreakEvent unless the effect is supposted to break blocks. I've tested the haste enchantment and it does NOT run a BlockBreakEvent. However, I will test more and we will figure out a solution to this.

Thank you both! I added the full NBT data of the item that was causing it in my original post, and the item also had the `detonate` enchant, which breaks blocks in 3x3. It may have something to do with the combination of detonate and haste enchants that are causing the server to crash when veinminer is toggled on.

**Comment by ThomasWega** [comment] 2024-01-04 07:08
Well obviously this is going to cause issues. Will cause infinite calls because we run BlockBreakEvents for Trench which the Veinminer will respond to. I will try to add checks for the NBT data of Veinminer and this can hopefully be fixed. Will let you know how it goes

**Comment by ThomasWega** [comment] 2024-01-04 07:13
Do you mind sending a video please? I cannot reproduce it :D

**Comment by 2008Choco** [comment] 2024-01-05 01:40
I'm willing to work on a bit more of a broad solution and implement some changes into VeinMiner directly. This isn't an AdvancedEnchantments-exclusive issue. It's an issue with any plugin that forces a player to break a block. Like I said in my first comment, in some instances this is actually desirable (again - fortune-like enchantments come to mind). I foresee more complaints about AE enchantments not working together with VM than an incompatibility.

Maybe some action that allows enchantments to be configured to assign a boolean metadata value to a block would be convenient here. If the action is present, `block.setMetadata("blockbreakevent-handle", new FixedMetadataValue(plugin, false));` (or maybe a better key), call the `BlockBreakEvent`, remove the metadata value (to avoid memory leaks), proceed. I can then ignore any blocks that have that specific metadata value. With this approach, it delegates the compatibility to the user but allows for much more flexibility when plugins like mine, or tree-capitator, or other similar plugins want to work in tandem.

I would like to maybe create some sort of standard that other enchantment plugins can use as well, or even just any plugin wanting to listen for BlockBreakEvents recursively as we both clearly want to do. I'm open to suggestions.

**Comment by 2008Choco** [comment] 2024-01-05 14:11
I think that's fine, although that would have me avoid _all_ interactions, which I want to avoid.

**Comment by GC-spigot** [comment] 2024-01-06 11:47
> I think that's fine, although that would have me avoid _all_ interactions, which I want to avoid.

Agree. We have enchantments that handle drops, e.g. smelt them, teleport them to inventory. How are drops handled in your VeinMiner plugin? If you did ignore our breaks from `fakeBreak` metadata, we may be able then to still keep full support of your plugin's veinmining.

**Comment by 2008Choco** [comment] 2024-01-13 18:31
Sorry, I was busy this last week.

> How are drops handled in your VeinMiner plugin?

However vanilla handles them. I don't do any custom drops whatsoever. I just invoke Player#breakBlock() for all blocks that need breaking. The item drops are handled by vanilla and anything else that manages a `BlockBreakEvent` or `BlockDropItemEvent`. Not my responsibility. VeinMiner just needs to break the blocks, that's it.

> If you did ignore our breaks from fakeBreak metadata, we may be able then to still keep full support of your plugin's veinmining.

I suppose it's probably fine to be honest. Would really like @Auxilor to also jump in on this issue and see if we can come to an agreement between two of the larger custom enchantment plugins and specify a standard. Maybe they want to adhere to `fakeBreak` as well but it should be consistent.

**Comment by WillFP** [comment] 2024-01-13 18:37
In EcoEnchants (and the rest of my plugins), veinminer-like effects put a temporary meta value on the blocks called `block-ignore` which should do exactly what you need

**Comment by ThomasWega** [comment] 2024-01-16 08:08
we have changed all "fakeBreak" metadata to "blockbreakevent-ignore". Will be present in one of the upcoming updates in max few days. All good if I mark this as solved now?

**Comment by ThomasWega** [comment] 2024-01-16 09:02
I am pretty sure update will be in a few days at most. I will leave this issue open for now

**Comment by 2008Choco** [comment] 2024-01-16 15:37
> we have changed all "fakeBreak" metadata to "blockbreakevent-ignore". Will be present in one of the upcoming updates in max few days. All good if I mark this as solved now?

I'll be sure to update VeinMiner some time this weekend when I have time away from work. Thank you for coming to an amicable solution :) I appreciate it a lot.

**Closed** 2024-01-18 11:00 UTC
Labels: Type: Plugin Conflict, Resolution: Accepted, Status: Awaiting Response, Status: Resolved
