### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by TylorTurner** [GC-spigot/AdvancedEnchantments#4260] opened 2024-05-08 00:34 UTC
### Describe the bug

![image](https://github.com/GC-spigot/AdvancedEnchantments/assets/133236597/4bc6344d-e796-43d4-b411-f26baf2ff379)

### How to reproduce

Console error

### "/ae plinfo" link

https://paste.md-5.net/ifeloweqox

**Comment by ThomasWega** [comment] 2024-05-08 20:05
duplicate of https://github.com/GC-spigot/AdvancedEnchantments/issues/4256

**Closed by ThomasWega** 2024-05-08 20:05 UTC
Labels: Bug: Unconfirmed
