### ISSUE TITLE
Itemsadder With MMOItems + Smelt enchant has bug occur

### ISSUE THREAD

**Issue by hyein6790** [GC-spigot/AdvancedEnchantments#4302] opened 2024-05-18 01:39 UTC
### Describe the bug

Only itemsadder has problem.
enchanting with smelt effect => extreamly low durability.
it doesn't look lower durability but break a few blocks, it going to broken. (2~30 blocks)

### How to reproduce

Only itemsadder has problem.
enchanting with smelt effect => extreamly low durability.
it doesn't look lower durability but break a few blocks, it going to broken. (2~30 blocks)

### "/ae plinfo" link

https://paste.md-5.net/apifucapuy

**Comment by ThomasWega** [comment] 2024-05-19 12:08
Duplicate of https://github.com/GC-spigot/AdvancedEnchantments/issues/4228

**Closed by ThomasWega** 2024-05-19 12:08 UTC
Labels: Bug: Unconfirmed
