### ISSUE TITLE
ProjectileLaunchEvent TRIDENT_THROW error in version prior 1.13

### ISSUE THREAD

**Issue by CryLegende** [GC-spigot/AdvancedEnchantments#2361] opened 2021-09-20 12:13 UTC
### Describe the bug

ProjectileLaunchEvent throw an error with AE 8.6.13 (latest version) in servers using a version prior 1.13 because of the trident who doesn't exist in those versions

### How to reproduce

ProjectileLaunchEvent

### Screenshots / Videos

![image](https://user-images.githubusercontent.com/25080946/134000196-adc35390-3758-4abb-a768-bf41e0f1f21a.png)

### "/ae plinfo" link

https://paste.md-5.net/omiluxanof

**Comment by Insprill** [comment] 2021-09-20 20:28
Duplicate of #2352 (fixed in the next update)

**Closed by Insprill** 2021-09-20 20:28 UTC
Labels: Resolution: Duplicate
