### ISSUE TITLE
[Issue] The `/asets update` command does not work reliably.

### ISSUE THREAD

**Issue by smyaknti** [GC-spigot/AdvancedEnchantments#1757] opened 2021-03-08 14:11 UTC
**Description**
The `/asets reload` command does not work reliably post Pre 20.5 version. The armour sets sometimes do not load properly at all.

**Reproduction**
Just copy a armour set config file and change some values in it and it will break the loading.

**Screenshots / Video**
![image](https://user-images.githubusercontent.com/13618933/110332230-1860df80-8046-11eb-8af4-769ae73c4840.png)
The above prompt is shown but once i try to see the armorsets they do not update

Edit: I found this new issue
![image](https://user-images.githubusercontent.com/13618933/110332805-d2f0e200-8046-11eb-95f1-ab6f7df013e3.png)
The set files do not even show up sometimes now. The defaults are the same, previously it were fine

**Server Information (please complete the following information):**
- Server Version: [e.g. Paper-499 1.16.5]
- Plugin Version: [e.g. Pre 20.7]

**Comment by Insprill** [comment] 2021-03-24 01:03
I was not able to reproduce this issue on my dev build on 21.6. Can you verify all your files using [this website](https://www.yamlchecker.com/)? If there aren't any syntax errors try it out on the latest version and see if it still happens.

**Comment by smyaknti** [comment] 2021-03-24 17:23
Actually I copied over a old set and renamed it, that should make 2 sets of same property but different names, which wasnt the case.

I shall report my findings with the latest version.

**Comment by Insprill** [comment] 2021-03-27 22:06
Any updates?

**Comment by smyaknti** [comment] 2021-03-28 03:48
Sorry for the delay in proper testing, the issue I am facing is creation of new custom sets mainly. I plan to make new asets and as I found no other documentation, I proceeded as mentioned in the config files. Can you please test the feature of creation of new ArmorSets? If it works then its all fine, I will try to fix any bugs from my end.

**Comment by smyaknti** [comment] 2021-03-28 12:43
Update: Tested with the newest version, the armor sets are fine, as in the yaml files and things work, but the loading is bugged. If I rename the config files they do not tend to load. The way I managed to load is to rename a default armor set and then copy my custom armor set config into the file. 

My files are fine, just the loading is bugged out. I cannot add my self created armorsets reliably.

**Comment by Insprill** [comment] 2021-03-30 02:04
are you changing the name field?

**Comment by smyaknti** [comment] 2021-03-30 03:06
Is that the identifier? Then some of them can be duplicates. I will test and report findings asap.

**Comment by smyaknti** [comment] 2021-03-30 05:33
![image](https://user-images.githubusercontent.com/13618933/112938532-69e12380-9147-11eb-8b7e-7efe1d8c7112.png)
No, it didn't help. I even deleted the default configs, still nothing. I didn't restart the server yet.. not sure whats going on. :/
I will comment after testing on a smaller sub server in our network which I can restart

**Comment by Insprill** [comment] 2021-03-30 06:51
You can't delete the default sets. We can change that. Other then that is it all working correctly now?

**Comment by smyaknti** [comment] 2021-03-30 06:53
Umm not only the default sets, any sets loaded stays loaded. And the changes are not being picked up. Is it a one off issue?

**Comment by Insprill** [comment] 2021-03-30 07:10
Ah so it just doesn't unload sets?

**Comment by smyaknti** [comment] 2021-03-30 08:34
Seems like it. It would be cool if it loads the sets on reload clearing the old ones...

**Comment by Insprill** [comment] 2021-03-30 08:42
Alright. Would you mind creating another issue specific to the reload command not unloading sets? Going to close this issue to not cause confusion.

**Closed** 2021-03-30 08:42 UTC
Labels: Bug: Unconfirmed
