### ISSUE TITLE
Potion effect lost when wearing EFFECT_STATIC enchantment and unequipping HELD enchantment

### ISSUE THREAD

**Issue by Dakotaa** [GC-spigot/AdvancedEnchantments#2046] opened 2021-06-07 18:42 UTC
## Details

**Describe the bug**
When a player is wearing an EFFECT_STATIC piece of armour that gives a potion effect, night vision, for example, and they are holding a tool that has a HELD enchantment that gives the same potion effect, the effect will be lost when they unequip the tool, even though they're still wearing the armour that should be giving them the effect.

**To Reproduce**
Wear a piece of armour with an EFFECT_STATIC enchantment that gives a potion effect.
Hold a tool with a HELD enchantment that gives the same potion effect as the armour.
Unequip the tool, the potion effect will be removed, even though the armour is still equipped.

## Server Information
- "/ae plinfo" link: https://paste.md-5.net/mohupociza

**Comment by Insprill** [comment] 2021-06-09 00:49
Duplicate of #2039

**Closed by Insprill** 2021-06-09 00:49 UTC
Labels: Resolution: Duplicate
