### ISSUE TITLE
Trench, Waterwalker, Lavawalker BUG

### ISSUE THREAD

**Issue by LavosKore** [GC-spigot/AdvancedEnchantments#3546] opened 2023-08-03 13:27 UTC
### Describe the bug

This enchants don't work, and when they used appear this message in console https://pastebin.com/uaqQFDFK

### How to reproduce

When i mine with a pickaxe with trench up, appear this message, and block mined drop nothing, same for lavawalker and waterwalker, i think is an issue with Factions, i use SaberFactions.

### Screenshots / Videos

https://pastebin.com/uaqQFDFK

### "/ae plinfo" link

https://paste.md-5.net/pitibijube

**Comment by GC-spigot** [comment] 2023-08-03 17:37
duplicate of #3486

**Closed by GC-spigot** 2023-08-03 17:37 UTC
Labels: Bug: Unconfirmed
