### ISSUE TITLE
TP_DROPS doesn't add broken blocks to statistics

### ISSUE THREAD

**Issue by Dakotaa** [GC-spigot/AdvancedEnchantments#2142] opened 2021-07-13 16:04 UTC
## Details

**Describe the bug**
When using a tool with TP_DROPS, breaking blocks does not add the broken blocks to the ingame statistics count.

**Comment by Insprill** [comment] 2021-07-16 14:04
Duplicate of #2106

**Closed by Insprill** 2021-07-16 14:04 UTC
Labels: Bug: Confirmed, Resolution: Duplicate
