### ISSUE TITLE
Fortune not working with Telepathy enchant 

### ISSUE THREAD

**Issue by LuluxClient** [GC-spigot/AdvancedEnchantments#1840] opened 2021-04-05 13:49 UTC
## Details

**Describe the bug**

Fortune and the telepathy enchant (TP_DROPS) doesn't work together
**To Reproduce**

Simply enchant your pickaxe with fortune 3 and telepathy and mine a diamond ore and bam you only get 1...
**Screenshots / Video**

https://gyazo.com/f56bf772a780216079fe641c0a9b8ef9

## Server Information
- "/ae plinfo" link: 
- Server log: 
- plugin ver : 8.0.0-Pre22.3
- Server ver : paper 1.8.8-443 (latest)

**Comment by LuluxClient** [comment] 2021-04-05 13:49
Only AdvancedEnchants & vault & papi & essentialsX & SaberFaction on the server

**Comment by Insprill** [comment] 2021-04-06 02:16
duplicate of #1822

**Closed by Insprill** 2021-04-06 02:16 UTC
Labels: Resolution: Duplicate
