### ISSUE TITLE
Telepathy enchant does not work with jobs plugin or MCMMO

### ISSUE THREAD

**Issue by TheLeby9** [GC-spigot/AdvancedEnchantments#2243] opened 2021-08-06 13:45 UTC
Before reporting a bug, make sure you have the latest version of the plugin.
Advanced Plugins: https://advancedplugins.net/item/1/   yes
Spigot: https://www.spigotmc.org/resources/43058/     yes

**Describe the bug**
Using telepathy enchant wont trigger miner job. if you are in miner job from jobs plugin and u are using a telepathy pickaxe , then the job wont work it wont trigger the breaking block effect and give money or xp . Same for MCMMO it wont trigger the mcmmo mining.

**To Reproduce** 
join miner job in jobs plugin and use telepathy enchant on pickaxe and mine and it wont trigger the miner job. same for mcmmo

**Screenshots / Video**
https://streamable.com/hay4x7

## Server Information
- "/ae plinfo" link: https://paste.md-5.net/ogiqoqujoy
- Server log: https://mcpaste.io/53bc331796ff209b

**Comment by Insprill** [comment] 2021-08-06 14:14
Duplicate of #2213 & #1361

**Closed by Insprill** 2021-08-06 14:14 UTC
Labels: Resolution: Duplicate
