### ISSUE TITLE
PUMPKIN / TIMERS BUG UNFAIR

### ISSUE THREAD

**Issue by illudota** [GC-spigot/AdvancedEnchantments#2677] opened 2022-03-10 06:17 UTC
### Describe the bug

The duration of the Pumpkin effect is still ongoing even after death, this makes players retrieve their helm when they die with pumpkin effect. 

EXTRA NOTES: BTW This also works on "WAIT" , etc, the timers are still ongoing even after player deaths. such as "WAIT" AND "HARM" CEs EX: Bleed, etc. please disable timers on player death.

About the 'WAIT' AND 'HARM' one, its very dangerous since if players have holy white on their item and when timer still ongoing after respawn, then they die again, holy white will be removed and item will be dropped on spawn.

So Conclusion: Please remove / disable 'WAIT' and 'PUMPKIN' timers on player death so these kind of bugs wont happen

### How to reproduce

wait till pumpkin effect procs on that player, kill him, then he respawns and wait a few secs he will regain his helm, check the video below.

EXTRA NOTES: BTW This also works on "WAIT" , etc, the timers are still ongoing even after player deaths. such as "WAIT" AND "HARM" CEs EX: Bleed, etc. please disable timers on player death.

About the 'WAIT' AND 'HARM' one, its very dangerous since if players have holy white on their item and when timer still ongoing after respawn, then they die again, holy white will be removed and item will be dropped on spawn.

So Conclusion: Please remove / disable 'WAIT' and 'PUMPKIN' timers on player death so these kind of bugs wont happen

### Screenshots / Videos

ABOUT THE PUMPKIN:
https://www.youtube.com/watch?v=S3Wk6ZeHeak&feature=youtu.be
https://www.youtube.com/watch?v=3-4d5IiwJ5k

ABOUT THE HARM:
https://www.youtube.com/watch?v=_zdrT_fmC34

### "/ae plinfo" link

https://paste.md-5.net/huxejigawo

### Server Log

https://mcpaste.io/576f1f90a1271825

### Enchantment I Used As Test:

ABOUT THE PUMPKIN:
halloweenify:
  display: '%group-color%Halloweenify'
  description: 'Chance to replace your opponents helmet to a pumpkin for a short time.'
  applies-to: 'Weapons'
  type: 'ATTACK'
  group: 'MASTERY'
  applies:
    - ALL_SWORD
    - ALL_AXE
  levels:
    1:
      cooldown: 10
      effects:
        - 'PUMPKIN:80 %victim%'
        - 'MESSAGE:&e&l** HALLOWEENIFY ** %victim%'
        - 'PLAY_SOUND_OUTLOUD:ANVIL_DROP'

ABOUT THE HARM:
rupture:
  display: '%group-color%Rupture'
  description: "&fBleeds, weakens removes regen\n&ffrom your opponent\n&fafter the bleed duration, there will be\n&fa slight burst of damage\n&6Requires:\n&eDeep &eBleed &eVI"
  applies-to: 'Swords'
  group: 'MASTERY'
  type: 'ATTACK'
  applies:
    - ALL_SWORD
  settings:
    required-enchants:
      - 'deepbleed:6'
    removed-enchants:
      - 'deepbleed'
  levels:
    '1':
      cooldown: 10
      effects:
        - 'CURE:REGENERATION %victim%'
        - 'POTION:WEAKNESS:0:100 %victim%'
        - 'MESSAGE:&4&l** RUPTURE ** %attacker%'
        - 'MESSAGE:&4&l** RUPTURED ** %victim%'
        - 'PLAY_SOUND_OUTLOUD:ENTITY_STRIDER_DEATH'    
        - 'ADD_HARM:<random number>1-4</random number> %victim%'
        - 'WAIT:10'
        - 'ADD_HARM:<random number>1-4</random number> %victim%'
        - 'WAIT:10'
        - 'ADD_HARM:<random number>1-4</random number> %victim%'
        - 'WAIT:10'
        - 'ADD_HARM:<random number>1-4</random number> %victim%'
        - 'WAIT:10'
        - 'ADD_HARM:<random number>1-4</random number> %victim%'
        - 'WAIT:10'
        - 'ADD_HARM:<random number>1-4</random number> %victim%'
        - 'WAIT:10'
        - 'ADD_HARM:<random number>1-4</random number> %victim%'
        - 'WAIT:10'
        - 'ADD_HARM:<random number>1-4</random number> %victim%'
        - 'WAIT:10'
        - 'ADD_HARM:<random number>1-4</random number> %victim%'
        - 'WAIT:10'
        - 'ADD_HARM:<random number>1-4</random number> %victim%'
        - 'WAIT:10'
        - 'ADD_HARM:<random number>1-4</random number> %victim%'
        - 'WAIT:10'
        - 'ADD_HARM:10 %victim%'

**Comment by illudota** [comment] 2022-03-16 01:04
Any updates? :< Players keep dying in spawn and drop their items due to the HARM CE i made :<

**Comment by illudota** [comment] 2022-03-28 14:53
Halloweenify seems fixed, it's now the 'WAIT' one, please fix! ty!

**Comment by Burchard36** [comment] 2022-03-29 00:41
Hello its fixed now: #2715

**Comment by Burchard36** [comment] 2022-03-29 00:49
Closing this as it is a duplicate of the other 2 issues opened

**Closed by Burchard36** 2022-03-29 00:49 UTC
Labels: Bug: Confirmed, Resolution: Accepted
