### ISSUE TITLE
HolyWhite scroll bug, when they die it does not disappear and eliminates the item it protected

### ISSUE THREAD

**Issue by WAFFUGOD** [GC-spigot/AdvancedEnchantments#3660] opened 2023-09-13 07:40 UTC
### Describe the bug

In this bug not only what happened previously happens that the players died but they were still in the item, now the same thing happens but the protected items disappear

### How to reproduce

the player applies the sacred white scroll to the item, it enters pvp, the items protected upon death remain protected, but one of all the items disappears.

As you can see in the video, first the helmet disappears, then the boots and so on

### Screenshots / Videos

https://youtu.be/7i3cXu2-7j0

### "/ae plinfo" link

I don't Know what to fill here

**Comment by ThomasWega** [comment] 2023-09-13 19:11
duplicate of https://github.com/GC-spigot/AdvancedEnchantments/issues/3658

**Closed by ThomasWega** 2023-09-13 19:11 UTC
Labels: Bug: Unconfirmed
