### ISSUE TITLE
Infinite Haste | Haste CE

### ISSUE THREAD

**Issue by itslukemango** [GC-spigot/AdvancedEnchantments#2211] opened 2021-07-29 19:43 UTC
## Details

**Describe the bug**

You can glitch any tool with any potion effect CE to keep the effect permanently by spamming it in the same slot until the item is deselected and the effect remains.

**To Reproduce**

Put any potion effect CE on a tool, spam the tool until you have it deselected and the effect remains, it's now permanent.

**Screenshots / Video**

https://streamable.com/6kuqnn

## Server Information
- "/ae plinfo" link:  https://paste.md-5.net/kaquwunaro
- Server log:  https://mclo.gs/Yv9B0fY

**Comment by Insprill** [comment] 2021-07-29 20:25
Duplicate of #1916

**Closed by Insprill** 2021-07-29 20:25 UTC
Labels: Resolution: Duplicate
