### ISSUE TITLE
mcMMO Double Drops doesn't work with Telepathy (use-experimental-block-breaking: true)

### ISSUE THREAD

**Issue by WhatsTheBadNews** [GC-spigot/AdvancedEnchantments#2019] opened 2021-05-29 09:42 UTC
## Details

**Describe the bug**
When you use a pickaxe enchanted with Telepathy, mcMMO's Double Drops from the Mining Skill does not work.

I've only tested with `use-experimental-block-breaking: true`, though I am not sure if that makes a difference.

**To Reproduce**
1.) Set `use-experimental-block-breaking` to true
2.) Install mcMMO
3.) `/mmoedit [player] Mining 1000` (Setting your mining level to 1000 should ensure that 100% of ores mined are supposed to be double drops)
4.) Hold a pickaxe and do `/ae enchant Telepathy 4`
5.) Find some diamond ores. (They must be natural, played placed diamonds will not work). If you mine them with a regular Diamond Pickaxe, each ore will give you 2 Diamonds because of mcMMO's Double Drops. However, if you mine them with the Pickaxe that has Telepathy, each Diamond Ore mined will only give you one Diamond.

## Server Information
- "/ae plinfo" link: https://paste.md-5.net/yefonotavu
- Server log: https://gist.github.com/WhatsTheBadNews/0996a6819b5c3aebdae5e8b6553378a4

**Comment by Insprill** [comment] 2021-05-30 01:25
Duplicate of #1594

**Closed by Insprill** 2021-05-30 01:25 UTC
Labels: Resolution: Duplicate
