### ISSUE TITLE
Health Boost seems to be inverted (Now replicable)

### ISSUE THREAD

**Issue by FighterPilot50** [GC-spigot/AdvancedEnchantments#2102] opened 2021-07-01 07:57 UTC
## Details

**Describe the bug**
Health Boost status effects seem to be inverted - positive values merely decrease health, but health is still recoverable, like instant damage. Happens whether I do /effect or if it comes from an enchantment. I'm not 100% sure this is caused by AE.

**To Reproduce**
I don't know how or why this happened, and therefore don't know how to reproduce. AE version was 8.3.4 but I updated to 8.4.0 and nothing changed. (EDIT - In comments)

**Screenshots / Video**
![image](https://user-images.githubusercontent.com/77595823/124087397-f558a200-da1f-11eb-9ed1-e5c8fd7febcd.png)
I don't know if this'll help, but here's the health boost enchantment configuration.

## Server Information
- "/ae plinfo" link: https://paste.md-5.net/sixumobana
- Server log: https://mcpaste.io/1c4daf6b68136085

**Comment by Insprill** [comment] 2021-07-01 16:23
Is this still an issue on 8.4.0? I can't reproduce it - works fine

**Comment by FighterPilot50** [comment] 2021-07-01 23:24
> Is this still an issue on 8.4.0? I can't reproduce it - works fine

This might be a problem with my server, as It doesn't seem directly connected to AE - except I have no other idea where it could've originated from. Seems like a completely unique problem, I can't find any other reports of a similar issue.

**Comment by Starkenz** [comment] 2021-07-02 05:33
> Is this still an issue on 8.4.0? I can't reproduce it - works fine

https://youtu.be/G1lEo5RHVAg

**Comment by FighterPilot50** [comment] 2021-07-04 02:07
> https://youtu.be/G1lEo5RHVAg

> Is this still an issue on 8.4.0? I can't reproduce it - works fine

I think I found the issue, it seems to be MythicMobs / MythicLib, I'm not sure if it's a compatibility issue or a bug with the Mythic plugins themselves. At least now this issue should be reproduceable!

**Comment by FighterPilot50** [comment] 2021-07-04 02:12
> > https://youtu.be/G1lEo5RHVAg
> 
> > Is this still an issue on 8.4.0? I can't reproduce it - works fine
> 
> I think I found the issue, it seems to be MythicMobs / MythicLib (latest versions), I'm not sure if it's a compatibility issue or a bug with the Mythic plugins themselves. At least now this bug should be reproduceable!

**Comment by Insprill** [comment] 2021-07-07 01:57
I can't get MythicLib to enable but the issue still doesn't happen to me with MythicMobs 4.12.0 installed

**Comment by FighterPilot50** [comment] 2021-07-07 13:58
> I can't get MythicLib to enable but the issue still doesn't happen to me with MythicMobs 4.12.0 installed

I'm pretty sure MythicLib is a dependency, so if you can't get it to enable I don't think MythicMobs will enable either, was MythicMobs working when you tested it?

**Comment by Insprill** [comment] 2021-07-07 15:59
It enabled fine without the lib

**Comment by Insprill** [comment] 2021-07-17 03:13
Going to close this as I don't see how it can be related to AE since all it's doing is giving a potion effect. If you find evidence that it is in fact AE causing this issue feel free to comment and I'll reopen this or you can create a new issue.

**Closed by Insprill** 2021-07-17 03:13 UTC
Labels: Bug: Can't Reproduce, Resolution: Denied
