### ISSUE TITLE
Server Crash when right clicking a book - AE 8.6.4

### ISSUE THREAD

**Issue by LordMick14** [GC-spigot/AdvancedEnchantments#2284] opened 2021-08-16 16:35 UTC
## Details

**Describe the bug**
In version 8.6.4, if you hold a ae book in your hand and press right click and mess a bit with it, 10 seconds after, you get a paper watchdog error and the server crash. I tested with the default config of 8.6.4 and it does it.

**To Reproduce** 
1 - /ae givebook,
Get a ae book

2 - You hold it and press right click

3 - Look console and enjoy.

**Temporary solution for those who have this problem:**
Get back to 8.6.2, the time that they fix this issue.

## Server Information
https://paste.md-5.net/ahecexixot
https://hastebin.com/itelododuv.md

**Comment by TheLeby9** [comment] 2021-08-16 16:47
This might have a relation with the issue posted before by me about the firework_star unopened enchants becoming books after i updated the plugin. i tried making them back to fireworkstar in groups.yml and also caused crashes still.  #2283

**Comment by Insprill** [comment] 2021-08-16 17:09
Duplicate of #2254 (Fixed in the next update)

**Closed by Insprill** 2021-08-16 17:09 UTC
Labels: Resolution: Duplicate
