### ISSUE TITLE
BLACK-SCROLL DON'T REMOVE ALL CUSTOMENCHANT

### ISSUE THREAD

**Issue by mk9395** [GC-spigot/AdvancedEnchantments#4249] opened 2024-05-04 07:24 UTC
### Describe the bug

I'm having an error when using black-scroll, the problem is I limit the max enchant to 5, and can use slot expansion up to 10!
But when using black-scroll to get back enchants, I can only get a maximum of 5 random enchants, and the enchants I pressed and extended use cannot be gotten!
The system says there are no enchants to remove, even though my item still has enchants!

### How to reproduce

You just need to install max enchant and use more slot gems!
Then enchant exceeds the max limit (For example default 5, you only need to enchant 6)
Then using black-scroll, you can only remove 5, even though the item has 6 enchants

### "/ae plinfo" link

https://paste.md-5.net/qamuvilize

**Comment by ThomasWega** [comment] 2024-05-05 11:20
Duplicate of https://github.com/GC-spigot/AdvancedEnchantments/issues/4226. Will be fixed next update. Big apologies

**Closed by ThomasWega** 2024-05-05 11:20 UTC
Labels: Bug: Unconfirmed
