### ISSUE TITLE
Add NoCheatPlus compatibility

### ISSUE THREAD

**Issue by Leomelonseeds** [GC-spigot/AdvancedEnchantments#316] opened 2019-01-28 05:53 UTC
Currently NoCheatPlus checks prevent many enchantments from working. If you could hook into it's API and disable the checks during BlockBreakEvent specifically, that would be great.

Thanks for considering, and I hope you have a nice day.

**Comment by GC-spigot** [comment] 2019-02-05 14:47
Duplicate of #282

**Closed by GC-spigot** 2019-02-05 14:47 UTC
