### ISSUE TITLE
Slab with water. Water dissapears on slab break when using TP_DROPS/SMELT

### ISSUE THREAD

**Issue by Ecilpse** [GC-spigot/AdvancedEnchantments#4440] opened 2024-07-09 14:10 UTC
### Describe the bug

1. when break farmlands with TP_DROPS tools, it given FARM_LAND block.
(it given dirt block in previous version. and FARM_LAND block can't gain in survival environment)

2. when player break slab block with filled with water, water was disappeared.

### How to reproduce

i uploaded video.

### Screenshots / Videos

1. farmland
https://github.com/GC-spigot/AdvancedEnchantments/assets/25452835/702d7be9-168a-4a6e-8a20-4f51dbfc808e

2. water
https://github.com/GC-spigot/AdvancedEnchantments/assets/25452835/668f38e6-e40f-48ee-b141-8169687caaf5

### "/ae plinfo" link

https://paste.md-5.net/kumoqutiwo

**Comment by ThomasWega** [comment] 2024-07-12 13:13
1. will be fixed next update. (Can't reproduce now, but I've done some changes already)
2. Confirmed bug

**Comment by ThomasWega** [comment] 2024-08-04 12:11
Should be fixed in the next update

**Closed by ThomasWega** 2024-08-04 12:11 UTC
Labels: Priority: Low, Bug: Confirmed
