### ISSUE TITLE
Killaura bug

### ISSUE THREAD

**Issue by illudota** [GC-spigot/AdvancedEnchantments#2357] opened 2021-09-18 17:00 UTC
### Describe the bug

knew this since a player reported mobs were immortal, then so i tried giving myself a kill aura sword only with sharp 5, kill aura doesn't work and once u use it, u could damge mobs for a while, but after that, you cant deal damage anymore nor can attack them. it feels like they're in creative mode

### How to reproduce

just get kill aura sword, try on some mobs for quite some time and u will see.

### Screenshots / Videos

https://imgur.com/a/wa3vx69

### "/ae plinfo" link

https://paste.md-5.net/zecaguqagi

### Server Log

https://mcpaste.io/89c0646c952b63c1

**Comment by illudota** [comment] 2021-09-18 17:45
Kill aura night owl iniquisitive word error
![Uploading 1744C3DF-0BD0-43CA-9A85-D7D00B5D0EF6.png…]()

**Comment by Insprill** [comment] 2021-09-18 18:44
Duplicate of #2012

**Closed** 2021-09-18 18:44 UTC
Labels: Resolution: Duplicate
