### ISSUE TITLE
Server crash anvil

### ISSUE THREAD

**Issue by iBuseWinner** [GC-spigot/AdvancedEnchantments#2255] opened 2021-08-11 15:48 UTC
## Details

**Describe the bug**
When someone using anvil

**To Reproduce** 
idk what is that enchantment or what is it...

## Server Information
- "/ae plinfo" link: https://paste.md-5.net/uqipexesud
- Server log: https://mcpaste.io/f0f407df7acba6e5

**Comment by Insprill** [comment] 2021-08-11 19:10
Duplicate of #2254 - same cause

**Closed** 2021-08-11 19:10 UTC
Labels: Resolution: Duplicate
