### ISSUE TITLE
Smelt Doesnt work with fortune 1.18

### ISSUE THREAD

**Issue by Bradayy** [GC-spigot/AdvancedEnchantments#2710] opened 2022-03-26 15:13 UTC
### Describe the bug

when i mine iron ore with a fortune pick i get 1-3 iron
but when i add my autosmelt
i only get 1
when i mine 5 iron without i can get up to 15, but with autosmelt I only get 5
Please fix

autosmelt:
  display: '%group-color%AutoSmelt'
  description: 'Smelts Ores'
  applies-to: 'tools'
  group: 'SIMPLE'
  type: 'MINING'
  applies:
    - 'ALL_PICKAXE'
    - 'ALL_SPADE'
  settings:
    removeable: false
  levels:
    '1':
      chance: 100
      effects:
        - 'SMELT %attacker%'

### How to reproduce

Copy the smelt enchant that I made and do the test yourself

### "/ae plinfo" link

https://paste.md-5.net/uwajeguduj

**Comment by DuneSciFye** [comment] 2022-03-27 12:16
Duplicate of #2709

**Comment by Burchard36** [comment] 2022-03-29 22:29
This will be fixed next bug patch update.

Video: https://youtu.be/smzXnm9UlOY

**Comment by Burchard36** [comment] 2022-03-30 11:01
This is fixed in version 8.9.9, please wait for this to be upload to spigot/ae.net, allow a couple hours for this, have a nice day!

**Closed by Burchard36** 2022-03-30 11:01 UTC
Labels: Type: Enchant Conflict, Bug: Confirmed, Resolution: Accepted
