### ISSUE TITLE
Some console error

### ISSUE THREAD

**Issue by illudota** [GC-spigot/AdvancedEnchantments#2720] opened 2022-04-02 15:03 UTC
### Describe the bug

It happens with ADD DURABILITY I think

### How to reproduce

ADD Durability CE

### Screenshots / Videos

https://pastebin.com/e0FuuNkG

Pic of durabiliy error in discord:
https://media.discordapp.net/attachments/377152090088275968/959827741044260894/unknown.png

### "/ae plinfo" link

https://paste.md-5.net/ejicihoyoz

### Server Log

https://mcpaste.io/a3707ac72c1680ca

**Comment by Burchard36** [comment] 2022-04-03 04:08
Duplicate of #2719 (Its the same error)

Read my latest comment on that github issue

**Closed by Burchard36** 2022-04-03 04:08 UTC
Labels: Bug: Unconfirmed
