### ISSUE TITLE
[Issue] TRENCH Bugs

### ISSUE THREAD

**Issue by ZeddyOG** [GC-spigot/AdvancedEnchantments#939] opened 2020-04-12 21:17 UTC
**Describe the bug**
* When used on leaves it will gives the leaves to you and doesn't just break them (Like the tool has silk touch or is shears)
* When using a material that normally shouldn't be able to obtain things, it can obtain them. (Example: Wooden Pickaxe mining and getting diamond)
* Along with the bug reported above, mining diamond ore with anything you normally couldn't gives diamond ore back (Like it was a iron/diamond pickaxe with silk touch)
* When you have 2 slabs stack on top of each other they will only give 1 back
* Items that normally have a chance to give more than one only give one (i.e Melons, Glowstone + Bookshelves)
* When breaking mushroom stem it gives back a mushroom stem (Like the tool has silk touch)
* Breaking snow and snow blocks gives back itself (Shouldn't drop anything unless broken with a shovel (gives snowballs))
* When stacking sea pickles over 1 in a block (You can do this for up to 4 sea pickles) it will only return 1
* When breaking turtle eggs it will give 1 back (It shouldn't give any back when broken)
* When breaking coral (not coral blocks) it will give it back (Like the pickaxe has silk touch)
* When breaking a banner with a design on it, it will remove the design and give back the default colored banner
* When breaking custom skulls it will reset them back to default steve heads
* When placing a bed horizontal (North-South) it will duplicate the bed on break and give 2 (I will provide a video of this)
* When breaking a full composter it should give 1 bone meal but doesnt

**To Reproduce**
Use TRENCH on a pickaxe and mine any of the items I listed

**Screenshots / Video**
Bed Glitch - https://www.youtube.com/watch?v=cQrLrOrRuww

**Server Information (please complete the following information):**
 - Minecraft Version: Paper 1.15.2
- Plugin Version: 7.5.0-Pre1

**Comment by FeroxDrood** [comment] 2020-04-13 16:46
All these are happening to me too.

**Comment by GC-spigot** [comment] 2020-04-13 20:07
Most of these are caused by new materials not supported by AE which is being worked on, everything else will be fixed within next 2 versions

**Comment by FeroxDrood** [comment] 2020-04-15 11:27
I'll also add when mining any sort of sub stone such as diorite or andersite it just gives normal silktouched stone

**Comment by ZeddyOG** [comment] 2020-04-17 07:37
Updated to plugin version 7.3.5 (Tested all of them again and removed the ones that have been patched)

**Comment by GC-spigot** [comment] 2020-04-17 20:47
Most are caused due to AE not supporting new materials format, it's because of how spigot forces materials to work - it's either no new materials or 1.8 support dropped, I'm working on fixing it which should fix all these issues, fixing as many as I can now but full 'fix' is coming soon

**Comment by FeroxDrood** [comment] 2020-04-17 22:17
> Most are caused due to AE not supporting new materials format, it's because of how spigot forces materials to work - it's either no new materials or 1.8 support dropped, I'm working on fixing it which should fix all these issues, fixing as many as I can now but full 'fix' is coming soon

Thank youuu GC, sorry if this is pushy but any ETA on the fix coming soon :D

**Comment by ZeddyOG** [comment] 2020-04-17 22:53
> Most are caused due to AE not supporting new materials format, it's because of how spigot forces materials to work - it's either no new materials or 1.8 support dropped, I'm working on fixing it which should fix all these issues, fixing as many as I can now but full 'fix' is coming soon

I'm aware, I am just going to make sure to keep it updated when you fix one or more of them so you know that they are for sure patched.

**Comment by GC-spigot** [comment] 2020-04-18 17:20
> > Most are caused due to AE not supporting new materials format, it's because of how spigot forces materials to work - it's either no new materials or 1.8 support dropped, I'm working on fixing it which should fix all these issues, fixing as many as I can now but full 'fix' is coming soon
> 
> Thank youuu GC, sorry if this is pushy but any ETA on the fix coming soon :D

Within a week

**Comment by FeroxDrood** [comment] 2020-04-20 15:52
As of 7.3.9 here is the latest update from the list I have just tested each reported bug.

The X's are still broken and the #'s are fixed.

X Mining Granite, Diorite, + Andesite (Normal + Polished) drop STONE
# When used on leaves it will gives the leaves to you and not just break them (Without Silk Touch)
X Dark Oak Log gives Acacia Logs instead
XAll other wood types (Other than Dark Oak + Acacia) logs give Oak
X All wood planks give back oak planks
X On newer version the "Wood" block (Solid log) of Dark Oak gives normal acacia logs
X All other "Wood" block (Solid logs) give normal oak logs
# The effect doesn't work at all on stripped logs (It does function on stripped wood properly)
X Colored Blocks (i.e Green Concrete) gives White back (Tested on Concrete, Wool, Carpet, Terracotta, Concrete Powder, Stained Glass, + Stained Glass Panes)
X When used on an item such as an axe, it can mine + drop blocks that should only be obtainable with a pickaxe (Stone/Diamond Ore)
X When using it on a lower tier pickaxe, I was able to mine blocks that would require a higher tier pickaxe
# When breaking any leaf (other than dark oak + acacia) it gives OAK leaves
X When breaking dark oak leaves it gives Acacia leaves
X Forms of sandstone (i.e Chiseled, Smooth, + Cut) give normal sandstone
X Red sand gives normal sand back
X Forms of red sandstone (i.e Chiseled, Smooth, + Cut) give normal red sandstone
X Cobblestone, stonebrick, netherbrick, sandstone, + quartz slabs turn into Smooth Stone slabs
X All wood slabs give back oak slabs
X When you have 2 slabs stack on top of each other they will only give 1 back
X Mossy cobblestone walls turn into normal cobblestone walls
X All forms of stonebrick (i.e Mossy, Chiseled, + Cracked) turn into normal stonebrick
X Wet sponge gives back a normal sponge
X Lapis Lazuli Ore only gives 4 even if you have fortune
X Smooth sandstone blocks + smooth stone blocks drops 1 smooth stone slab
# Ice gives back ice (Like the pickaxe has silk touch)
X Items that normally have a chance to give more than one only give one (i.e Melons + Glowstone)
X Forms of Quartz (Chiseled + Pillar) give back normal quartz blocks
X When breaking brown mushroom block + red mushroom block you get nothing back (Error fixed)
X When breaking mushroom stem it gives back a brown mushroom block
X Breaking snow gives back snow (Like the pickaxe has silk touch) (Shouldn't drop anything unless broken with silk touch or a shovel (gives snowballs))
X Breaking snow blocks gives back itself (Like the pickaxe has silk touch) (Shouldn't drop anything unless mined with silktouch or a shovel (gives snowballs))
X Breaking a chipped or damage anvil gives back a normal anvil

**Comment by FeroxDrood** [comment] 2020-04-28 19:06
As of 7.5.0-Pre1 this is the updated list from this post :) 

The X's are still broken and the O's are fixed.

Also there were 0 console errors when testing all of these!

O Mining Granite, Diorite, + Andesite (Normal + Polished) drop STONE
O Dark Oak Log gives Acacia Logs instead
O All other wood types (Other than Dark Oak + Acacia) logs give Oak
O All wood planks give back oak planks
O On newer version the "Wood" block (Solid log) of Dark Oak gives normal acacia logs
O All other "Wood" block (Solid logs) give normal oak logs
O Colored Blocks (i.e Green Concrete) gives White back (Tested on Concrete, Wool, Carpet, Terracotta, Concrete Powder, Stained Glass, + Stained Glass Panes)
**X When using it on a lower tier pickaxe, I was able to mine blocks that would require a higher tier pickaxe**
O When breaking dark oak leaves it gives Acacia leaves
O Forms of sandstone (i.e Chiseled, Smooth, + Cut) give normal sandstone
O Red sand gives normal sand back
O Forms of red sandstone (i.e Chiseled, Smooth, + Cut) give normal red sandstone
O Cobblestone, stonebrick, netherbrick, sandstone, + quartz slabs turn into Smooth Stone slabs
O All wood slabs give back oak slabs
**X When you have 2 slabs stack on top of each other they will only give 1 back**
O Mossy cobblestone walls turn into normal cobblestone walls
O All forms of stonebrick (i.e Mossy, Chiseled, + Cracked) turn into normal stonebrick
O Wet sponge gives back a normal sponge
**X Lapis Lazuli Ore only gives 1 even if you have fortune**
O Smooth sandstone blocks + smooth stone blocks drops 1 smooth stone slab
**X Items that normally have a chance to give more than one only give one (i.e Melons + Glowstone)**
O Forms of Quartz (Chiseled + Pillar) give back normal quartz blocks
O When breaking brown mushroom block + red mushroom block you get nothing back (Error fixed)
O When breaking mushroom stem it gives back a brown mushroom block
O Breaking snow gives back snow (Like the pickaxe has silk touch) (Shouldn't drop anything unless broken with silk touch or a shovel (gives snowballs))
**X Breaking snow blocks gives back itself (Like the pickaxe has silk touch) (Shouldn't drop anything unless mined with silktouch or a shovel (gives snowballs))**
O Breaking a chipped or damage anvil gives back a normal anvil

**Comment by ZeddyOG** [comment] 2020-04-28 19:15
I'm updating it to 7.5.0-Pre1 and reporting new bugs currently.

**Comment by GC-spigot** [comment] 2020-05-01 18:34
More progress - quite a few fixes are coming to possibly fully patch up this list

**Closed by GC-spigot** 2020-05-01 18:34 UTC
Labels: important, issue
