### ISSUE TITLE
XP set to 0 with /e

### ISSUE THREAD

**Issue by 69werdna** [GC-spigot/AdvancedEnchantments#2122] opened 2021-07-05 13:32 UTC
**Describe the bug**
When a player typed /e, on a very rare occasion, the player XP will be set to 0,

**To Reproduce**
No idea how to reproduce...

**Screenshots / Video**
https://pastebin.com/A050g5xN

## Server Information
https://paste.md-5.net/iraxiguxex
https://pastebin.com/A050g5xN

**Comment by Insprill** [comment] 2021-07-07 01:02
When they typed it or when they bought something? If it's just when they typed it that's not possible

**Comment by 69werdna** [comment] 2021-07-07 10:26
> When they typed it or when they bought something? If it's just when they typed it that's not possible

Player is unsure what they might have clicked, claiming that there was a cat sitting on his mouse when that happened. What about the error/warn I'm getting though, does that provide any information?

**Comment by Insprill** [comment] 2021-07-07 16:00
No unfortunately it doesn't. I'm gonna close this since there isn't a way to reproduce it. If you can find a reliable way to reproduce it feel free to comment on this or open a new issue.

**Closed** 2021-07-07 16:00 UTC
Labels: Resolution: Not a Bug
