### ISSUE TITLE
Factions Land support for Lava/Water walker enchant 

### ISSUE THREAD

**Issue by Thefluffypvper1** [GC-spigot/AdvancedEnchantments#2321] opened 2021-08-29 09:32 UTC
## Details

**Describe the bug**
When using the Lava/Water enchant it turns lava/walker into obsidian which courses the water to stop flowing for a couple of seconds, this is a major problem with faction land were people have cobblestone walls with water above it, people can walk on each wall stopping water from following to shoot cannons at the dry wall.

**To Reproduce** 
Use a FactionsUUID factions plugin claim faction land example /f claim 2 Make cobblestone walls with water above it, go on a alt and walk over them with  waterwalker boots, make sure the alt isn't in the same faction, try flint a tnt as you drop the water to brake the dry wall when it should of been watered.

**Screenshots / Video**
https://www.youtube.com/watch?v=ehl4d3B2wik&ab_channel=Doooch

## Server Information
- https://paste.md-5.net/woqotusimu
- Server log: https://paste.helpch.at/ogexorajiw.md

**Comment by Insprill** [comment] 2021-08-29 11:23
Duplicate of #1936

**Closed by Insprill** 2021-08-29 11:23 UTC
Labels: Resolution: Duplicate
