### ISSUE TITLE
[Issue] Telepathy is still not working, shulkers are losing items

### ISSUE THREAD

**Issue by naikyy** [GC-spigot/AdvancedEnchantments#1716] opened 2021-02-26 19:16 UTC
When you dig the shulker with items in it by enchant Telepathy the Shulker lose all items in it.

**Server Information:**
- Server Version: Purpur [newest build]
- Plugin Version: pre20.1

**Comment by Insprill** [comment] 2021-02-28 18:27
I was not able to reproduce this, with a netherite pickaxe & telepathy, the shulker box didn't lose any of its items. Can you try with pre 20.2? If it still happens, please send what all enchants you have on the item you are breaking the shulkerbox with

**Comment by naikyy** [comment] 2021-02-28 22:57
I've tried it once again. It is doing with combination Silk Touch and Telepathy. Yep, thats broken.

**Comment by Sikatsu** [comment] 2021-03-01 15:15
It works for me with the detonate / trench enchantment, despite the blacklist.

**Comment by Insprill** [comment] 2021-03-01 18:54
Fixed in next update

**Closed by Insprill** 2021-03-01 18:54 UTC
Labels: issue
