### ISSUE TITLE
NoCheatPlus Error

### ISSUE THREAD

**Issue by downboy** [GC-spigot/AdvancedEnchantments#375] opened 2019-03-12 20:13 UTC
Hallo,

I don't use NocheatPlus on my server because I use Spartan Anticheat. But when I use an enchantment I get the following error! I hope you can fix it!

`[21:09:25 ERROR]: Could not pass event BlockBreakEvent to AdvancedEnchantments v5.3.7
java.lang.NoClassDefFoundError: fr/neatmonster/nocheatplus/hooks/NCPExemptionManager
at n3kas.ae.hooks.anticheat.ExemptPlayer.a(ExemptPlayer.java:26) ~[?:?]
at n3kas.ae.effectsreader.RunnableEffect.c(RunnableEffect.java:969) ~[?:?]
at n3kas.ae.effectsreader.RunnableEffect.a(RunnableEffect.java:108) ~[?:?]
at n3kas.ae.enchanthandler.ProcessEnchantment.a(ProcessEnchantment.java:225) ~[?:?]
at n3kas.ae.enchanthandler.ProcessEnchantment.a(ProcessEnchantment.java:120) ~[?:?]
at n3kas.ae.enchanttypes.MINING.lambda$0(MINING.java:61) ~[?:?]
at java.util.ArrayList.forEach(ArrayList.java:1257) ~[?:1.8.0_192]
at n3kas.ae.enchanttypes.MINING.a(MINING.java:56) ~[?:?]
at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor1851.execute(Unknown Source) ~[?:?]
at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:70) ~[patched_1.12.2.jar:git-Paper-1606]
at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78) ~[patched_1.12.2.jar:git-Paper-1606]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[patched_1.12.2.jar:git-Paper-1606]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:513) ~[patched_1.12.2.jar:git-Paper-1606]
at net.minecraft.server.v1_12_R1.PlayerInteractManager.breakBlock(PlayerInteractManager.java:322) ~[patched_1.12.2.jar:git-Paper-1606]
at net.minecraft.server.v1_12_R1.PlayerInteractManager.a(PlayerInteractManager.java:193) ~[patched_1.12.2.jar:git-Paper-1606]
at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:920) ~[patched_1.12.2.jar:git-Paper-1606]
at net.minecraft.server.v1_12_R1.PacketPlayInBlockDig.a(SourceFile:40) ~[patched_1.12.2.jar:git-Paper-1606]
at net.minecraft.server.v1_12_R1.PacketPlayInBlockDig.a(SourceFile:10) ~[patched_1.12.2.jar:git-Paper-1606]
at net.minecraft.server.v1_12_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:14) ~[patched_1.12.2.jar:git-Paper-1606]
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_192]
at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_192]
at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46) ~[patched_1.12.2.jar:git-Paper-1606]
at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:850) ~[patched_1.12.2.jar:git-Paper-1606]
at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:423) ~[patched_1.12.2.jar:git-Paper-1606]
at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:774) ~[patched_1.12.2.jar:git-Paper-1606]
at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:666) ~[patched_1.12.2.jar:git-Paper-1606]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_192]`

**Comment by Leomelonseeds** [comment] 2019-03-14 01:08
Same problem here. I believe the issue is that the AdvancedEnchantments is being forced to hook into NCP, even when NCP is not installed. A temporary fix for this problem would be to install NoCheatPlus.

**Comment by GC-spigot** [comment] 2019-03-20 19:15
Fixed! It mistaked Spartan for NoCheatPlus.

**Closed by GC-spigot** 2019-03-20 19:15 UTC
