### ISSUE TITLE
Soulbound item dupe if we die by warden SonicBoom

### ISSUE THREAD

**Issue by MoGGaming** [GC-spigot/AdvancedEnchantments#3732] opened 2023-10-20 17:35 UTC
### Describe the bug

die by warden SonicBoom while holding soulbound item

### How to reproduce

die by warden SonicBoom while holding soulbound item

### "/ae plinfo" link

https://paste.md-5.net/uceduzofoy

**Comment by ThomasWega** [comment] 2023-10-20 19:34
duplicate of https://github.com/GC-spigot/AdvancedEnchantments/issues/3713

**Closed by ThomasWega** 2023-10-20 19:34 UTC
Labels: Bug: Unconfirmed
