### ISSUE TITLE
[Issue] Permanent potion effect

### ISSUE THREAD

**Issue by Weslly96** [GC-spigot/AdvancedEnchantments#1770] opened 2021-03-11 15:52 UTC
When creating the following enchantment, instead of applying the effect with a duration of 100 ticks, the effect will be created permanent

desesperacion:
  display: '%group-color%Desesperacion'
  description: 'Otorga lentitud en área'
  applies-to: 'Armor'
  group: 'ELITE'
  type: 'SHIFT'
  applies:
    - 'ALL_ARMOR'
  levels:
    '1':
      chance: 100
      cooldown: 120
      effects:
        - 'POTION:SLOWNESS:2:100 <aoe> radius=10 target=all </aoe>'
        - 'POTION:GLOWING:0:100 <aoe> radius=10 target=all </aoe>'

**Comment by Insprill** [comment] 2021-03-30 01:59
Duplicate of #1671

**Closed by Insprill** 2021-03-30 01:59 UTC
Labels: Resolution: Duplicate
