### ISSUE TITLE
Permission not working (ae.limit.number) 

### ISSUE THREAD

**Issue by LuluxClient** [GC-spigot/AdvancedEnchantments#1857] opened 2021-04-08 15:26 UTC
## Details

**Describe the bug**

If you give someone the permission ae.limit.4 for example and in your config the limit is at 2 the player will only be able to put 2 enchants on an item
**To Reproduce**

Give the permission "ae.limit.4" and put the max slot in the config to 2 and try
**Screenshots / Video**

Don't need 

## Server Information
- "/ae plinfo" link: 
- Server log: 
Paper 1.8.8
8.0.0-Pre22.5

**Comment by Insprill** [comment] 2021-04-13 06:53
What permissions plugin are you using? I was not able to reproduce this.

**Comment by Starkenz** [comment] 2021-04-13 10:54
@LuluxClient You just have to put permissions like this. Consider you're in vip group and vip group has ae.limit.5. And after that in mvp group(consider you have to make limit.6) you have to type your permissions like this:
    - -ae.limit.5
    - ae.limit.6

**Comment by Insprill** [comment] 2021-04-13 11:03
So is it only if they it multiple times with different amounts?

**Comment by Starkenz** [comment] 2021-04-13 11:31
> So is it only if they it multiple times with different amounts?

Yes, if its like multiplied like on every group:
VIP:
- ae.limit.5
MVP:
- ae.limit.6 //It will not work. (Only ae.limit.5 will work if MVP inherited vip group)

To work like this you should write like this:
VIP:
- ae.limit.5
MVP:
- -ae.limit.6 // - is denying permission
- ae.limit.6

**Comment by LuluxClient** [comment] 2021-04-13 13:42
> What permissions plugin are you using? I was not able to reproduce this.

Luckperm

**Comment by LuluxClient** [comment] 2021-04-13 13:43
> @LuluxClient You just have to put permissions like this. Consider you're in vip group and vip group has ae.limit.5. And after that in mvp group(consider you have to make limit.6) you have to type your permissions like this:
> mvp:
> - -ae.limit.5
> - ae.limit.6

I only have 1 group that has this permission

**Comment by LuluxClient** [comment] 2021-04-13 23:03
After doing some testing still nothing

**Comment by Insprill** [comment] 2021-04-15 15:21
Just tested this again. I gave my alt ae.limit.1 2 3 and 4 adding them on top of each other with it set to 1 in my config. worked as intended. Looking at the code behind the permission, I don't see how it would even happen. it just takes the highest one

**Comment by LuluxClient** [comment] 2021-04-17 12:51
> Just tested this again. I gave my alt ae.limit.1 2 3 and 4 adding them on top of each other with it set to 1 in my config. worked as intended. Looking at the code behind the permission, I don't see how it would even happen. it just takes the highest one

Update (from discord) 


The bug is just a visual bug, the display on items is the thing that is bugged. 

For example The limit is 3 but you have a limit of 5, on the item if you place 5 enchantements it will display has "-2 enchant slots"

**Comment by LuluxClient** [comment] 2021-04-17 12:51
![image](https://user-images.githubusercontent.com/62576432/115113802-609be780-9f8c-11eb-9291-245df3857aad.png)

**Comment by Insprill** [comment] 2021-09-16 07:18
Going to close this as #1896 is more specific.

**Closed by Insprill** 2021-09-16 07:18 UTC
Labels: Bug: Can't Reproduce
