### ISSUE TITLE
Could not pass event EntityDamageByEntityEvent to AdvancedEnchantments v8.5.2

### ISSUE THREAD

**Issue by antibitcoin** [GC-spigot/AdvancedEnchantments#2173] opened 2021-07-20 19:31 UTC
## Details

**Describe the bug**
Spam on command and lag
[21:25:47 ERROR]: Could not pass event EntityDamageByEntityEvent to AdvancedEnchantments v8.5.2
java.lang.ClassCastException: class org.bukkit.craftbukkit.v1_17_R1.entity.CraftEnderDragon cannot be cast to class org.bukkit.entity.Projectile (org.bukkit.craftbukkit.v1_17_R1.entity.CraftEnderDragon and org.bukkit.entity.Projectile are in unnamed module of loader 'app')
        at net.advancedplugins.ae.enchanthandler.enchanttypes.DEFENSE_MOB.activate(DEFENSE_MOB.java:72) ~[?:?]
        at net.advancedplugins.ae.enchanthandler.enchanttypes.DEFENSE_MOB.playerHitPlayer(DEFENSE_MOB.java:47) ~[?:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor1080.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.17.1.jar:git-Paper-119]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.17.1.jar:git-Paper-119]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.17.1.jar:git-Paper-119]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:624) ~[patched_1.17.1.jar:git-Paper-119]
        at org.bukkit.craftbukkit.v1_17_R1.event.CraftEventFactory.callEvent(CraftEventFactory.java:242) ~[patched_1.17.1.jar:git-Paper-119]
        at org.bukkit.craftbukkit.v1_17_R1.event.CraftEventFactory.callEntityDamageEvent(CraftEventFactory.java:1100) ~[patched_1.17.1.jar:git-Paper-119]
        at org.bukkit.craftbukkit.v1_17_R1.event.CraftEventFactory.handleEntityDamageEvent(CraftEventFactory.java:986) ~[patched_1.17.1.jar:git-Paper-119]
        at org.bukkit.craftbukkit.v1_17_R1.event.CraftEventFactory.handleEntityDamageEvent(CraftEventFactory.java:942) ~[patched_1.17.1.jar:git-Paper-119]
        at org.bukkit.craftbukkit.v1_17_R1.event.CraftEventFactory.handleLivingEntityDamageEvent(CraftEventFactory.java:1132) ~[patched_1.17.1.jar:git-Paper-119]
        at net.minecraft.world.entity.LivingEntity.damageEntity0(LivingEntity.java:2041) ~[?:?]
        at net.minecraft.world.entity.player.Player.damageEntity0(Player.java:1011) ~[?:?]
        at net.minecraft.world.entity.LivingEntity.hurt(LivingEntity.java:1350) ~[?:?]
        at net.minecraft.world.entity.player.Player.hurt(Player.java:918) ~[?:?]
        at net.minecraft.server.level.ServerPlayer.hurt(ServerPlayer.java:998) ~[?:?]
        at net.minecraft.world.entity.boss.enderdragon.EnderDragon.knockBack(EnderDragon.java:441) ~[?:?]
        at net.minecraft.world.entity.boss.enderdragon.EnderDragon.aiStep(EnderDragon.java:313) ~[?:?]
        at net.minecraft.world.entity.LivingEntity.tick(LivingEntity.java:2880) ~[?:?]
        at net.minecraft.world.entity.Mob.tick(Mob.java:389) ~[?:?]
        at net.minecraft.server.level.ServerLevel.tickNonPassenger(ServerLevel.java:903) ~[?:?]
        at net.minecraft.world.level.Level.guardEntityTick(Level.java:869) ~[?:?]
        at net.minecraft.server.level.ServerLevel.lambda$tick$5(ServerLevel.java:600) ~[?:?]
        at net.minecraft.world.level.entity.EntityTickList.forEach(EntityTickList.java:54) ~[patched_1.17.1.jar:git-Paper-119]
        at net.minecraft.server.level.ServerLevel.tick(ServerLevel.java:581) ~[?:?]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1553) ~[patched_1.17.1.jar:git-Paper-119]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:479) ~[patched_1.17.1.jar:git-Paper-119]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1406) ~[patched_1.17.1.jar:git-Paper-119]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1188) ~[patched_1.17.1.jar:git-Paper-119]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316) ~[patched_1.17.1.jar:git-Paper-119]
        at java.lang.Thread.run(Thread.java:831) [?:?]
[21:25:48 INFO]: 1
[21:25:48 INFO]: 2
[21:25:48 INFO]: 1
[21:25:48 INFO]: 1
[21:25:48 INFO]: 2
[21:25:48 INFO]: 2
[21:25:48 INFO]: 2
[21:25:48 INFO]: 1
[21:25:48 INFO]: 1
[21:25:48 INFO]: 1
[21:25:48 INFO]: 2
[21:25:48 INFO]: 2
[21:25:48 INFO]: 2
[21:25:48 INFO]: 2
[21:25:48 INFO]: 1
[21:25:48 INFO]: 1
[21:25:48 INFO]: 2
[21:25:48 INFO]: 1
[21:25:48 INFO]: 2
[21:25:48 INFO]: 1
[21:25:48 INFO]: 2
[21:25:48 INFO]: 2
[21:25:48 INFO]: 1
[21:25:48 INFO]: 2
[21:25:48 INFO]: 1
[21:25:48 INFO]: 2
[21:25:48 INFO]: 2
[21:25:48 INFO]: 1
[21:25:48 INFO]: 2
[21:25:48 INFO]: 1
[21:25:48 INFO]: 1
[21:25:48 INFO]: 2
[21:25:48 INFO]: 2
[21:25:48 INFO]: 1
[21:25:48 INFO]: 2
[21:25:48 INFO]: 2
[21:25:48 INFO]: 2
[21:25:48 INFO]: 2
[21:25:48 INFO]: 1
[21:25:48 INFO]: 2
[21:25:48 INFO]: 2
[21:25:48 INFO]: 2
[21:25:48 INFO]: 1
[21:25:48 INFO]: 2
[21:25:48 INFO]: 2
[21:25:48 INFO]: 2
[21:25:48 INFO]: 2
[21:25:48 INFO]: 2
[21:25:48 INFO]: 2
[21:25:48 INFO]: 1
[21:25:48 INFO]: 2
[21:25:48 INFO]: 2
[21:25:48 INFO]: 2
[21:25:48 INFO]: 2
[21:25:48 INFO]: 2
[21:25:48 INFO]: 1
[21:25:48 INFO]: 2
[21:25:48 INFO]: 2
[21:25:48 INFO]: 2
[21:25:48 INFO]: 2
[21:25:48 INFO]: 2
[21:25:48 INFO]: 1
[21:25:48 INFO]: 2
[21:25:48 INFO]: 2
[21:25:48 INFO]: 2
[21:25:48 INFO]: 2
[21:25:48 INFO]: 2
[21:25:48 INFO]: 2
[21:25:48 INFO]: 1
[21:25:48 INFO]: 2
[21:25:48 INFO]: 2
[21:25:48 INFO]: 2
[21:25:48 INFO]: 2

**To Reproduce**
Just updated and restarted and this spam started including 1 212 12 12 infinite could be a conflict with something else that I cant point out. 

**Screenshots / Video**

## Server Information
- "/ae plinfo" link: https://paste.md-5.net/ivuwugukup
- Server log: https://mcpaste.io/1c014ad649666045

**Comment by Insprill** [comment] 2021-07-20 20:20
Duplicate of #2170

**Closed by Insprill** 2021-07-20 20:20 UTC
Labels: Resolution: Duplicate
