### ISSUE TITLE
Trench duplicating blocktrack lore - again

### ISSUE THREAD

**Issue by arceusxs2** [GC-spigot/AdvancedEnchantments#2324] opened 2021-08-29 18:26 UTC
## Details
Same as https://github.com/GC-spigot/AdvancedEnchantments/issues/2064
**Describe the bug**

Hello, theres bug with trench and blocktrack that i reported 2 months ago and was supposed to be fixed, but its not,
Thats the problem https://github.com/GC-spigot/AdvancedEnchantments/issues/2064
**To Reproduce** 

**Screenshots / Video**

https://prnt.sc/1qr7ukp

## Server Information
- "/ae plinfo" link: 
- Plugins version 8.6.7, Break Checks trues
- Server log:

**Comment by Insprill** [comment] 2021-08-29 21:23
Update AE.

**Comment by arceusxs2** [comment] 2021-08-30 09:47
Hello, i did that but it still didnt fix it.

**Comment by Insprill** [comment] 2021-08-30 16:46
Does experimental-block-breaking make a difference?

**Comment by arceusxs2** [comment] 2021-08-31 10:17
Turned it on but still having the same problem

**Comment by arceusxs2** [comment] 2021-08-31 19:47
https://paste.md-5.net/upidehowig

**Comment by Insprill** [comment] 2021-09-03 00:40
On 8.6.9 i can't reproduce this, can you update to that and see if it's still an issue? @arceusxs2

**Comment by arceusxs2** [comment] 2021-09-03 09:15
Tried, but sadly it didnt help.

**Comment by Insprill** [comment] 2021-09-03 09:40
Try with a fresh pickaxe. Maybe something is broken with the NBT data of that one.

**Comment by arceusxs2** [comment] 2021-09-03 09:55
Tried, but didnt help. Also i tried it on completly fresh server with unmodified configs of AE at all and so far what i can see, it happenes only when i have trench 9 + reforged 9 and unbreakable 1 on the pickaxe.

**Comment by Insprill** [comment] 2021-09-16 00:50
Fixed in the next update

**Closed by Insprill** 2021-09-16 00:50 UTC
Labels: Priority: High, Bug: Confirmed, Resolution: Accepted
