### ISSUE TITLE
Cannot Upgrade Level of Enchant when Tool/Weapon/Armor has lower level of enchant

### ISSUE THREAD

**Issue by J14P** [GC-spigot/AdvancedEnchantments#2092] opened 2021-06-27 19:17 UTC
## Details

**Describe the bug**
When i put my pickaxe with experience 1 into the anvil and experience 5 book into the anvil the pickaxe shows up with experience 5 but it does not let me take the pickaxe from the anvil. It doesn't show if a certain amount of experience is needed either

**To Reproduce**
Put any tool/weapon/armor into the anvil that has a lower level enchant then put a book with that same enchant but a higher level.

**Screenshots / Video**

https://user-images.githubusercontent.com/86026838/123556685-9c0c1c80-d75a-11eb-9916-9e3eab22ce1c.mp4

## Server Information
- "/ae plinfo" link: https://paste.md-5.net/otafisavoh
- Server log: https://mcpaste.io/671e60dc5ed21138

**Comment by Insprill** [comment] 2021-06-28 11:54
Duplicate of #2081. Please try 8.3.7 and see if that fixes it, if it doesn't comment this info on that issue.

**Closed by Insprill** 2021-06-28 11:54 UTC
Labels: Resolution: Duplicate
