### ISSUE TITLE
Soul Miner Doesn't give souls 

### ISSUE THREAD

**Issue by OceanBurgerEx** [GC-spigot/AdvancedEnchantments#1814] opened 2021-03-25 14:39 UTC
Basically, my players were using soul miner on my server (w/ a soul tracker) and it didn't give them souls, however, the hearts particle effect did show up occasionally which I assume goes with the souls. I tested the same thing on a different pick, and it had the same results.
I'm not sure if I need to provide other info but If so I would be happy to.

Server Information
- Server Version: Paper 1.16.5
- Plugin Version: 8.0.0-Pre21.3

**Comment by Insprill** [comment] 2021-03-30 06:39
Duplicate of #1804

**Closed by Insprill** 2021-03-30 06:39 UTC
Labels: Resolution: Duplicate
