### ISSUE TITLE
@block no work

### ISSUE THREAD

**Issue by BeilorDA** [GC-spigot/AdvancedEnchantments#4641] opened 2024-09-19 23:25 UTC
### Describe the bug

I updated the plugin to the latest version and the enchantment stopped working. Here I send it in full:

```yml
gemificar:
  display: '%group-color%✦ Gemificar'
  description: Posibilidad de que un bloque de mineral se convierta en su bloque
  applies-to: Pickaxe
  type: MINING
  group: FABLED
  settings:
    showActionBar: true
  applies:
    - ALL_PICKAXE
  levels:
    '1':
      chance: 3
      cooldown: 5
      effects:
        - PARTICLE:GLOW:30:0.5 @Block
        - 'SET_BLOCK:GOLD_BLOCK @Block <condition>%block type% contains GOLD_ORE : %allow%</condition>'
        - 'SET_BLOCK:IRON_BLOCK @Block <condition>%block type% contains IRON_ORE : %allow%</condition>'
        - 'SET_BLOCK:COAL_BLOCK @Block <condition>%block type% contains COAL_ORE : %allow%</condition>'
        - 'SET_BLOCK:EMERALD_BLOCK @Block <condition>%block type% contains EMERALD_ORE : %allow%</condition>'
        - 'SET_BLOCK:COPPER_BLOCK @Block <condition>%block type% contains copper_ore : %allow%</condition>'
        - 'SET_BLOCK:REDSTONE_BLOCK @Block <condition>%block type% contains redstone_ore : %allow%</condition>'
        - 'SET_BLOCK:LAPIS_BLOCK @Block <condition>%block type% contains lapis_ore : %allow%</condition>'
        - 'SET_BLOCK:DIAMOND_BLOCK @Block <condition>%block type% contains diamond_ore : %allow%</condition>'
    '2':
      chance: 90
      effects:
        - PARTICLE:GLOW:30:0.5 @Block
        - 'SET_BLOCK:GOLD_BLOCK @Block <condition>%block type% contains GOLD_ORE : %allow%</condition>'
        - 'SET_BLOCK:IRON_BLOCK @Block <condition>%block type% contains IRON_ORE : %allow%</condition>'
        - 'SET_BLOCK:COAL_BLOCK @Block <condition>%block type% contains COAL_ORE : %allow%</condition>'
        - 'SET_BLOCK:EMERALD_BLOCK @Block <condition>%block type% contains EMERALD_ORE : %allow%</condition>'
        - 'SET_BLOCK:COPPER_BLOCK @Block <condition>%block type% contains copper_ore : %allow%</condition>'
        - 'SET_BLOCK:REDSTONE_BLOCK @Block <condition>%block type% contains redstone_ore : %allow%</condition>'
        - 'SET_BLOCK:LAPIS_BLOCK @Block <condition>%block type% contains lapis_ore : %allow%</condition>'
        - 'SET_BLOCK:DIAMOND_BLOCK @Block <condition>%block type% contains diamond_ore : %allow%</condition>'```

### How to reproduce

I simply updated the plugin from version 9.10.1 (if I'm not mistaken) to the latest

### Screenshots / Videos

https://cdn.discordapp.com/attachments/1286461265765601352/1286461279992680498/image.png?ex=66edfdee&is=66ecac6e&hm=cac18e3480e262f50f6a6cc8de757895e41ca3b301f7745ec0231dc7af41f168&


https://prnt.sc/Jfdjq3ps6eG5

### "/ae plinfo" link

https://paste.md-5.net/xovujagomu

### Server Log

https://mclo.gs/fkKUFBD

**Comment by ThomasWega** [comment] 2024-09-21 15:25
duplicate of https://github.com/GC-spigot/AdvancedEnchantments/issues/4639

**Closed by ThomasWega** 2024-09-21 15:25 UTC
Labels: Bug: Unconfirmed
