### ISSUE TITLE
Could not pass event BlockBreakEvent to AdvancedEnchantments v9.4.8

### ISSUE THREAD

**Issue by Jimaie72** [GC-spigot/AdvancedEnchantments#3714] opened 2023-10-07 13:43 UTC
### Describe the bug

I use the plugin : 
https://www.spigotmc.org/resources/farmingupgrade.76907/

When i do a left click with a hoe, full bugs on my console

### How to reproduce

Left click with hoe

### Screenshots / Videos

[15:40:07 ERROR]: Could not pass event BlockBreakEvent to AdvancedEnchantments v9.4.8
java.lang.IllegalArgumentException: No enum constant org.bukkit.Material.TORCHFLOWER
        at java.lang.Enum.valueOf(Enum.java:273) ~[?:?]
        at org.bukkit.Material.valueOf(Material.java:112) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        at net.advancedplugins.ae.impl.utils.CropUtils.isFullyGrown(CropUtils.java:143) ~[AdvancedEnchantments-9.4.8.jar:?]
        at net.advancedplugins.ae.impl.effects.effects.mechanics.triggers.internal.MiningTrigger.onBlockBreak(MiningTrigger.java:101) ~[AdvancedEnchantments-9.4.8.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor854.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:75) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:git-Paper-280]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:670) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        at no.hyp.farmingupgrade.FarmingUpgradePlugin.harvestCrop(FarmingUpgradePlugin.java:490) ~[farmingupgrade-1.5.0.jar:?]
        at no.hyp.farmingupgrade.FarmingUpgradePlugin.initiateHarvest(FarmingUpgradePlugin.java:447) ~[farmingupgrade-1.5.0.jar:?]
        at no.hyp.farmingupgrade.FarmingUpgradePlugin.onFarm(FarmingUpgradePlugin.java:428) ~[farmingupgrade-1.5.0.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor262.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:75) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:git-Paper-280]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:670) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        at net.minecraft.server.level.ServerPlayerGameMode.destroyBlock(ServerPlayerGameMode.java:369) ~[?:?]
        at net.minecraft.server.level.ServerPlayerGameMode.destroyAndAck(ServerPlayerGameMode.java:328) ~[?:?]
        at net.minecraft.server.level.ServerPlayerGameMode.handleBlockBreakAction(ServerPlayerGameMode.java:266) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handlePlayerAction(ServerGamePacketListenerImpl.java:1883) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundPlayerActionPacket.handle(ServerboundPlayerActionPacket.java:42) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundPlayerActionPacket.a(ServerboundPlayerActionPacket.java:15) ~[?:?]
        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$1(PacketUtils.java:51) ~[?:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.19.2.jar:git-Paper-280]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1341) ~[paper-1.19.2.jar:git-Paper-280]
        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:185) ~[paper-1.19.2.jar:git-Paper-280]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1318) ~[paper-1.19.2.jar:git-Paper-280]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1311) ~[paper-1.19.2.jar:git-Paper-280]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1289) ~[paper-1.19.2.jar:git-Paper-280]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1177) ~[paper-1.19.2.jar:git-Paper-280]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:305) ~[paper-1.19.2.jar:git-Paper-280]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]

### "/ae plinfo" link

https://paste.md-5.net/fovajovefo

**Comment by austv** [comment] 2023-10-07 17:45
@ThomasWega I get this error since 4.9.7, and is not just with blocks:

[14:43:37 ERROR]: Could not pass event EntityDamageByEntityEvent to AdvancedEnchantments v9.4.7
java.lang.ClassCastException: null

In this case, I don't know how to reproduce, but I would guess is hitting mobs with ae enchants

**Comment by ThomasWega** [comment] 2023-10-07 19:17
Please send the full error

**Comment by austv** [comment] 2023-10-07 19:17
This is the full error on console

**Comment by austv** [comment] 2023-10-07 19:18
![image](https://github.com/GC-spigot/AdvancedEnchantments/assets/66658478/e413d980-6146-4074-bab6-21c975753527)

**Comment by ThomasWega** [comment] 2023-10-07 19:32
Can you please try 9.4.8?

**Comment by GC-spigot** [comment] 2023-10-09 07:35
> ![image](https://user-images.githubusercontent.com/66658478/273405123-e413d980-6146-4074-bab6-21c975753527.png)

That is not a full error, that error happens after same error is sent a few times and it's being rate limited to not spam same information. We need either:
1. your full latest.log file
2. this error, but in full. You will need to find the first instance of this error in logs file and send it.

**Comment by Jimaie72** [comment] 2023-10-09 10:44
[latest.log](https://github.com/GC-spigot/AdvancedEnchantments/files/12845071/latest.log)

**Comment by RageOfFire** [comment] 2023-10-09 14:51
I got a same problem without farmupgrade plugin it's seem like because I using old minecraft version (v1.16.5) ?

**Comment by ThomasWega** [comment] 2023-10-10 06:35
The BlockBreakEvent will be fixed in next version. For the EntityDamageByEntityEvent, please create a new issue if you still have it after the next release

**Closed by ThomasWega** 2023-10-10 06:35 UTC
Labels: Bug: Confirmed, Status: Awaiting Response
