### ISSUE TITLE
broken mobtrak

### ISSUE THREAD

**Issue by wundertraume** [GC-spigot/AdvancedEnchantments#3950] opened 2024-01-20 18:51 UTC
### Describe the bug

When you take mobtrak and apply it to an item, stattrak is applied - stattrak

### How to reproduce

`/ae giveitem name mobtrak 1` and apply it

### Screenshots / Videos

https://www.youtube.com/watch?v=jUqFn9SOQzk

### "/ae plinfo" link

https://paste.md-5.net/yuwodaluvo

**Comment by ThomasWega** [comment] 2024-01-22 14:21
Seems to be a duplicate of https://github.com/GC-spigot/AdvancedEnchantments/issues/3947. Will handle the issue there

**Closed by ThomasWega** 2024-01-22 14:21 UTC
Labels: Bug: Confirmed
