### ISSUE TITLE
Any Potion Effect CE | Permanent Effect

### ISSUE THREAD

**Issue by itslukemango** [GC-spigot/AdvancedEnchantments#2206] opened 2021-07-28 17:01 UTC
## Details

**Describe the bug**

When you replace a helmet with a CE that gives a potion effect with any item using /hat it retains the potion effects from the replaced helmet, for example, put obsidian shield on a diamond helmet, hold a dirt block and do /hat

**To Reproduce**

Put obsidian shield on a diamond helmet, hold a dirt block and do /hat

**Screenshots / Video**

https://streamable.com/0x9vg5

## Server Information
- "/ae plinfo" link:  https://paste.md-5.net/kaquwunaro
- Server log:  https://mclo.gs/Yv9B0fY

**Comment by Insprill** [comment] 2021-07-28 18:09
Duplicate of #2096

**Closed by Insprill** 2021-07-28 18:09 UTC
Labels: Resolution: Duplicate
