### ISSUE TITLE
The "/apply" command works wrongly

### ISSUE THREAD

**Issue by Ecilpse** [GC-spigot/AdvancedEnchantments#4607] opened 2024-09-02 02:56 UTC
### Describe the bug

#4468 
I uploaded issues, but there is no answer after 40 days.

### How to reproduce

#4468 

### "/ae plinfo" link

https://paste.md-5.net/ipecojapaq

**Comment by SirJben** [comment] 2024-09-03 13:28
Duplicate of #4468

**Closed by SirJben** 2024-09-03 13:28 UTC
Labels: Bug: Unconfirmed
