### ISSUE TITLE
Enchants from lore line are not updating and placeholder problem

### ISSUE THREAD

**Issue by n0tailz-debug** [GC-spigot/AdvancedEnchantments#2276] opened 2021-08-15 02:29 UTC
## Details

**Describe the bug**
When a player upgrades a custom enchant example Curse 3 you will need Curse 3 to make it Curse 4, it will say its successful but
it stays Curse 3 and I tried to manually enchant it using /ae enchant Curse 4 it says it got removed. Like the Curse 3 loreline isnt changing but the custom enchant is working.

Also when I /ae enchant curse 4 from curse 3 it says its downgraded  from **%prevlevel%**

**To Reproduce** 
Just upgrade a custom enchant 

**Screenshots / Video**

![1](https://user-images.githubusercontent.com/78484864/129465001-30d3b702-2906-4569-bbba-19b04cd758f0.PNG)

## Server Information
- https://paste.md-5.net/dawiqogizo
- https://mcpaste.io/e726f227764d2834

**Comment by n0tailz-debug** [comment] 2021-08-15 02:35
https://youtu.be/xWP5S98mOJk

Here is a video link of the bug I tried to upload it but its bigger than 10mb

**Comment by n0tailz-debug** [comment] 2021-08-15 02:37
Oof, so i tried one again I enchanted an item using /ae enchant Cactus 1
and then i got a Cactus 2 book and I enchanted it on the item and look 
![312](https://user-images.githubusercontent.com/78484864/129465176-127d7cd3-fc33-4f74-b336-9b8ebfd761f6.PNG)

**Comment by Insprill** [comment] 2021-08-15 03:48
Duplicate of #2279 (foxed in next update).

As for the second issue, change the placeholder to `%prevLevel%`.

**Closed by Insprill** 2021-08-15 03:48 UTC
Labels: Resolution: Duplicate

**Comment by n0tailz-debug** [comment] 2021-08-15 04:09
> Duplicate of #2279 (foxed in next update).
> 
> As for the second issue, change the placeholder to `%prevLevel%`.

![3232](https://user-images.githubusercontent.com/78484864/129466803-386147c0-de55-43b2-8526-bfd414c36271.PNG)
Its already like '%prevLevel%'

**Comment by Insprill** [comment] 2021-08-15 04:24
Try letting the locale file regenerate
