### ISSUE TITLE
Entire server crash

### ISSUE THREAD

**Issue by juancruzdal** [GC-spigot/AdvancedEnchantments#2256] opened 2021-08-11 22:49 UTC
[19:15:42] [Server thread/INFO]: Exigentee issued server command: /e
[19:16:45] [PaperSpigot Watchdog Thread/ERROR]: The server has stopped responding!
[19:16:45] [PaperSpigot Watchdog Thread/ERROR]: Please report this to PaperSpigot directly!
[19:16:45] [PaperSpigot Watchdog Thread/ERROR]: Be sure to include ALL relevant console errors and Minecraft crash reports
[19:16:45] [PaperSpigot Watchdog Thread/ERROR]: PaperSpigot version: git-PaperSpigot-"4c7641d" (MC: 1.8.8)
[19:16:45] [PaperSpigot Watchdog Thread/ERROR]: ------------------------------
[19:16:45] [PaperSpigot Watchdog Thread/ERROR]: Server thread dump (Look for plugins here before reporting to PaperSpigot!):
[19:16:45] [PaperSpigot Watchdog Thread/ERROR]: ------------------------------
[19:16:45] [PaperSpigot Watchdog Thread/ERROR]: Current Thread: Server thread
[19:16:45] [PaperSpigot Watchdog Thread/ERROR]: 	PID: 18 | Suspended: false | Native: false | State: RUNNABLE
[19:16:45] [PaperSpigot Watchdog Thread/ERROR]: 	Stack:
[19:16:45] [PaperSpigot Watchdog Thread/ERROR]: 		java.util.regex.Pattern$Start.match(Pattern.java:3475)
[19:16:45] [PaperSpigot Watchdog Thread/ERROR]: 		java.util.regex.Matcher.search(Matcher.java:1248)
[19:16:45] [PaperSpigot Watchdog Thread/ERROR]: 		java.util.regex.Matcher.find(Matcher.java:637)
[19:16:45] [PaperSpigot Watchdog Thread/ERROR]: 		java.util.regex.Matcher.replaceAll(Matcher.java:951)
[19:16:45] [PaperSpigot Watchdog Thread/ERROR]: 		java.lang.String.replaceAll(String.java:2223)
[19:16:45] [PaperSpigot Watchdog Thread/ERROR]: 		net.advancedplugins.ae.enchanthandler.enchantments.AdvancedEnchantment.getMaterialsNice(AdvancedEnchantment.java:283)
[19:16:45] [PaperSpigot Watchdog Thread/ERROR]: 		net.advancedplugins.ae.features.usercommands.Enchantments.parseVariables(Enchantments.java:361)
[19:16:45] [PaperSpigot Watchdog Thread/ERROR]: 		net.advancedplugins.ae.features.usercommands.Enchantments.open(Enchantments.java:282)
[19:16:45] [PaperSpigot Watchdog Thread/ERROR]: 		net.advancedplugins.ae.features.enchanter.InventoryEvent.onClick(InventoryEvent.java:83)
[19:16:45] [PaperSpigot Watchdog Thread/ERROR]: 		net.advancedplugins.ae.globallisteners.InventoryClicks.onInvClix(InventoryClicks.java:30)
[19:16:45] [PaperSpigot Watchdog Thread/ERROR]: 		sun.reflect.GeneratedMethodAccessor730.invoke(Unknown Source)
[19:16:45] [PaperSpigot Watchdog Thread/ERROR]: 		sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[19:16:45] [PaperSpigot Watchdog Thread/ERROR]: 		java.lang.reflect.Method.invoke(Method.java:498)
[19:16:45] [PaperSpigot Watchdog Thread/ERROR]: 		org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:300)
[19:16:45] [PaperSpigot Watchdog Thread/ERROR]: 		co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78)
[19:16:45] [PaperSpigot Watchdog Thread/ERROR]: 		org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
[19:16:45] [PaperSpigot Watchdog Thread/ERROR]: 		org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:517)
[19:16:45] [PaperSpigot Watchdog Thread/ERROR]: 		org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:502)
[19:16:45] [PaperSpigot Watchdog Thread/ERROR]: 		net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:1657)
[19:16:45] [PaperSpigot Watchdog Thread/ERROR]: 		net.minecraft.server.v1_8_R3.PacketPlayInWindowClick.a(SourceFile:31)
[19:16:45] [PaperSpigot Watchdog Thread/ERROR]: 		net.minecraft.server.v1_8_R3.PacketPlayInWindowClick.a(SourceFile:9)
[19:16:45] [PaperSpigot Watchdog Thread/ERROR]: 		net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13)
[19:16:45] [PaperSpigot Watchdog Thread/ERROR]: 		java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[19:16:45] [PaperSpigot Watchdog Thread/ERROR]: 		java.util.concurrent.FutureTask.run(FutureTask.java:266)
[19:16:45] [PaperSpigot Watchdog Thread/ERROR]: 		net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44)
[19:16:45] [PaperSpigot Watchdog Thread/ERROR]: 		net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:774)
[19:16:45] [PaperSpigot Watchdog Thread/ERROR]: 		net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:378)
[19:16:45] [PaperSpigot Watchdog Thread/ERROR]: 		net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:713)
[19:16:45] [PaperSpigot Watchdog Thread/ERROR]: 		net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:616)
[19:16:45] [PaperSpigot Watchdog Thread/ERROR]: 		java.lang.Thread.run(Thread.java:748)

To reproduce: type /e

**Comment by Insprill** [comment] 2021-08-12 03:56
Duplicate of #2254

**Closed by Insprill** 2021-08-12 03:56 UTC
Labels: Resolution: Duplicate

**Comment by juancruzdal** [comment] 2021-08-12 12:26
I found the cause the error comes when you right click a enchantment too many tomes to see the enchants info
