### ISSUE TITLE
Duplication

### ISSUE THREAD

**Issue by DustedSoul** [GC-spigot/AdvancedEnchantments#2227] opened 2021-08-03 02:14 UTC
Whenever the unbreakable enchantment is paired with Vein Miner or Trench, it'll cause the item to duplicate by placing a non enchanted pickaxe into your offhand.

**Comment by Insprill** [comment] 2021-08-03 03:13
Duplicate of #2215 (fixed in next update)

**Closed by Insprill** 2021-08-03 03:13 UTC
Labels: Resolution: Duplicate
