### ISSUE TITLE
Trench effect unreliable

### ISSUE THREAD

**Issue by Dakotaa** [GC-spigot/AdvancedEnchantments#1938] opened 2021-05-06 18:35 UTC
## Details

**Describe the bug**
When using a pickaxe with the Trench effect, the correct area is not always broken. It seems to only happen when blocks are mined too quickly. If the player waits a moment before mining another block, it works fine. Happens with both the TRENCH:3 and CUSTOM_TRENCH:3:3:3 effects.

**To Reproduce**
Enchant an item with trench, mine blocks.

**Screenshots / Video**
https://i.giphy.com/media/AZorm23ObvRilVeEFR/giphy.mp4

## Server Information
- "/ae plinfo" link: https://paste.md-5.net/eqimubamap

**Comment by Insprill** [comment] 2021-05-07 18:50
Can you try removing your anticheat and seeing if that fixes it?

**Comment by Insprill** [comment] 2021-05-08 14:16
I see you also have CompatNoCheatPlus. We don't have support for that at the moment, can you try removing that and see if the issue goes away?

**Comment by Dakotaa** [comment] 2021-05-08 15:59
> I see you also have CompatNoCheatPlus. We don't have support for that at the moment, can you try removing that and see if the issue goes away?

Yep, that was the problem. Are there any plans to support it in the future?

**Comment by Insprill** [comment] 2021-05-08 20:45
You can create a feature request to add support for it. I'm going to close this since that was the cause

**Closed** 2021-05-08 20:45 UTC
Labels: Bug: Unconfirmed
