### ISSUE TITLE
Somethign wrong with secret dust?

### ISSUE THREAD

**Issue by steda1985** [GC-spigot/AdvancedEnchantments#2004] opened 2021-05-26 14:36 UTC
Secret dust throwing an error

[14:11:30] [Server thread/WARN]: java.lang.IllegalStateException: zip file closed
[14:11:30] [Server thread/WARN]: 	at java.util.zip.ZipFile.ensureOpen(ZipFile.java:686)
[14:11:30] [Server thread/WARN]: 	at java.util.zip.ZipFile.getEntry(ZipFile.java:315)
[14:11:30] [Server thread/WARN]: 	at java.util.jar.JarFile.getEntry(JarFile.java:240)
[14:11:30] [Server thread/WARN]: 	at java.util.jar.JarFile.getJarEntry(JarFile.java:223)
[14:11:30] [Server thread/WARN]: 	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:165)
[14:11:30] [Server thread/WARN]: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
[14:11:30] [Server thread/WARN]: 	at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:119)
[14:11:30] [Server thread/WARN]: 	at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:114)
[14:11:30] [Server thread/WARN]: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
[14:11:30] [Server thread/WARN]: 	at net.advancedplugins.ae.handlers.lootPopulation.PopulationHandler.getLoot(PopulationHandler.java:73)
[14:11:30] [Server thread/WARN]: 	at net.advancedplugins.ae.handlers.lootPopulation.listeners.WorldLootPopulator.generateLoot(WorldLootPopulator.java:43)
[14:11:30] [Server thread/WARN]: 	at net.advancedplugins.ae.handlers.lootPopulation.listeners.WorldLootPopulator.populate(WorldLootPopulator.java:31)
[14:11:30] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.Chunk.loadCallback(Chunk.java:891)
[14:11:30] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.PlayerChunk.lambda$null$15(PlayerChunk.java:775)
[14:11:30] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.PlayerChunkMap$CallbackExecutor.run(PlayerChunkMap.java:204)
[14:11:30] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.ChunkProviderServer$a.executeNext(ChunkProviderServer.java:1078)
[14:11:30] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.ChunkProviderServer.runTasks(ChunkProviderServer.java:660)
[14:11:30] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.MinecraftServer.bb(MinecraftServer.java:1272)
[14:11:30] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.MinecraftServer.executeNext(MinecraftServer.java:1256)
[14:11:30] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119)
[14:11:30] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.MinecraftServer.sleepForTick(MinecraftServer.java:1217)
[14:11:30] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1131)
[14:11:30] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:290)
[14:11:30] [Server thread/WARN]: 	at java.lang.Thread.run(Thread.java:748)
[14:11:30] [Server thread/INFO]: Failed to generate AdvancedEnchantmetns Random Loot for item SECRET_DUST: error is located in console. 
[14:11:30] [Server thread/INFO]: It is most likely a configuration issue and this item's configuration should be checked before reporting.

**Comment by Insprill** [comment] 2021-05-26 18:13
Duplicate of #2003

**Closed** 2021-05-26 18:13 UTC
Labels: Bug: Confirmed, Resolution: Duplicate
