### ISSUE TITLE
Duplication with Trench and Vein Miner

### ISSUE THREAD

**Issue by MasonX3** [GC-spigot/AdvancedEnchantments#3630] opened 2023-09-03 21:31 UTC
### Describe the bug

When using an enchanted pickaxe or shovel with a vein miner or trench enchantment, stacked with an identical pickaxe or one with at least vein miner or trench enchantments in your offhand, any block mined will drop two of said block. This includes shulker boxes and their contents.

P.S. (I've removed the Tunnel and Vein Miner enchantments for the purposes of keeping my server stable)

### How to reproduce

To recreate this bug, all you need to do is have an enchantment with a TRENCH or Vein Mining Enchantment on it, as well as a pickaxe in your offhand with the same enchants. 

Mine any block, including shulker boxes, and you will receive an exact duplicate of it.

### "/ae plinfo" link

https://paste.md-5.net/yumejefuwa

**Comment by ThomasWega** [comment] 2023-09-03 21:52
Duplicate of https://github.com/GC-spigot/AdvancedEnchantments/issues/3511

We know about this issue and are working on it :)

**Closed by ThomasWega** 2023-09-03 21:52 UTC
Labels: Bug: Unconfirmed
