### ISSUE TITLE
[Issue] KEEP_ON_DEATH Duplication

### ISSUE THREAD

**Issue by Kbryst** [GC-spigot/AdvancedEnchantments#1584] opened 2020-12-08 19:37 UTC
**Describe the bug**
Using KEEP_ON_DEATH I am able to duplicate armor by killing the player in lava or water. The armor does not need to be worn to duplicate. 

**To Reproduce**
I threw "Soulbound" on a helmet and then drowned myself. I tested with it in my inventory and on my head, it duplicated each time. I also did the same with a pickaxe in my inventory, it did not at any point duplicate.

**Server Information (please complete the following information):**
- Server Version: Paper 1.16.4 
- Plugin Version: 8.0.0-Pre16.2 (1 version behind on spigot as of earlier)

My final config I'm using 

soulbound:
  display: '&7Soulbound'
  description: "Keeps item on death."
  applies-to: 'All gear'
  type: 'DEATH;PASSIVE_DEATH'
  group: 'LEGENDARY'
  applies:
    - ALL_SWORD
    - ALL_AXE
    - ALL_PICKAXE
    - ALL_SPADE
    - ALL_HOE
    - BOW
    - CROSSBOW
    - ALL_HELMET
    - ALL_CHESTPLATE
    - ALL_LEGGINGS
    - ALL_BOOTS
    - SHIELD
    - FISHING_ROD
    - SHEARS
    - TRIDENT
  levels:
    1:
      effects:
        - 'KEEP_ON_DEATH'

*Not too different from default config, just removed chance and cooldown. File does say "(only viable for armor & held item)" so I'm assuming I have this correct. 

This was done on a clean test server with minimum plugins like CMI.

**Comment by Alphagetti-Yeti** [comment] 2021-02-08 02:26
Having the same problem. Please fix.

**Comment by Insprill** [comment] 2021-02-24 17:42
I wasn't able to reproduce this, is it still occurring? If it is could you send a video of it if possible?

**Comment by Kbryst** [comment] 2021-02-24 19:01
I haven't used the plugin since, I wouldn't know.

**Comment by Insprill** [comment] 2021-02-24 20:33
@Alphagetti-Yeti is it still happening for you?

**Comment by Alphagetti-Yeti** [comment] 2021-03-26 02:20
@Insprill sorry for late reply hadn't been on here to look for any responses. As far as I am aware this problem was still on going on the server I was using it on (just a server with friends) however I haven't been on in a while and could not tell you the status of the glitch. It may have been fixed I also made a issue post when I discovered this process im fairly certain I listed the plugins I was using so if the cause wasn't one of them then if you follow my explanation you should get the same result.

**Comment by Insprill** [comment] 2021-03-26 03:06
Alright, going to close this issue then

**Closed by Insprill** 2021-03-26 03:06 UTC
Labels: issue
