### ISSUE TITLE
TP_DROP with silktouch doesnt drop torches

### ISSUE THREAD

**Issue by xCloudiness** [GC-spigot/AdvancedEnchantments#2264] opened 2021-08-12 17:08 UTC
## Details

**Describe the bug**
 When using a telepathy enchant or something that uses TP_DROP and mine a torch that is placed in a wall it wont drop any torches nor place any torches back to your inventory

**To Reproduce** 

Have a silk touch pick with an enchant that uses telepathy or something like this
  levels:
    1:
      effects:
        - 'POTION:FAST_DIGGING:0'
        - 'TP_DROPS'

and mine a torch in a wall and it will not drop any torches
**Screenshots / Video**

https://imgur.com/sfAN92W

## Server Information
- "/ae plinfo" link:  https://paste.md-5.net/enociluxap
- Server log:  https://mcpaste.io/be5043b6171e507a

**Comment by Insprill** [comment] 2021-08-13 00:22
Can you send the full enchantment? Default telepathy works fine for me when breaking wall torches.

**Comment by xCloudiness** [comment] 2021-08-13 04:11
okay
```yml
hasteshift:
  display: '%group-color%Haste Shift'
  description: "&7Gain haste and teleport drops \nto you while using tools."
  applies-to: 'Tools'
  type: 'HELD;MINING'
  settings:
    removable: false
  group: 'ADVANCE'
  applies:
    - ALL_PICKAXE
    - ALL_SPADE
    - ALL_AXE
  levels:
    1:
      effects:
        - 'POTION:FAST_DIGGING:0'
        - 'TP_DROPS'
    2:
      effects:
        - 'POTION:FAST_DIGGING:1'
        - 'TP_DROPS'
 ```
 heres the entire enchantment

**Comment by Insprill** [comment] 2021-08-13 17:11
Using that enchant on 8.6.3 copying exactly what you did in the video I still couldn't reproduce it. Can you try removing all your plugins and see if it's still an issue and if it isn't add them back still it comes back?

**Comment by xCloudiness** [comment] 2021-08-13 19:16
Using 8.6.4 with a silk touch and it still doesnt work 
https://discord.com/channels/861277994462478346/861277994462478349/875817011857489982
this bug only applies to silk touch picks and not any other bugs
"/ae plinfo" link: https://paste.md-5.net/atujuqojul
Server log: https://mcpaste.io/2c7a1d4771e2d4fe

**Comment by xCloudiness** [comment] 2021-08-13 19:28
I tried using the premade telepathy and it gives the same result

https://user-images.githubusercontent.com/63063098/129409083-080df93b-092d-4084-b2d1-c1f9781742c1.mp4
"/ae plinfo" link: https://paste.md-5.net/oyalegayug
Server log: https://mcpaste.io/e04fce49794e2e5c

**Comment by Insprill** [comment] 2021-08-13 21:56
Do you have experimental-block-breaking enabled? If not try enabling it.

**Comment by xCloudiness** [comment] 2021-08-15 16:39
I tried having experimental-block-breaking to true, i wonder if i did it correctly though. sorry for the late reply, there was something we had to attend to
```yml

telepathy:
  display: "%group-color%Telepathy"
  description: "Automatically places blocks broken\nby tools in your inventory."
  applies-to: "Tools"
  type: "MINING"
  group: "UNIQUE"
  experimental-block-breaking: TRUE
  applies:
    - ALL_PICKAXE
    - ALL_SPADE
    - ALL_AXE
  levels:
    1:
      chance: 40
      effects:
        - "TP_DROPS"
    2:
      chance: 60
      effects:
        - "TP_DROPS"
    3:
      chance: 80
      effects:
        - "TP_DROPS"
    4:
      effects:
        - "TP_DROPS"
```

**Comment by Insprill** [comment] 2021-08-15 16:54
The setting is in the config.yml, towards the bottom

**Comment by xCloudiness** [comment] 2021-08-15 17:37
I've set it true on the config.yml and nothing has changed.

**Comment by xCloudiness** [comment] 2021-08-15 17:46
The plugin does read the enchant, maybe because its trying to give WALL_TORCH as an item?
![image](https://user-images.githubusercontent.com/63063098/129487566-d0734285-4011-4661-9617-3f81b1d119b9.png)

**Comment by xCloudiness** [comment] 2021-08-15 17:48
It does seem like its a real item but it doesnt have any data to it (This is from LibsDisguise)
![image](https://user-images.githubusercontent.com/63063098/129487601-7d95259c-52f2-4a58-9dc1-02f8e702f797.png)

**Comment by Insprill** [comment] 2021-08-15 17:48
Yeah thats what #2275 is about. Not sure how it's bypassing getting converted to a normal item but ill take a look at it Monday, might fix it.

**Comment by xCloudiness** [comment] 2021-08-15 17:51
This bug also applies to logs, if you mine a log with telepathy+silktouch with a different orientation it gives you a different item with an NBT Tag

**Comment by xCloudiness** [comment] 2021-08-15 18:02
I am not sure if this might help or not but i'll drop my current config.yml here
https://mcpaste.io/037f4500732af852

**Comment by xCloudiness** [comment] 2021-08-15 18:08
On further inspection this also makes it so when you mine a bookshelf with telepathy it only drops 1 book instead of 3
![Be2zZeJakc](https://user-images.githubusercontent.com/63063098/129488143-94eb0e05-f21a-4d0d-8f4d-a25ebc02fc1e.gif)

**Comment by xCloudiness** [comment] 2021-08-16 04:37
while reading the console this has popped up.
![image](https://user-images.githubusercontent.com/63063098/129512042-301a5272-bbed-46f5-8594-b32669b3e0ae.png)

**Comment by Insprill** [comment] 2021-08-16 07:48
Yup thats the cause. The log issue show be fixed as of a couple versions ago

**Comment by xCloudiness** [comment] 2021-08-16 09:47
the log issue still occurs on 8.6.4 though..

**Comment by Insprill** [comment] 2021-08-18 00:19
Fixed in the next update

**Closed by Insprill** 2021-08-18 00:19 UTC
Labels: Bug: Confirmed, Resolution: Accepted

**Comment by FrontierPixelmon** [comment] 2021-10-19 01:50
> 
> 
> Fixed in the next update

Telepathy + Silktouch = doesn't pickup Redstone
Looks like it is a similar issue to the post referenced below. Telepathy works just fine with redstone, however as soon as silktouch is applied; the combination of the two breaks redstone without picking it up.

Fixed in the next update

_Originally posted by @Insprill in https://github.com/GC-spigot/AdvancedEnchantments/issues/2264#issuecomment-900717072_
